### ISSUE TITLE
Submission by status/detail view: Can't submit note on mobile

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#1005]
Submit button on mobile view for submitting notes on Submission by status/detail view is currently not functioning - does nothing when pressed. Can you please take a look?

**Comment by chris-lawton** [comment]
Hi Maya,

This is now fixed on dev.

Thanks,
Chris

**Comment by gibbsmaya** [comment]
Confirming this now works.

FYI @danblah.

Can you get this ready for deployment to live, either via @todd-dembrey or @frjo? Thanks.
