### ISSUE TITLE
Dashboard: Waiting for your review block: updates

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#1009]
'Waiting for your review' block which has been updated in #937 needs to be updated in terms of submissions being displayed in this block and the subsequent pre-filtered submission list (accessible via the 'show all' link at bottom of table if more than 5 submissions).

After discussion with OTF, agreed approach for an initial release is that both waiting for your review and the corresponding 'show all' page should show all submissions where I am assigned as reviewer, in any status other than a final determined state, i.e. all states other than accepted, dismissed, concept accepted and invite to proposal (`?status=screening&status=more-information-required&status=internal-review&status=ready-for-discussion&status=ready-for-determination&status=advisory-council-review&status=ready-for-preliminary-determination&status=proposal-received&status=ready-for-final-determination&reviewers=9&query=`). The waiting for review block on dashboard should show the first 5 in the list as it does now, linking to all submissions prefiltered in the same way.

@frjo we were hoping you could undertake this work.
@todd-dembrey please add any further dev notes needed and then assign to @frjo ?

cc @danblah

**Comment by frjo** [comment]
Is this what you had in mind https://github.com/OpenTechFund/opentech.fund/pull/1030 ?

I bassed the pr on sprint-3-winter-2019 branch.

**Comment by gibbsmaya** [comment]
@todd-dembrey can you check this pls?

**Comment by todd-dembrey** [comment]
@gibbsmaya this is now on dev. 

* The dashboard "to review" list is now populated from all statuses in which you can give a review. 
* If you have more than 5 submissions in this list then the there is a link to the table pre-filtered with the same statuses as the dashboard.

**Comment by gibbsmaya** [comment]
Hi @todd-dembrey 

There are a few submissions that are not appearing in this block when I would expect them to. Acting as Lindsay, I should see the  following submissions in my 'waiting for review' block 
https://dev-apply.opentech.fund/apply/submissions/21/
https://dev-apply.opentech.fund/apply/submissions/10/
https://dev-apply.opentech.fund/apply/submissions/9/

Please can you take a look?

Thanks,
Maya

**Comment by todd-dembrey** [comment]
Hi Maya, this is now correct on staging.

21 - should not appear - she has submitted a review
9 - correctly appears
10 - Now appears

**Comment by gibbsmaya** [comment]
Thanks @todd-dembrey.

Waiting for your review block now working as expected but there is an issue with the 'all submissions' page that this links too. Again, see Lindsay's dashboard and go through to https://dev-apply.opentech.fund/apply/submissions/all/?reviewers=9screening&status=more-information-required&status=internal-review&status=ready-for-discussion&status=ready-for-determination&status=advisory-council-review&status=ready-for-preliminary-determination&status=invited-for-proposal&status=proposal-received&status=ready-for-final-determination

It may be a typo in the code?
![screen shot 2019-03-04 at 11 43 34](https://user-images.githubusercontent.com/19690895/53731514-e7f07480-3e72-11e9-9b79-80c78cbedcd2.png)

**Comment by todd-dembrey** [comment]
I have fixed this issue, the link is now correct of dev.

**Comment by gibbsmaya** [comment]
Done. Note that the show all page also includes submissions where the review has already been undertaken because we currently don't have a filter to differentiate between 'already reviewed' or 'yet to review'. This is a little confusing, but as things get determined they will disappear from this list. A filter could be added in future to deal with this.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina,

This is now ready for testing. This work is updating the logic of the submissions that appear in the 'Waiting for your review' block on dashboard. @fourthletter probably easiest for you to test this since there were submissions missing from your dashboard.

Please test this against the initial issue description and check this matches. Please also see my comment above (previous comment) about the pre-filtered 'all submissions' page that the user will land on.

Thanks,
Maya

**Comment by fourthletter** [comment]
I completed this test and all features are functional and visible. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey ready for live deployment.
