### ISSUE TITLE
Submission by round/status detail views: Review information: Reviewer roles and assignees

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#1016]
**Acceptance criteria**

- [x] API updated to include the following new information:
  * Role Icon URL
  * List of Agreers & disagreers (Name, icon URL, and opinion only)
  * List of assigned reviewers (both OTF staff and external reviewers, even if they have not completed a review)
- [x] Status tab in right hand column of Submission by round detail view page contains these two new bits of information presented in same way as review block in right hand column of submission detail page (e.g. https://dev-apply.opentech.fund/apply/submissions/6/)

**Design** 
Using existing output as per right hand column of submission detail page:
![image](https://user-images.githubusercontent.com/6338661/52417713-65c79700-2ae4-11e9-808c-7041001d77ed.png)

**QA criteria**
Dev:

- [ ] checked feature meets acceptance criteria/conforms exactly to the specification.
- [ ] provided good unit test coverage (if this is non-trivial behaviour).
- [ ] checked all tests for the project pass with this feature enabled.
- [ ] checked code conforms to the project coding standards.
- [ ] had code reviewed by another developer and resolved any issues raised.
- [ ] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [ ] checked that this feature works on the server/s I am deploying it to.

QA:

 * [ ] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [ ] checked that the feature works on the server/s deployed to

**Comment by gibbsmaya** [comment]
@tm-kn this is unblocked for you now.

**Comment by chris-lawton** [comment]
Branch - https://github.com/OpenTechFund/opentech.fund/tree/feature/1016-detail-view-review-information

Just requires the api to grab the icon and replace the placeholder that is currently being used.

**Comment by todd-dembrey** [comment]
@gibbsmaya this is now on dev for testing.

**Comment by gibbsmaya** [comment]
Issue when moving between submissions - page is blank and not loading anything.

**Comment by todd-dembrey** [comment]
@gibbsmaya It looked like if the data was a little slow to load then it errors. I have added in the loading panel for the reviews while they are being fetched

**Comment by gibbsmaya** [comment]
@todd-dembrey this looks much better thanks. A couple of small points below:

Example: https://dev-apply.opentech.fund/apply/rounds/732/?submission=5

- [ ] Role icon missing
- [ ] Score needs to be cut off to a more sensible number of decimal points

**Comment by todd-dembrey** [comment]
@gibbsmaya as discussed I have added a hide show for the external reviewers who have not submitted reviews. I have also fixed the above two comments w.r.t score and icon.

**Comment by gibbsmaya** [comment]
Thanks @todd-dembrey . I can't test the hide/show due to the data on dev but we can test this once it is deployed. Please deploy to test.

**Comment by todd-dembrey** [comment]
This is now on test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

I am adding in the testing notes here. @todd-dembrey is yet to deploy this to live, but as soon as he does (very soon!) he will update this to confirm. For when he does - here are the testing notes:

This work is now ready for testing. This work is adding in the reviewer roles and review assignees to the status tab on the detail view pages. It refers to both the submission by round page e.g. https://test-apply.opentech.fund/apply/rounds/732/?submission=11 and the submission by status page e.g. https://test-apply.opentech.fund/apply/submissions/internal-review/?submission=10

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by todd-dembrey** [comment]
This is now on test

**Comment by fourthletter** [comment]
All acceptance criteria visible and functional. Thanks!

**Comment by gibbsmaya** [comment]
Ready for live deployment.
