### ISSUE TITLE
When I add a file to be uploaded, nothing visible happens or confirms that files will be uploaded when I hit submit

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1050]
I can confirm that file uploads are working, but there's nothing that indicates to the applicant that they've added a file to be uploaded or even a number that says they've added files. It also seems like when if you hit the button, it resets the file settings, requiring one to re-add any previous files.

- [x] Show the number of files that will be submitted
- [x] Show the filenames of the files that are to be submitted
- [ ] Allow the applicant to clear all files
- [ ] Allow the applicant to remove a specific file
- [ ] Allow the applicant to add one or more files
- [ ] Show which file types are allowed to be submitted

**Comment by frjo** [comment]
The PR https://github.com/OpenTechFund/opentech.fund/pull/1093 fixes some of the issue, please test and review on https://test-apply.opentech.fund/.

**Comment by danblah** [comment]
Tested... shows multiple files as desired. Clicking upload after previously adding files, before submitting, removes all the previously selected files. submitting cause an [error](https://sentry.io/organizations/otf/issues/928814612/?project=1275696&referrer=alert_email).

**Comment by frjo** [comment]
That behaviour is as it has always been. The is that this pr add only list the files, nothing else. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
