### ISSUE TITLE
Add reviewer in webapp is getting an error message

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1061]
Add reviewer in webapp is getting an error message. Fig 1 is the add reviewer button and Fig 2 is the error message:

Fig 1
![image](https://user-images.githubusercontent.com/20019656/53391560-03511080-3997-11e9-8d54-5697e4516fad.png)

Fig 2
![image](https://user-images.githubusercontent.com/20019656/53391507-d6046280-3996-11e9-9864-ac8e19e422d5.png)

**Comment by todd-dembrey** [comment]
@fourthletter Is this within the test app? Because this is a known to be an issue until we finish some work towards the end of this week.

https://sentry.io/organizations/otf/issues/908172517/?project=1275696&query=is%3Aunresolved&statsPeriod=14d&utc=false

**Comment by todd-dembrey** [comment]
#1072 Should fix the issues on the live site.

**Comment by danblah** [comment]
@fourthletter, is this issue resolved? If so, go ahead and close it.
