### ISSUE TITLE
CFP: New workflow – Request with community review

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1063]
States:

* Screening
* More information required
* Open Call (public) (New: will make the submission display on a public page with a "Build it" button)
* Community review (New: Will allow users with the role "Community reviewer" to review submissions.)
* Internal Review
* Ready For Discussion
* More information required
* Advisory Council Review
* Ready For Discussion
* More information required
* Ready for Determination
* Accepted
* Dismissed

**Comment by tarakiyee** [comment]
Instead of public review, let's call that state "open call"
