### ISSUE TITLE
CFP: Make it possible to group forms

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1064]
Make it possible to group forms and set them as collapsed by default. A trigger field can make them uncollapsed.

This could be done by adding a feature to group fields in application forms or by having multiple application forms for a fund with the new "Request with community review" workflow being stitched together.

**Comment by frjo** [comment]
@Parbhat Do you think you can take this on?

**Comment by Parbhat** [comment]
@frjo Can you please add some more information to the issue? Got the requirements slightly but it would be good to have more info.

**Comment by frjo** [comment]
@Parbhat  OTF is starting a new fund called "Community Prototype Fund", CPF. This fund will collect project ideas that OTF should fund.

People who send in submission will fall in two distinct groups.

1. People who suggest project ideas that they think someone should do.
2. People who suggest project ideas that they themselves want to do.

The first kind will only need to fill in a subset of fields while the second group need to fill in the whole form.

My plan was to have all the fields present in the form but have one "toggle" field with radio options like:

* I want to implement it!
* Help me find someone to implement it!

If the user pick "I want to implement it!" the additional fields are revealed/unhidden (remove a "hidden" css class with some JavaScript).

In Drupal I would have done this with the Field group module https://www.drupal.org/project/field_group. But with Django/Wagtail I'm unsure if that is the best approach. Another option would be to add two (or more) separate application forms to the fund and concat them together in separate groups on the same application form.

There needs some way for admins to pick the trigger field that should revel the rest of the form. 

Add an option to the checkboxes stream field or create a new custom version of the checkboxes stream field? If it's possible it would be really neat to have the option to add any number of groups with one trigger field for each group.

**Comment by Parbhat** [comment]
@frjo Thanks for the information. Created a draft PR #1123
