### ISSUE TITLE
Creating a copy of a round results in 500 error

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1068]
Expected behavior, hit copy of a round, input all the needed details to make a copy

Instead, get 500 [error](https://sentry.io/organizations/otf/issues/887293023/?project=1268368&query=is%3Aunresolved&statsPeriod=14d&utc=false).

The reason is the copy function doesn't give the user the option to change the dates, thus error for overlapping round dates.

**Comment by todd-dembrey** [comment]
This is the same as #1018

**Comment by frjo** [comment]
Closing as duplicate.
