### ISSUE TITLE
Adding new round for IFF shows the wrong workflow, request rather than Concept & Proposal 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1069]
Add round
Choose [Fund] Internet Freedom Fund
See Workflow, says request rather than Concept & Proposal

**Comment by frjo** [comment]
After saving the round the workflow is correct from what I can see. So the problem is that while creating a round the wrong workflow is displayed witch is confusing even if it gets correct in the end.

**Comment by arduina** [comment]
Thanks, it worked for the May round.

**Comment by fourthletter** [comment]
We tested and it's functional. Thanks!

**Comment by danblah** [comment]
Closing this, seems responsed.
