### ISSUE TITLE
Investigate memory usage, often close to the max 512 MB

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1081]
Can we get Django to use less or do we need to upgrade to 2x dynos that has 1 GB memory.

**Comment by todd-dembrey** [comment]
You can use the scout reporting to help identify some areas for improvements.

https://scoutapp.com/apps/28725?section=memory&p=memory&s=response_time&insights=more

**Comment by Parbhat** [comment]
@todd-dembrey @frjo Can I get access to scout app OTF project to review possible performance issues?

**Comment by frjo** [comment]
@Parbhat Invite sent.

I have upgraded to 2x dynos on Heroku for the moment to avoid problems. Would be nice if we could revert back to 1x.

**Comment by Parbhat** [comment]
@frjo Thanks, got access.

**Comment by Parbhat** [comment]
@frjo One of the reasons for the recent increase in database queries and increased response time is changes made in [table.html ](https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/funds/templates/funds/tables/table.html). The changes made in the template increased the number of DB queries significantly. As this template is used for many views to create a table it reduces the overall performance. Given it a quick shot to reduce the effects but it will take more time. Also, are we moving some pages containing tables like `/apply/submissions/all/` to React frontend? If yes, we check the performance again after the migration is made.

**Comment by frjo** [comment]
@Parbhat There is only a very specific use of react and it's for OTF staff only. Do not think that will be expanded much.

**Comment by frjo** [comment]
This is no longer an issue after performance improvements in other issues.
