### ISSUE TITLE
Add a Partners section to funds/labs that allows a manager to select users in the group Partner to associate with that fund/lab

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1084]
Should work just like the Reviewers section
On a submission from that lab/fund, when adding partners, only show the selected partners.
If there are no selected partners, hide the partner button on the submission page.

**Comment by saoun** [comment]
not 100% what this means @frjo. sounds like something that is already implemented or am i missing something?

**Comment by frjo** [comment]
You can pick a number of reviewers on a fund or lab and they will get automatically assigned to all submissions that are sent in for that fund or lab.

This is the same functionality for partners. As it is now you need to manually add partners to individual submissions.

I do not think adding partners is that common but staff will know this.

**Comment by saoun** [comment]
I see. The only time staff add partners, it is usually per submission, and they would want to select them manually because it shouldn't always be the same. I will close this for now, and we can reopen in case it becomes relevant again.
