### ISSUE TITLE
Notify the Partner and Applicant when a new Partner has been added to an application 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1085]
For applicants, send the name of added partners to the applicant
For partners, say they've been added a partner for an application with the name of the submission with and link

**Comment by danblah** [comment]
Working but for some reason its doing it twice... see: https://test-apply.opentech.fund/django-admin/activity/event/?submission__id=10

**Comment by frjo** [comment]
I think your are seeing "Partners Updated" and then "Partners Updated Partner". One is for altering the applicant and the other the partners. Not the best names I know.
