### ISSUE TITLE
Automatically change a proposal's status from "Advisory Council Review" to "Ready for discussion" after it's received 2 reviews

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1096]

**Comment by fourthletter** [comment]
This automation makes sense and would be helpful.

**Comment by frjo** [comment]
Ready to test on test.

**Comment by fourthletter** [comment]
Status automatically changed when Advisory Council Review" to "Ready for discussion" after it's received **ONE** review. Thanks!

**Comment by frjo** [comment]
@fourthletter That submission has two reviews. But the status changed after only one review?

If that is the case it's a bug since it should be after two reviews.

**Comment by fourthletter** [comment]
Status automatically changed when Advisory Council Review" to "Ready for discussion" after it's received two reviews. Thanks!
