### ISSUE TITLE
Four reviews formatted to fit into one screen

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1098]
All four reviews (2 internal + 2 AC) could not be viewed at the same time side-by-side. 

Scrolling left to right in order to view the last review easily forces the screen to the previous page. Seeing all four reviews side-by-side on one screen is helpful when we write determination letters. Thanks.

**Comment by fourthletter** [comment]
Team members will need to reduce the view of their screen to less than 100% to fit all four reviews.

**Comment by frjo** [comment]
@fourthletter This we can fix with some CSS, no need to close it. 

It's designed for up to 3 reviews but not hard to make more flexible.
