### ISSUE TITLE
Only allow specified file types in file uploads on submissions

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1099]

**Comment by frjo** [comment]
@danblah The image field seems to only allow image files but the file and multiple files fields on submissions accepts anything from what I can see.

What extensions should be accepted? How about this list?

* doc
* docx
* odp
* ods
* odt
* pdf
* ppt
* pptx
* rtf
* txt
* xls
* xlsx

**Comment by frjo** [comment]
I would like a setting in base.py where the allowed extensions can be listed with some sensible default (pdf, rtf, txt). Similar to BLEACH_ALLOWED_TAGS.

Django/wagtail then use this list to validate file uploads server side.

Would be really neat to also implement HTML5 accept attribute so the user gets quick feedback.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept

Each instance of an upload field should list the allowed file types as well.

**Comment by danblah** [comment]
The list you posted above @frjo is good! cc @Parbhat

**Comment by Parbhat** [comment]
PR #1113
