### ISSUE TITLE
Can't scroll after opening a dialogue on a submission.

### ISSUE THREAD

**Issue by arduina** [OpenTechFund/opentech.fund#1101]
I can't reproduce this bug for every application. But it is happening on different devices. Reloading "fixes" it.

**Comment by frjo** [comment]
See 
https://github.com/OpenTechFund/opentech.fund/issues/1102

**Comment by danblah** [comment]
This is still happening, even after adding reviewers and the icons are in place. See: https://apply.opentech.fund/apply/submissions/3865/
