### ISSUE TITLE
The detailed view can't be sorted or filtered by status. In other words, all submissions within a particular status like "internal review" does not appear in the detailed view.

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1104]
The detailed view can't be sorted or filtered by status. In other words, all submissions within a particular status like "internal review" does not appear in the detailed view.

**Comment by frjo** [comment]
@fourthletter  I need a url so I know what view it is.

**Comment by fourthletter** [comment]
This tech issue was resolved. Thanks, Di
