### ISSUE TITLE
Update list of allowed tags

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1105]
See https://apply.opentech.fund/apply/submissions/3677/#communications. Horizontal line and quoting are not showing up.

**Comment by frjo** [comment]
The "bleach" filter is what sanitise all output from users so this is a global setting.

What tags should be allowed? The current list looks like this.

```
BLEACH_ALLOWED_TAGS = ['h2', 'h3', 'p', 'b', 'i', 'em', 'strong', 'a', 'ul', 'ol', 'li', 'br', 'span']
```

Your example above indicate that 'blockquote' and 'hr' should be allowed as well. Any more?

In the old Drupal site we allowed these tags:

´´´
<a> <b> <big> <blockquote> <br> <cite> <code> <dd> <del> <dl> <dt> <em> <h1> <h2> <h3> <h4> <h5> <h6> <i> <ins> <li> <ol> <p> <pre> <small> <strong> <sub> <sup> <ul>
´´´

My suggestion is:

```
BLEACH_ALLOWED_TAGS = ['a', 'b', 'big', 'blockquote', 'br', 'cite', 'code', 'dd', 'del', 'dl', 'dt', 'em', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'i', 'ins', 'li', 'ol', 'p', 'pre', 'small', 'span', 'strong', 'sub', 'sup', 'ul', ]
```

**Comment by danblah** [comment]
Let's start with those and go from there. Thanks!
