### ISSUE TITLE
Message "The contents of this application have been changed by someone else" constantly appears in the detailed view of a submission

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1108]
The message (image below) appears constantly within the detailed view. Here is an example link to the detailed view: https://apply.opentech.fund/apply/rounds/796/?submission=3690

This message (image below) has been permanently visible in different submissions for several team members. Either 1) this message is correct and should appear or 2) this is a bug.

![image](https://user-images.githubusercontent.com/20019656/54297836-000c7600-458e-11e9-866e-a25a9fca53e4.png)

Thanks, Di

**Comment by frjo** [comment]
This is in the react app, the message comes from this code:

https://github.com/OpenTechFund/opentech.fund/blob/a281060d595cc5e20c445a214689008814aef504/opentech/static_src/src/app/src/containers/CurrentSubmissionDisplay.js#L56-L61

**Comment by frjo** [comment]
@fourthletter Is this still an issue?

**Comment by fourthletter** [comment]
Yes, this is still an issue.

**Comment by chris-lawton** [comment]
The message is correct in appearing but what's triggering it is the authentication token on images hosted with s3. The token is being updated every time a request is being made to the backend, hence the change in the diff and the message appearing. Having a static, shareable image links will resolve this.

Relevant issue: https://github.com/OpenTechFund/opentech.fund/issues/1168

**Comment by fourthletter** [comment]
Test does not show message. Thanks! 🔥
