### ISSUE TITLE
The List View does not capture who signed up to write a review for an application.

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1109]
The List View does not capture who signed up to write a review or intends to write a review in the future. 

It is possible to know AFTER a review has been submitted, but this information is not available BEFORE a review has been submitted. It is also possible to see names of reviewers within the submission and in the detailed view, but it's not possible in the List View. 

- Managers need a quick view to know which applications need additional reviewers in order to assign multiple reviewers as a batch action. 
- Individuals need a quick view to know which applications need primary or secondary reviewers in order to select multiple applications as a batch action.

**Comment by frjo** [comment]
@fourthletter Is there a function where reviewers can sign up to review a specific submission? I do not know about it, or maybe you want such a feature added?

In the list view (I assume you mean https://apply.opentech.fund/apply/submissions/all/) it would be hard to fit a long list of reviewers like the one on submission detail view.

It would definitely need to be in the fold out section for each submission, but still hard to fit. Any ideas how it should look/work?

**Comment by arduina** [comment]
This is causing some problems and confusion in the current ICFP and March 1 round. It would be great if this could be resolved as soon as possible, therefore I am adding a priority label.

**Comment by arduina** [comment]
@frjo in the fold out section would be fine. It would be great if you could see right away if there are not only review outcomes but reviewers assigned. In this view you also assign yourself by clicking the box left of the application and using the function above. 
Right now you can't see if this project already has sufficient reviewers, so if you assign yourself, others are simply removed. 

<img width="1225" alt="Bildschirmfoto 2019-03-13 um 17 44 01" src="https://user-images.githubusercontent.com/6928861/54316827-01529880-45b8-11e9-9639-ba2f1bfd2ed2.png">

**Comment by frjo** [comment]
The batch add reviewers function on 
https://apply.opentech.fund/apply/submissions/all/ is only for staff, reviewers can not access this view at all.

Are OTF staff using this to assign themselves to submissions? I thought this was the job of the lead?

If this is the way you use this feature, would it be ok to only show staff reviewers in the fold out section? And not all reviewers (that can be a long list indeed)?

**Comment by fourthletter** [comment]
@frjo We are using the batch action to assign reviewers in the list view through the round or fund: https://apply.opentech.fund/apply/rounds/794/

The lead and other staff members are unable to see in this view which individuals have been assigned primary or secondary reviewers because this information is not visible: https://apply.opentech.fund/apply/rounds/794/ 

The lead and other staff members are able to see who has signed up as primary or secondary when they go to the submission directly. This defeats the purpose of assigning individuals as a batch action.

**Comment by fourthletter** [comment]
@frjo I am attaching the features discussed during testing and development phase: https://github.com/OpenTechFund/opentech.fund/issues/1016

**Comment by frjo** [comment]
This is now on test ready for your testing. http://test-apply.opentech.fund/apply/submissions/

I made the "Review outcome" list staff reviewers even if they have not submitted an review so they are always visible, the outcome is then set to "—". See screendump for example as well.

Does this seem like an acceptable solution?

![staff_reviewers_list](https://user-images.githubusercontent.com/191392/54530024-e306e700-4981-11e9-90fc-e1f16241e1f7.jpg)

**Comment by frjo** [comment]
@arduina Removed screen dumps since these issues are public and submission information should not be public (deleted revisions om the comments as well).

**Comment by arduina** [comment]
Oh gosh, you're right. Thank you.
