### ISSUE TITLE
Review Outcomes are not visible in one submission

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1111]
Review Outcomes are not visible in this submission https://apply.opentech.fund/apply/submissions/3753/

I am creating a ticket for this issue because this might be a bug and impact other submissions.

**Comment by frjo** [comment]
@fourthletter The review has no outcome so nothing to show. You have forgotten to add a score field to the review form. Without a score there is no outcome for the system to calculate.

**Comment by fourthletter** [comment]
@frjo Individuals are adding themselves as primary or secondary reviewers. This is visible on the submission page. Example: https://apply.opentech.fund/apply/submissions/3752/

This information is not visible on the List View: https://apply.opentech.fund/apply/rounds/794/
