### ISSUE TITLE
Increase size of note-taking section in detailed view 

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1114]
This an enhancement and UX issue for increasing the space where notes are inputted and submitted. 

The current space is small relative to the space above it. Increasing the size would give the note-taker better visibility to read what has been written. The length of written content submitted to the system is often one paragraph or longer.

**Comment by frjo** [comment]
@fourthletter At the moment the note section is set to take 25% of the column hight. How much space would you like it to take?

**Comment by fourthletter** [comment]
Here are the current proportions with already saved notes. The space size for drafting text is smaller when there are previously saved notes.

![Screenshot 2019-03-26 at 11 34 03 AM](https://user-images.githubusercontent.com/20019656/55640792-9bc78580-57cc-11e9-8db6-1e27f4eae28e.png)

**Comment by frjo** [comment]
Each time the note section reloads (every 30000ms) in the react app the add note form part shrinks. It should be 25vh, and it is initially. Changing the css only have an effect initially, after reload it to small again.

**Comment by frjo** [comment]
@fourthletter I believe this has been fixed in the recent work with editing comments from Torchbox. Please reopen if it persist.
