### ISSUE TITLE
Paste function in mobile app

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1116]
Individuals are unable to paste content to a determination letter in the mobile webapp. 

There is a "copy" function, but a "paste" function is not available. This means information from elsewhere in the submission cannot be duplicated using shortcuts when someone is drafting a determination letter in the mobile webapp.

**Comment by frjo** [comment]
Some screenshots would help me understand the problem. 

I tested to copy and paste in the determination form on my iPhone and it seemed to work as it should. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo it's not working on android phones. :(

**Comment by frjo** [comment]
@fourthletter And it’s the standard Android copy and paste function you are trying to use? And it’s working in other web forms?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
Two people using android phones have this issue.

**Comment by frjo** [comment]
I would like to know two things.

* Can these users copy and paste in other web forms without issue?
* Do they have problem with copy and paste on only some OTF WebApp forms or on all of them?

**Comment by fourthletter** [comment]
Question 1. Users can copy and paste in other web forms without issue.
Question 2. Users can copy, but are NOT able to paste on OTF WebApp forms.

**Comment by frjo** [comment]
Can it be that it's a problem in rich text fields (with a wysiwyg editor) but works in plain text fields?

**Comment by fourthletter** [comment]
The PASTE function appears when I click on "Insert link" but not when I'm in a text box.

**Comment by danblah** [comment]
I just tried testing this in the admin interface and applying. not able to reproduce. can we get specific pages in the app you're seeing this @fourthletter and a confirmation that you're seeing this on your mobile's chrome browser?

**Comment by fourthletter** [comment]
The specific page I want to paste into is for determination messages. It is possible to copy from anywhere, but not possible to paste in the text box used to draft determination messages via an android.

**Comment by danblah** [comment]
That's great. Just confirmed this. 

@frjo, to reproduce
1. go to https://apply.opentech.fund/apply/submissions/3851/
2. Select Add determination
3. Copy any text on that screen
4. Touch the first text box
5. Press/hold to select paste

Expected behavior, that the Android context box pops up that allows for pasting. What happens instead is that some wysiwyg editor box pops up a box for options Formats, Link, and Image options.

Seems there's some overriding thing in the wysiwyg editor code. The workaround for this (until this bug is sorted) is to install another keyboard/input method (I'm using CodeBoards) and then actually hit ctrl+v.

**Comment by frjo** [comment]
@danblah It seems to be the TinyMCE context menu that makes life hard for Android copy and paste function. I have created an PR that disabled the contextmenu plugin. Hopefully that will fix the issue and no one was most likely using the context menu anyway.

**Comment by danblah** [comment]
Tested, now no menu comes up when the field is blank. If i punch in some text first, highlight that (or go to its tail), I now get the option to copy/paste/etc (android menu). If there's no easy/quick way to get the menu to come up in a blank field, I'd say this is good.
