### ISSUE TITLE
Send need information determination during the Ready for Preliminary Determination status

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1121]
Staff needs to write and send determination letters asking applicants to provide additional information during the **Ready for Preliminary Determination** status.

Currently, staff could only send "accept" or "dismiss" letters in the Ready for Preliminary Determination status. This is not adequate.

**Comment by fourthletter** [comment]
@frjo Staff needs to send correspondence this week. Is it possible to have a short-term solution like move applications to a different status that allows "need more info" determinations OR allow admins to make this change on their own? 

Example: Move applications from **Ready for Preliminary Determination** to **Ready for Discussion** status. Ready for Preliminary Determination status restricts external communication to either "accept" or "dismiss." 

Allowing admins to draft "need more info" determinations in any status would provide the most flexibility and least restrictive work flow. However, this change might not be arduous to complete this week.

**Comment by frjo** [comment]
Ready to be tested on http://test-apply.opentech.fund/apply/submissions/

**Comment by fourthletter** [comment]
Testing went great -- thank you! http://test-apply.opentech.fund/apply/submissions/
