### ISSUE TITLE
The "show all" function does not display all submissions that have been assigned to an individual

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1124]
The "show all" function does not display all submissions that have been assigned to an individual. The "show all" button in the Waiting for Your Review dashboard is currently jumping to All Submissions. 

Individuals should be able to view a list of submissions that have been assigned to them by clicking on the "show all" function. The Waiting for Your Review dashboard defaults to showing 5 submissions, clicking on the "show all" button should display all of the submissions assigned to someone.

Example: Individuals with 20 assigned submissions to review should be able to see these 20 submissions in their Waiting for Your Review dashboard when they click on "show all." 

Image of Waiting for Your Review dashboard:
![image](https://user-images.githubusercontent.com/20019656/54554946-0fbffc00-498c-11e9-85ca-b63edb36ecfb.png)

**Comment by frjo** [comment]
@fourthletter  It looks like this is how it works already. I assigned a bunch of submissions to myself and the "Show all" link on the dashboard then goes to `
/apply/submissions/all/?reviewers=1&status=screening&status=more-information-required&status=internal-review&status=ready-for-discussion&status=ready-for-determination&status=advisory-council-review&status=ready-for-preliminary-determination&status=invited-for-proposal&status=proposal-received&status=ready-for-final-determination`

The `reviewers=1` query makes the view filter on submissions that my account is assigned to review (my account is nr 1).

Does this not work for you? Can you paste in the link you get?

**Comment by fourthletter** [comment]
The ‘Show all‘ links should jump to the relevant listing page for the summary type. 

Currently the ‘Show all‘ button jumps to _all submissions_ even though the linked listing page should apply the same queryset filters as on the current summary table. 

The queryset filter in this case should be all assigned submissions waiting for your review

**Comment by frjo** [comment]
@fourthletter But as I wrote above, when I click that link I do get a list of all submissions I'm assigned to review.

Can you paste in the link you get that does not do what you want?

**Comment by fourthletter** [comment]
This has been fixed. Thank you.
