### ISSUE TITLE
Notify Second Reviewer when First Review is finished [High/Improvement] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1125]
-=Sensitive=-
No

-=Reporter=-
Tara

-=Ideal deadline=-

-=Who's affected=-
OTF team

-=Description=-
On slack, the notification of a review only notifies the round lead of the review. It should also tag the second reviewer on the CN/Proposal.

-=Objective=-
Second reviewers are notified when they are able to put in their review. 

-=Additiional info=-
no, thanks!

-=Timestamp=-
2019-03-21T01:42:00.852Z

**Comment by fourthletter** [comment]
@frjo this feature is no longer available.
