### ISSUE TITLE
Updates to notes behaviour in detail view

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1128]
These elements have not been implemented during Winter Sprint:

[ ] Notes will be editable by the author 
[ ] Unsubmitted notes will persist between switching submission (if you remain on the page). E.g. if you accidentally change submission, the note will not be lost and will be visible when you re-select the submission
[ ] There will be notification about unsent notifications if you navigate away from the page.

relates to #945

**Comment by todd-dembrey** [comment]
* Does the editing need to  only to work in the react app or is this also meant to also work on the the normal django pages?

We will need to talk internally about how we represent unsent messages.

**Comment by danblah** [comment]
Priority is the normal app, not the react app (that's a would be nice along with unsent msgs). #945 is the base requirement. Please make tickets for whatever else can't be done beyond that in this sprint.

**Comment by frjo** [comment]
@fourthletter Has these issue not been fixed by now?

**Comment by fourthletter** [comment]
@frjo This issue has been fixed. Thanks!
