### ISSUE TITLE
batch action determination jumps to a different page

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1130]
After completing a batch action determination within a specific round, the page jumps to all submissions and the queryset filter no longer applies. 

After completing a batch action determination with a specific round, the page should stay within the round.

**Comment by gibbsmaya** [comment]
**Acceptance criteria**

- [ ] Following batch submission, user returned to listing page they originated from including any applied filters/searches.
- [ ] QA criteria satisfied

**Comment by abigail-hampson** [comment]
Looks good, this can be deployed to test

**Comment by fourthletter** [comment]
Features are functional during test. Thanks! 💥
