### ISSUE TITLE
Sort submission list in the react app by id just as the submission list view

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1142]
The view at /apply/submissions/all/ sort submission by submission id.

The react app at /apply/rounds/*/?* sort the submissions in the left column by latest activity.

We would like that to sort by submission id as well so the list is sorted the same in different views. Makes it easier to locate submissions.

**Comment by todd-dembrey** [comment]
@frjo if the issue is finding things in the list would we be better places to provide some means of search?

**Comment by frjo** [comment]
Search would be good as well but they really want the lists to be ordered the same way. Seems to be important for their workflow. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gibbsmaya** [comment]
Chris to check both instances of the listings and confirm the sort order on both (list view e.g. https://test-apply.opentech.fund/apply/rounds/732/ and the sort order within a grouping on the detail view e.g. ordering within 'Accepted' status on https://test-apply.opentech.fund/apply/rounds/732/?submission=17).

Following this we will confirm with @fourthletter what the correct sort order should be and adjust one of the lists.

**Comment by chris-lawton** [comment]
Hi @fourthletter 

Following on from Maya's comment above I can confirm the:

- list view default ordering is by last updated
- grouping on the detail view has no default ordering applied

Would you like the grouping on the detail view to be ordered by last updated or do you have another preference?

**Comment by fourthletter** [comment]
@chris-lawton "grouping on the detail view to be ordered by last updated" would be great. Thanks!

The use case is Person A uses the **list view** to facilitate a meeting and lead the discussion while Person B uses the **detail view** for note-taking. We do not need these views to be mirror images or exact replicas, but it difficult for Person B to write notes about what Person A is discussing when the order is completely different. Confusion occurs when several applications are being discussed.

**Comment by chris-lawton** [comment]
Ready for internal testing on dev.
Example:
Ordering of items here (by last updated) - https://dev-apply.opentech.fund/apply/rounds/732/?status=dismissed&query= should now be reflected in the 'dismissed' column here https://dev-apply.opentech.fund/apply/rounds/732/?submission=3

**Comment by abigail-hampson** [comment]
Looks good, this can be deployed to test

**Comment by fourthletter** [comment]
Features are functional during test. Thanks! 💥
