### ISSUE TITLE
Custom dashboard and submission detail views for reviewers, partners and community reviewers

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1147]
### Dashboard

New custom dashboards for Partners and Community reviewers. Additions to reviewers dashboard.

**Reviewers:**

* Mainly write reviews and that part of the dashboard works well.
* They also can send in their own submissions and if they do a new section should display on their dashboard similar to what applicants see.

**Partners:**

* Should see the submission they have been added to as partners. They can both review and edit these submissions.
* Should see any reviews they write just like reviewers.
* Should see their own submissions if they send in any.

**Community reviewers:**

* Mainly write their own submissions as applicants.
* Should also see a list of any submissions that are in a COMMUNITY_REVIEW_PHASES state. These they can review.
* Should see any reviews they write just like reviewers.

### Submission detail view

New custom submission detail views for Partners and Community reviewers.

**Partners:**

* Everything like applicants
* See their own reviews and reviews set to be public.

**Community reviewers:**

* Everything like applicants
* See their own reviews and reviews set to be open to all reviewers.

**Comment by Parbhat** [comment]
In Submission detail view for partners and Community reviewers:

> See their own reviews and reviews set to be public.

Are there any public reviews? From the [current](https://github.com/OpenTechFund/opentech.fund/blob/fcfd52be4e394eab781d20ca08bd22eedf545885/opentech/apply/review/options.py#L41) state, it does not seem we have any public review.

**Comment by frjo** [comment]
Bad wording by me. Have updated the text now.

There is a new "visibility" field that can be added to review forms, by default set to "private". It can also be set to "reviewers".

* Private: Only visible to the review author and to staff. (This is how it has worked earlier.)
* Reviewers: Visible to all reviewers and to staff.
