### ISSUE TITLE
Ensure that reviewers are ordered consistently between different views

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#1152]
@todd-dembrey Could making sure the list of reviewers being sorted in the same manner in all places be part of this as well?

_Originally posted by @frjo in https://github.com/OpenTechFund/opentech.fund/issues/985#issuecomment-474865793_

**Comment by fourthletter** [comment]
This [test application](https://apply.opentech.fund/apply/submissions/3912/) in the live webapp shows sequence of reviewers in three different orders:

A) List View: https://apply.opentech.fund/apply/rounds/823/
![image](https://user-images.githubusercontent.com/20019656/56915212-3b1f2600-6ab6-11e9-8df5-6bae925a91ce.png)

B) Submission View: https://apply.opentech.fund/apply/submissions/3912/
![image](https://user-images.githubusercontent.com/20019656/56915348-905b3780-6ab6-11e9-9c2e-551ed2b08d0b.png)

C) Detailed view: https://apply.opentech.fund/apply/rounds/823/?submission=3912
![image](https://user-images.githubusercontent.com/20019656/56915395-aff26000-6ab6-11e9-9731-155fe87392f8.png)

**Comment by gibbsmaya** [comment]
Correct reviewer ordering is:

<role reviews submitted ordered by role order>
<staff reviews submitted>
<role not reviewed ordered by role order>
<staff not reviewed>
---
<external reviews>
<external not reviewed>

(Submission View currently correct)

**Acceptance criteria**

 - [ ] List View (e.g.https://apply.opentech.fund/apply/rounds/823/) ordered as per correct sort order
 - [ ] Submission View (e.g. https://apply.opentech.fund/apply/submissions/3912/) ordered as per correct sort order
 - [ ] Detailed view (e.g. https://apply.opentech.fund/apply/rounds/823/?submission=3912) ordered as per correct sort order

**Comment by abigail-hampson** [comment]
This is now ready for you to review. In the detail view the order of the external reviewers differs slightly to on the submission view. They are however grouped and listed in the correct order identified above. Let me know if you're happy with all of this.

**Comment by fourthletter** [comment]
All acceptance criteria are functional and visible. Thanks!

**Comment by gibbsmaya** [comment]
@frjo this is ready to be deployed to live. Can you include in your next deployment please?
