### ISSUE TITLE
Applicant will be directed to NEW questions in IFF and CIF concept note

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1163]
- Account name or name of person: Di
- Title of submission (app URLs alone are OK): Add two text boxes for new concept note questions IFF and CIF

**Is your feature request related to a problem? Please describe.**
Team wants to steer applicants to specific questions related to particular themes. Applicants working within research or digital security will be presented with a unique set of questions that goes beyond compulsory questions.

**Is your feature request related to an existing functionality? Please describe.**
This is a new feature or preemptive step before an applicant is allowed to start an concept note.

**Describe the solution you'd like**
A new prompt or question box will appear when an applicant starts a new application. Selecting research or digital security will take an applicant to a unique set of questions. 

**Describe alternatives you've considered**
We are open to other alternatives that would increase usability. 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff
- Applicants
- Reviewers
- Partners

**Ideal deadline**
Mid-June

**Comment by frjo** [comment]
We recently added the possibility to group fields on application forms and have a toggle to show/hide each group. This sounds like a case for that.

**Comment by danblah** [comment]
Closing this as it's being covered with the field group functions.
