### ISSUE TITLE
Submissions are not automatically accessible to AC reviewers when in AC Review Status

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1165]
Submissions are not automatically accessible to AC members when it's in the AC Review Status. Team members have to manually select AC names in order to enable access, this action should occur automatically.

**Expected behavior**
AC reviewers should be able to access a submission and draft a review when it's ready for review. 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Reviewers

**Additional context**
Related to #1102

**Comment by frjo** [comment]
@fourthletter I have tested back and fourth and for me reviewers can view any submission regardless of state. When I read the code this is also how it's supposed to work.

**Comment by frjo** [comment]
@fourthletter Can we close this or is there still an issue?

**Comment by fourthletter** [comment]
@frjo This issue could be closed. 

We recently discovered the most recently created September round didn't carry over AC names from the last round. I want to ensure team members are aware of this in the future. Thanks!
