### ISSUE TITLE
Add application form in wagtail should retain information from previous application

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1167]
- Account name or name of person: Di

**Describe the bug**
The "add application form" or generating an application form for a new round should retain information from previous application. The questions are retained, but information within the help text do NOT.

**To Reproduce**
Click on "add application form"

**Expected behavior**
The "add application form" or generating an application form for a new round should retain information from previous application.

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
The help text box contains descriptions to the question in order to give applicants additional information and context regarding the question.

**Comment by frjo** [comment]
When you create a new round it will use the application form attached to the fund, not the one attached to the latest round.

I think this issue will be fixed if you edit the application form attached to the fund and add the help text there. Then it will be present in all the rounds moving forward.

**Comment by fourthletter** [comment]
There are several IFF and CIF options in the application form folder. Do you recommend the one I should use? https://test-apply.opentech.fund/admin/funds/applicationform/
