### ISSUE TITLE
Route all s3 private file requests via Django, checking access privs

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1168]
Currently the OTF WebApp generates download links for s3 private files with a token that is valid for 10 minuts. This does not work well. Many times it takes more than 10 minuts to read a submission so when the user gets to the bottom and tries to download the file the link is not valid anymore. It's also not possible to share the link since it times out in 10 minuts.

In Drupal we used the built in Private file storage. It route all file access via Drupal so the request can be checked for access privileges.

We need something similar for the OTF WebApp.

The goal is to have links to submission uploads (private files on s3) that checks that the currently logged in user has the right to view the submission. If yes server them the file, if not redirect to the login form.

* These links would never timeout.
* They would allow e.g. staff members to share links between them.

Related issues: #1108, #1166 and #637

**Comment by danblah** [comment]
Yes. See #637

**Comment by danblah** [comment]
can we get some testing instructions/criteria here?

**Comment by frjo** [comment]
* Test to submit a new submission with an uploaded file. Does it work?
* Can the newly uploaded file be downloaded from the submission detail view?
* Can the upload file link be shared to another staff user ,and still works after more than 10 minuts?
* Can an anon user, or a logged in user that is not allowed to see the submission itself, access the upload file link (they should not).

**Comment by danblah** [comment]
I think i've got this via https://github.com/OpenTechFund/opentech.fund/issues/637#issuecomment-495609678

**Comment by danblah** [comment]
Noting that this is additional features (not holding up this ticket)...

Whats missing is that if someone shares the s3 url+access key before timeout, an unauthenticated user can view files. Two open questions I'd like to see tickets to resolve are:

* How can we make sure access to the url alone doesn't allow access to the files? Does s3's referer url bucket policy address this (ie, if the user isn't coming for our website, no allowed: https://www.botreetechnologies.com/blog/django-private-content-streaming-using-amazon-s3). What other other things are right here to try?

* Can we remove the redirect to the s3 domain, and keep users on our domain the whole time?

**Comment by Parbhat** [comment]
It will be better to stream the response to the admin user instead of a redirect (Option 2).

**Comment by Parbhat** [comment]
PR #1242 to serve private media from OTF domain instead of S3 redirect.

**Comment by danblah** [comment]
Noting that https://github.com/OpenTechFund/opentech.fund/issues/1241 resolves the first concern for me. I'm not sure how to test this for second option. Does the needs tests label need to be removed here?

**Comment by Parbhat** [comment]
The second option is deployed  on `dev-apply` site (Example [submission](https://dev-apply.opentech.fund/apply/submissions/24/)).

**Comment by frjo** [comment]
This is ready for test on test. Private media are now served directly instead of a S3 redirect.

**Comment by Parbhat** [comment]
The redirect after login is not working only on Test environment seems due to Cloudflare login. It will work on a live site, and currently working on `dev-apply` environment.

**Comment by Parbhat** [comment]
@frjo Looks like we can close this issue.
