### ISSUE TITLE
We need to choose one WYSIWYG and remove the other, discuss! 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1170]
@frjo, @todd-dembrey, @fourthletter @Parbhat 

What are the pros/cons. One uses markdown the other HTML. One allows pasting in rich text (the html one), the other doesn't. Others? I really want us to come to a conclusion, noting that neither are prefect.

**Comment by frjo** [comment]
My option would be to keep the wysiwyg editor as is for the public pages and use markdown for everything else.

There already exist a markdown textfield for applications forms, ready to use. Same implementation is also used for submission comments today. The editor in use is ok but not perfect. I would like to find a better one but that can be done without it effecting the content in any way, just makes it nicer for the users.

The third place is the nodes editor in the react app. Hopefully it would not be too hard to switch that out for markdown.

**Comment by Parbhat** [comment]
I am new to the rich text editors discussions/choices used in this project. Looks like we use TinyMCE for the apply site and pagedown (markdown editor by StackOverflow) mostly in public site and apply site's [MarkdownTextFieldBlock](https://github.com/OpenTechFund/opentech.fund/blob/322c41732872b9dc1e208273ff970fdcdb8066de/opentech/apply/utils/blocks.py#L47).

Pagedown is [used](https://github.com/OpenTechFund/opentech.fund/search?q=from+pagedown.widgets+import+PagedownWidget&unscoped_q=from+pagedown.widgets+import+PagedownWidget) mostly in the introduction field of Wagtail admin pages. The new rich text editor [Draftail](https://www.draftail.org/) came in Wagtail 2.0 support markdown and new [features](https://docs.wagtail.io/en/v2.5/releases/2.5.html#new-markdown-shortcuts-in-rich-text) are being added to it. It seems better to streamline it across the wagtail admin. But will require extra work in migrating content from pagedown markdown to HTML compatible with Wagtail's rich text editor.

**Comment by frjo** [comment]
Since Draftmail is built in to Wagtail it would be good to replace TineMCE with it. It should most likely be used for the introduction fields as well, I added markdown to get formatting working quickly.

There is also a React editor for notes in the react app for staff rounds administration, https://github.com/sstur/react-rte. Do not know how easy or important it's to replace that. (I would be happier if we could replace react completely with something simpler, this project is complex enough as it's.)

**Comment by saoun** [comment]
@danblah @frjo did you ever come to a consensus on this?

**Comment by frjo** [comment]
@saoun No consensus. I think we can leave it as is, there have not been any big issues around this that I know about.

**Comment by saoun** [comment]
great, so can we close this ticket then? if yes, please do!
