### ISSUE TITLE
Update the region scheme to the UN scheme and update all submissions accordingly

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1173]
I'm not sure the right order to do this in but we'd like new submissions to be labeled appropraely as soon as possible.

**_Here's the list we'd like to have:_**
Eastern Africa
Middle Africa
Northern Africa
Southern Africa
Western Africa

Western Asia
Central Asia
Eastern Asia
Southern Asia
South-eastern Asia

Northern Europe
Eastern Europe
Southern Europe
Western Europe

Caribbean
Central America
Northern America
South America

Oceania

**_Here's an order of operations as I see it:_**
Africa
* Rename North Africa and Middle East to Northern Africa
* Rename East Africa to Eastern Africa
* Rename West Africa to Western Africa
* Rename South Africa to Southern Africa
* Create Middle Africa

Asia
* Rename East Asia to Eastern Asia
* Rename South Asia to Southern Asia
* Rename South-East Asia to South-eastern Asia
* Create Western Asia

Europe
* Leave Eastern Europe
* Add Northern Europe
* Add Southern Europe
* Add Western Europe

Americas
* Leave Carribean
* Leave Central America
* Create South America
* Combine Southern Cone and Andean into 

Oceania
* Create Oceania

_**Modify all submissions appropriately according to https://unstats.un.org/unsd/methodology/m49/**_

**Comment by danblah** [comment]
We'd love see this done in Q2 but I'm trying not to add anything else there. @frjo, if things need to be moved around to make this happen, let us know.

**Comment by newbie15423** [comment]
We need to include all regions: "As we transition our application submission system to the new regional breakdown, we intend to ensure all regions globally can be selected to better understand the extent of applications focused on those previously unavailable." https://www.opentech.fund/results/visualizing-otf-application-data/

**Comment by newbie15423** [comment]
That means also adding: Northern America, Northern Europe, Western Europe, Australia and New Zealand, Melanesia, Micronesia, Polynesia

**Comment by newbie15423** [comment]
I think we should separate implementing this in the application forms than converting all previous submissions which is going to be a lengthier process. Right now this can only be done for IFF and CIF applications. For those, I need to add the node ID's back into the dataset so they are tied to the updated regions and then that will need to be used to map the changes. For the rest of the applications, they still need to be converted to the new regions. While most are straightforward, those that are not require manual inspection so not sure what the timeline looks like there

**Comment by danblah** [comment]
@frjo bumping this

**Comment by Parbhat** [comment]
@danblah @frjo Regions can be renamed/created from the Wagtail admin (`/admin/categories/category/`). in Region(s) category we have the `Options` section from which we create the Region field's choices in application forms like [IFF](https://apply.opentech.fund/internet-freedom-fund/). Renaming the value of the option is fine and changes will be reflected in old submissions as well.

 For example, renaming East Africa to Eastern Africa will display Eastern Africa both in old submission data and new application forms.

**Comment by frjo** [comment]
@fourthletter @danblah @saoun  If this works for you then you can do this update directly on live. No new functionality needed.

If this is the case please close this issue.

**Comment by fourthletter** [comment]
@newbie15423 @danblah next steps...

[✔ ] Regions can be renamed/created from the Wagtail admin 
[ ] Convert or assign submissions in Jan, March, May, July, Sept to new regions
[ ] Add regional category to IFF and CIF application forms in Wagtail admin

**Comment by danblah** [comment]
Ok, I've done all the renames and creation of new ones, as described above.

@frjo what about the ones we want to remove or integrate but not delete? This includes:

- North Asia and Russia (Archive)  > Likely go into Eastern Europe
- Andean (Archive) > Southern America
- Southern cone (Archive) > Southern America

**Comment by Parbhat** [comment]
A region should not be deleted as old submissions will not be able to get that region value. The current implementation stores the id of the region. And then [retrieve](https://github.com/OpenTechFund/opentech.fund/blob/31aab52a6d3131b2183e7fb880e04dcd7a235875/opentech/apply/categories/blocks.py#L80) the region value using that id. Deleting a region will not fetch region in old submissions.

We can add an archived feature to Category's [Option](https://github.com/OpenTechFund/opentech.fund/blob/31aab52a6d3131b2183e7fb880e04dcd7a235875/opentech/apply/categories/models.py#L19). So, we will not display archived regions in application forms. And old submissions will continue to display the archived values.

**Comment by frjo** [comment]
We have a separate issue for updating existing submissions, see #1581. The other parts of this ticket is done.
