### ISSUE TITLE
Rename comment visibility options, create a new ones, and update help text

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1174]
**-=Renames=-**

- Private => Applicant
- Reviewers and Staff => Reviewers
- Internal => Team
- Public => All

**-=To create=-**

- Applicant and Reviewers
- Private

**-=Help text changes=-**

- Applicant: Visible to applicant and team (default)
- Reviewers: Visible to reviewers and team.
- Applicants and Reviewers: Visible to applicants (including partners), reviewers, and team.
- Team: Visible only to team.
- Private: Visible only to author. 
- All: Visible to any user who has access to the submission. If the submission is public, that means he comment is publicly visible.

**Comment by frjo** [comment]
Relates to #1087

**Comment by frjo** [comment]
@danblah  See how it looks in the screenshot below. Are all these options really needed? I'm afraid the users will be a bit overwhelmed by all the options. All users will not see all the options but staff will.

![comment_visibility_ui](https://user-images.githubusercontent.com/191392/58092758-32110880-7bcd-11e9-9b07-032487f1f762.png)

**Comment by frjo** [comment]
My suggestion is that we at least skip the new "Private" option that makes the comment visible only to the user. This demands a rewrite of the comment access function that now is based on groups.

If someone want to have private notes, why should they add it do the system?

**Comment by danblah** [comment]
All good to remove the private option.

On the interface, what if have it be a pop up box from a button titled "Visibility". On click, you have checkboxes for the following:

* Applicant (default)
* Team (only visible to users in the role Staff)
* Partners
* Reviewers

The help text below updates as options are selected to say:
Visible to: OTF team, Applicants, Partners, Reviewers (etc). 

Then there's a save/submit or whatever button and it goes back to the comment edit screen.

**Comment by frjo** [comment]
@danblah So then we are down do:

* Rename Private => Applicant
* Rename Internal => Team
* Rename Reviewers and Staff => Reviewers
* Replace Public => Partners

Four options is what we have today so then the UI can stay the same.

**Comment by danblah** [comment]
Those are the right options and I like that they related to roles.

I am proposing a different interface though I don't know if its possible. Right now its a radio button with only one option that requires a lot of help text because I don't think its intuitive. I'm proposing that you have a set of checkboxes for the commenterd to select any of the above that apply to them, clearly indicating that those are who can see the comment. I think that makes would allow us to dismiss the help text all together. Is what I'm saying make sense here?

**Comment by frjo** [comment]
The new interface with checkboxes is not implemented but the names are updated and a partner option is added.

Will add a new issue for the improved interface.

**Comment by frjo** [comment]
Related: https://github.com/OpenTechFund/opentech.fund/issues/1445

**Comment by fourthletter** [comment]
- blah asked for small word change from Applicant to Applicant(s) on July 11.

All features are visible and functional during test. Thanks!

![image](https://user-images.githubusercontent.com/20019656/63457651-67710080-c41f-11e9-985c-6cfd1c956668.png)
