### ISSUE TITLE
Update to Django 2.1.x and Wagtail 2.5.x

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1184]
Django 2.2.0 is the latest release but all the packages we use does not yet support it so we first go to Django 2.1.x.

**Comment by frjo** [comment]
@fourthletter @danblah This testing is done on dev, https://dev.opentech.fund

Please test all manner of functionality.

**Comment by danblah** [comment]
@frjo is going to push this to test and then we'll test it out on test.otf.
