### ISSUE TITLE
Make it possible to pick 1-12 weeks as an duration option in the Duration stream field

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1185]
The current options are set here:

https://github.com/OpenTechFund/opentech.fund/blob/97ec20965197be7915a001882205fcb02183e9fd/opentech/apply/funds/blocks.py#L106-L121

* For statistics we want to have a single duration value in common for all submissions.
* Would like to avoid messing with current submission data if possible.

Idea: Have two duration fields, one for weeks and one for months (the current one) and then add a duration property to submissions that checks both week and month options and retrieves the right value?

**Comment by frjo** [comment]
@Parbhat Any ideas how to best accommodate this feature request?

**Comment by Parbhat** [comment]
@frjo The idea in the issue description sounds good. We can create two dictionaries one for months `DURATION_MONTH_OPTIONS` and other for weeks `DURATION_WEEK_OPTIONS`. And `DURATION_OPTIONS` will be the combination of these two dictionaries. So, the user can then select a choice based on these two.

**Comment by frjo** [comment]
@Parbhat It would be ok to display both weeks and month in the same list to the applicant. (But OTF would prefer to have to separate fields or some kind of option on the duration field to pick week or month.)

The keys are now 1-24 that represent month. What should we use for keys for week do you think, if we present them together.

0.25|1 week
0.5|2 weeks
etc.

**Comment by Parbhat** [comment]
@frjo If the requirement is to pick one from weeks or months means applicant will be shown only weeks or months and not both. Then we can add an option in duration block which will let admin choose from week and month. Depending on that we will create choices for applicant. So, the week dictionary can also use 1 key which will represent 1 week.

**Comment by frjo** [comment]
@Parbhat But when retrieving the values we need to know if the key represents weeks or month.

**Comment by Parbhat** [comment]
@frjo After we have a new field which will let admin user pick the duration is for weeks/months. Then we can update this method with a conditional. If the `duration_type` (new field) value in weeks, we will check key in DURATION_WEEKS_OPTIONS dictionary.

https://github.com/OpenTechFund/opentech.fund/blob/97ec20965197be7915a001882205fcb02183e9fd/opentech/apply/funds/blocks.py#L129-L130

**Comment by frjo** [comment]
OTF says it works well and is approved (Slack).
