### ISSUE TITLE
Reviewer ordering: list view

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#1191]
Correct reviewer ordering is:

```
<role reviews submitted ordered by role order>
<staff reviews submitted>
<role not reviewed ordered by role order>
<staff not reviewed>
---
<external reviews>
<external not reviewed>
```

(Submission View currently correct)

**Acceptance criteria**

 - [x] List View (e.g.https://apply.opentech.fund/apply/rounds/823/) ordered as per correct sort order

**QA criteria**
Dev:

 - [x] checked feature meets acceptance criteria/conforms exactly to the specification.
 - [x] provided good unit test coverage (if this is non-trivial behaviour).
 - [x] checked all tests for the project pass with this feature enabled.
 - [x] checked code conforms to the project coding standards.
 - [x] had code reviewed by another developer and resolved any issues raised.
 - [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
 - [x] checked that this feature works on the server/s I am deploying it to.

QA:

 - [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 - [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@abigail-hampson This is now deploying on dev for you to test.

**Comment by abigail-hampson** [comment]
Looks good, can be deployed to test for OTF to test

**Comment by abigail-hampson** [comment]
This is now ready for you to review, an example of this can be tested here - https://test-apply.opentech.fund/apply/submissions/all/

**Comment by fourthletter** [comment]
Acceptance criteria is visible. Thanks!

**Comment by gibbsmaya** [comment]
@frjo this is ready to be deployed to live. Can you include in your next deployment please?
