### ISSUE TITLE
Comment editing: Backend

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#1193]
Backend task for #945: comment API backend extended to handle tracking last updated

- [x] Comment list API includes last edited date
- [x] Comment editing API includes last edited in response data on successful edit
- [x] Confirm comment editing API limited to author
- [x] QA criteria satisfied

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

- [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
- [x]  checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
Testing:

You can access the API on the dev environment, you will need to be logged in:

List of comments for a submission: `https://dev-apply.opentech.fund/apply/api/submissions/10/comments/` where `10` is the id of the submission with comments.
You can also use the form at the bottom of the page to create a new comment.

Editing comments:
`https://dev-apply.opentech.fund/apply/api/comments/296/edit/ ` where `296` is the comment you wish to edit. You can only edit your own comments, and can only edit a content once. After you have edited the comment it should remain in the same position in the list view, but with the extra `edited` field data.

**Comment by abigail-hampson** [comment]
Good to be deployed to the test server

**Comment by abigail-hampson** [comment]
This can be tested on #945, with the frontend and backend together
