### ISSUE TITLE
Comment editing: front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#1194]
Front end task for #945 

**Acceptance criteria**
- [x] Private comments in django app allow editing by the author of the comment
- [x] Reviewers and Staff comments in django app allow editing by the author of the comment
- [x] Internal comments in django app allow editing by the author of the comment
- [x] Public comments in django app allow editing by the author of the comment
- [x] Edit button visible on comment (styled as per edit button on submission detail page)
- [x] Inline editing of comment with 'submit' and 'cancel' button
- [x] Updated comment to display on edit submission
- [x] Last edited date to be displayed alongside post date
- [x] Comment sort order remains as it currently is (by original post date)

**QA criteria**
Dev:
 
- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

- [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
- [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
This is now on dev and ready for testing. 

Head to https://dev-apply.opentech.fund/apply/submissions/, pick a submission and you will be able to edit any comment that you have authored.

**Comment by abigail-hampson** [comment]
Looks good to me, ready to go to the test server

**Comment by abigail-hampson** [comment]
Closing this in favour of #945, this can be tested there with the frontend and backend together
