### ISSUE TITLE
Montserrat Thin too "thin" for body text

### ISSUE THREAD

**Issue by elioqoshi** [OpenTechFund/opentech.fund#1198]
Montserrat Thin is used as a large body text paragraph for introducing a lot of pages,
example:

![image](https://user-images.githubusercontent.com/5436686/57362210-96b87600-717e-11e9-8605-e4c6f5514d68.png)

This proves to be an accessibility and readability problem. I'd suggest that Thin is not used for Body text and instead the Light weight is used.

**Comment by elioqoshi** [comment]
Thanks! Appreciate the quick turnaround :)

**Comment by fourthletter** [comment]
@frjo Thank you, it looks good!
