### ISSUE TITLE
Add front end numbers next to names to show primary and secondary reviewers

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1205]
From: Di

**Is your feature request related to a problem? Please describe.**
Add numbers next to individuals in the list and detailed view when they sign up to be primary and secondary reviewers. Example: A primary reviewer should get a "1" and a secondary reviewer should get a "2"

**Is your feature request related to an existing functionality? Please describe.**
Yes, names of individuals appear, but it is unclear whether they have signed up to be primary or secondary because numbers are not visible. Image below:

![image](https://user-images.githubusercontent.com/20019656/57470402-be7b0d00-7256-11e9-9001-26984d2d4f47.png)

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

**Ideal deadline**
Quarter 3 or 4

**Comment by danblah** [comment]
Closing, completed
