### ISSUE TITLE
Unsaved comment edit notification in Django 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1214]
Task from #1128 

**Acceptance Criteria** 

- [x] When leaving the comments page in Django users see a notification that their edit will be lost if they do not save it 
- [x] Users can remain on the page to save their edit 

**QA Criteria** 

Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x]  tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

- [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
- [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
This is now on dev and ready for testing.

For testing:
Start to edit a comment and then try to navigate away/refresh the page and you will be warned about unsaved changes.

**Comment by abigail-hampson** [comment]
Looks good, can be deployed to the test server

**Comment by abigail-hampson** [comment]
This can now be tested against the acceptance criteria at the top of this issue, an example of where this can be tested is https://test-apply.opentech.fund/apply/submissions/26/#communications

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. 10 points for Hufflepuff! 

Warning message only appeared when I refreshed, not when I click on a different tab.

**Comment by abigail-hampson** [comment]
Great, thanks for testing this so quickly. 
For the warning message not appearing when changing tabs is this in regards to the tabs on the django page, eg 'Submission details', 'Communications' etc? If so when you click between these the edits to the comments aren't lost, they remain in the editing state as the page isn't being left. As this data wasn't being lost we feel that this would be the expected behaviour for moving between these tabs. Are you happy with this approach?

**Comment by fourthletter** [comment]
@abigail-hampson I accept this approach. Thanks!
