### ISSUE TITLE
Comment editing in submission detail view 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1215]
Task from #1128 

**Acceptance criteria**

- [x] Private comments in the detail view allow editing by the author of the comment
- [x] Internal comments in the detail view allow editing by the author of the comment
- [x] Edit button is visible on comment (styled as per edit button on submission detail page)
- [x] Inline editing of comment with 'submit' and 'cancel' button
- [x] Updated comment to display on edit submission
- [x] Last edited date to be displayed alongside post date
- [x] Comment sort order remains as it currently is (by original post date)

**QA Criteria**

Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

- [ ] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
- [ ] checked that the feature works on the server/s deployed to

**Comment by abigail-hampson** [comment]
The last edited date doesn't display in the detail view, and the comment which has been edited moves to the top of the list of comments. Could you take a look at these please

**Comment by todd-dembrey** [comment]
Good spot, I have fixed both of the issues and deployed the changes to dev.

**Comment by abigail-hampson** [comment]
This is ready to be tested against the acceptance criteria at the top of this issue. This can be tested here - https://test-apply.opentech.fund/apply/rounds/732/?submission=11

**Comment by fourthletter** [comment]
All acceptance criteria visible and functional. Thanks! 🔥
