### ISSUE TITLE
Switching between submissions in detail view retains comments 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1216]
Task from #1128 - 'Unsubmitted notes will persist between switching submission (if you remain on the page). E.g. if you accidentally change submission, the note will not be lost and will be visible when you re-select the submission' 

**Acceptance Criteria** 

- [x] Unsaved comments added to a submission are not lost when switching to a different submission 
- [x] Unsaved comments on a submission don't show on other submissions 

**QA Criteria**

Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

- [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
- [x] checked that the feature works on the server/s deployed to

**Comment by abigail-hampson** [comment]
Hi Todd, The edits are currently lost when switching submission, it reverts back to the unedited comment still in the edit section

**Comment by todd-dembrey** [comment]
I have updated the code to also work for the editing as well as the adding of notes.

**Comment by abigail-hampson** [comment]
This is now ready for testing against the acceptance criteria at the top of this issue, this can be tested here https://test-apply.opentech.fund/apply/rounds/732/?submission=11 by adding and editing the comments to check the edits remain when switching to a new submission

**Comment by fourthletter** [comment]
Acceptance criteria are visible and functional. Thanks! 🔥
