### ISSUE TITLE
Remove sections of the determination form that don't have any text from the email that goes to applicants

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1223]
Account name or name of person: Di

**Is your feature request related to a problem? Please describe.**
Please remove the sections of the determination form that don't have any text from the email that goes to applicants.

Example: A determination email has sections named: Goals/Principles, Technical merit, Reasonable, realistic and sustainable, Other comments. Staff sends a message with these section without text. The applicant receives an email with these section titles, but no text is provided underneath these section titles. 

**Is your feature request related to an existing functionality? Please describe.**
Applicants receive determination messages, but 

**Describe the solution you'd like**
Staff wants to ensure these messages are clear to applicants. Additional section headings without text confuse applicants.

**Describe alternatives you've considered**
Staff has administrative rights to edit automated determination messages in Wagtail.

**Additional context**
Below is image of a message. The Goals section contains the message we want to convey, but the other sections are blank. These section headings are unnecessary. 
![image](https://user-images.githubusercontent.com/20019656/57789800-9fbdc000-7707-11e9-9ee6-ce664805586e.png)

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff
- Applicants

**Ideal deadline**
Q2 or Q3

**Comment by fourthletter** [comment]
Related to #635

**Comment by frjo** [comment]
We are removing all extra fields from determination e-mails for security reasons in #1731 so closing this.
