### ISSUE TITLE
Can't save edits to active review forms, requires field: Visibility

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1228]
**Describe the bug**
When trying to save edits to active review forms, I'm getting the following error:
`You are missing the following required fields: Visibility`

**To Reproduce**
1. Go to 'https://apply.opentech.fund/admin/review/reviewform/edit/46/'
2. Make edits
3. Click on 'Save'

**Expected behavior**
Things would be saved.

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff/Team

**Comment by frjo** [comment]
@danblah please add the new visibility field as the error indicates and you will be able to save. That field makes it possible to set the visibility of a review. A new feature we added a couple of months ago. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
I think the visibility field looks best on top of the form. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danblah** [comment]
Ahh, ok!
