### ISSUE TITLE
Display “supported projects” in chronological order from newest to oldest rather than oldest to newest

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#1233]
Relevant page: https://www.opentech.fund/results/supported-projects/ 

**Problem statement**
At present, newly added projects show up on the last page (page 6 at present: https://www.opentech.fund/results/supported-projects/?page=6). The first page (https://www.opentech.fund/results/supported-projects/) shows the oldest projects.

**Describe the solution you'd like**
Newly added projects show up in chronological order from newest to oldest from page 1 onward, rather than oldest to newest. 

**Priority**
- Low priority (annoying, would be nice to not see)

**Ideal deadline**
If it's an easy fix, the sooner the better. If it's complicated, know that this isn't a high priority.

**Comment by frjo** [comment]
@dmcdev1  Please test at https://test.opentech.fund/results/supported-projects/

**Comment by dmcdev1** [comment]
tested, looks good to me. thanks @frjo
