### ISSUE TITLE
Remove the default "shadow effect" for project logos

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#1234]
**Is your feature request related to a problem? Please describe.**
The logos on individual projects pages render weird/hard to see because of the "shadow effect" wherein the logo is superimposed over a zoomed in image of the logo. See for example: https://www.opentech.fund/results/supported-projects/fort-rpki-validator/ and https://www.opentech.fund/results/supported-projects/k-9-mail/

**Describe the solution you'd like**
Simply remove that default effect so that the logo displays the image as is with no added effects/shadows.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- General public

**Comment by frjo** [comment]
@dmcdev1 Please test at:

* https://test.opentech.fund/results/supported-projects/server-side-blocking-characterizing-and-measuring-service-providers-discrimination/
* https://test.opentech.fund/results/supported-projects/
* https://test.opentech.fund/funds/internet-freedom-fund/

The same effect was used on people images etc. as well and it used the same template/code so all now have a new, better, look.

I have noticed the "shadow effect" and thought it looked a bit weird. I guess it looked good at one time with stock images.

**Comment by dmcdev1** [comment]
The people pages and most of the individual project pages look good. However, there are some exceptions where it seems to be making the zoomed in version the default; see for example:
-  https://test.opentech.fund/results/supported-projects/opennet-africa/
- https://test.opentech.fund/results/supported-projects/measurement-lab/ 
- https://test.opentech.fund/results/supported-projects/derecho-digitales/

If there's a way to mitigate this without having to manually change all of the affected project images, that would be great and save time.

And agreed - the shadow effect worked and looked cool for some, but for others it just doesn't work.

**Comment by frjo** [comment]
@dmcdev1 Looks better now? The listing page still have the same issues but unsure how to best fix it without changing the layout to much.

**Comment by dmcdev1** [comment]
@frjo yes, I think it looks better now. Regarding the listing page, I see that it has that same issue but in my view it actually looks ok. So long as the individual project pages clearly display the image I'm ok with the listing page having the zoomed in focus.
