### ISSUE TITLE
Improve security of submission private uploads

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1241]
A number of measurement to improve the security of submission private upload files. This is now in testing on https://test-apply.opentech.fund/

1. Lowered the AWS_QUERYSTRING_EXPIRE to 10 seconds.
2. Set up a new policy on arn:aws:s3:::test-public.opentech.fund that only allows get request if the referrer is "https://test-apply.opentech.fund/*".
3. Made submission upload links open in a new tab (target _blank) (only for usability).
4. Set bucket policy arn:aws:s3:::test-public.opentech.fund to block all public access (this just means that the OTF WebApp can't by mistake upload a file and set it to public).

Referrer headers are not hard to spoof but you would only have 10 seconds to do it.

If it works well in you testing to have AWS_QUERYSTRING_EXPIRE as low as 10 seconds I believe that the referrer header checking in S3 is not needed.

**Comment by danblah** [comment]
This works great. Lets deploy.
