### ISSUE TITLE
The score of an individual review is not calculating correctly

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1244]
Set the value of "N/A" = 0/Zero
Set the value of "Needs more info" = 0/Zero

For all the scores in a review
* Sum(score _**1**_, score _**2**_, score _**n**_…) / total _**n**_ scores

Apply this to all previous reviews

**Comment by frjo** [comment]
Please test on the test site. When a reviewer select not to answer a question (NA), the question is still counted with a score of 0 when calculating the average.

**Comment by fourthletter** [comment]
Testing worked! Reviewer selected not to answer a question (NA), the question is still counted with a score of 0 when calculating the average.

![image](https://user-images.githubusercontent.com/20019656/63347154-8c347d80-c324-11e9-8146-7dc3f312aed9.png)
