### ISSUE TITLE
Related pages for Labs render with a "Related Requests" at the bottom of the page, which is incorrect. The header should be "You might also like..."

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1246]
See https://www.opentech.fund/labs/legal-lab/ as an example.

**Comment by frjo** [comment]
Please test on the test site. The text should now be "You might also like…"

**Comment by fourthletter** [comment]
@frjo It still shows "Related Requests" 
![image](https://user-images.githubusercontent.com/20019656/63433494-498ca700-c3f1-11e9-9537-ed6cf05c2a1d.png)

**Comment by fourthletter** [comment]
@danblah do you like these changes to legal lab? https://test.opentech.fund/labs/legal-lab/

"Related Requests" has been removed and headings have been updated in the test site.

**Comment by frjo** [comment]
@fourthletter To see the change one needs to add some related pages to a lab.
