### ISSUE TITLE
Create a new page template called "Results", that can be placed anywhere.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#1248]
This is needed for the leads of Labs, Fellowships, and Funds to highlight noteworthy outcomes as a sub/child page. See a https://gomockingbird.com/projects/s5m06oe/4gXVnC to get a rough idea

This would require creating four new streamfields
* One to choose from all project pages to include in a list, header will be "Projects"
* One to choose from all people/fellow pages to include in a list, header will be "People"
* One to choose from all articles to include in a list, header will be "Updates"
* One to choose from all pages to include in a list, header will be "Related pages"

Each should have a description field included after the header, before the list

The above will all fit within a defined section that can have other normal fields (textfield etc.) above or below it as defined by the author.

Once we've the page template going with the content, the folks at Ura will craft a look/feel mockup for us to implement into html/css.

**Comment by frjo** [comment]
@danblah I understand the content type itself and the needed fields but where is it you want to display these pages?

Is it on e.g a Lab index page like https://www.opentech.fund/labs/ or on a specific Lab page like https://www.opentech.fund/labs/community-lab/ ?

If on a index page, should it look like the other items in the list?

If on a specific fund/lab page should it be a link/button somewhere to the result page?

Should the link/button show up automatically? Can it be more than one result page

If not as a link/button should the complete page show up in a box at the bottom or somewhere else?

**Comment by danblah** [comment]
We want the ability to place them in multiple places (as a child page for labs, funds, and other pages). We want it to replace this page https://www.opentech.fund/results/impacts-and-outcomes/, be something the labs can create themselves, etc.

Those are good questions but for now, I think we'll just use the Related Pages function and have it listed at the bottom, then go from there. There is a bug to fix where any related page shows up incorrectly as well (see https://github.com/OpenTechFund/opentech.fund/issues/1246 and https://github.com/OpenTechFund/opentech.fund/issues/1245). 

That should resolve the more than one question (there can be, if needed). There's no need for a special button right now (maybe later).

**Comment by fourthletter** [comment]
@frjo here is the mockup of we want to display https://www.figma.com/file/NHrPwDhOz1aDbKy2eR93HR8m/Impacts-and-Outcomes?node-id=0%3A1 (zoom to 50% to view)

**Comment by fourthletter** [comment]
@frjo We were able to create a new page template called "Results" during testing. This issue is on hold because Ura is using the test template to refine their designs. Thanks!

**Comment by frjo** [comment]
After talking with Url and OTF this is so not what is needed so closing.
