### ISSUE TITLE
Flexible grouping of Application form fields

### ISSUE THREAD

**Issue by Parbhat** [OpenTechFund/opentech.fund#1252]
**Is your feature request related to a problem? Please describe.**
The current grouping feature assumes fields after `Group fields` block are part of the next group say 2. But some fields that appear after the grouper fields should always display on the page. Currently, if a user selects the second option of group field block, all fields after it are hidden.

**Is your feature request related to an existing functionality? Please describe.**
This is an addition to #1064 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff

**Ideal deadline**
Asap

**Comment by frjo** [comment]
@danblah @fourthletter  This is ready for test on test. 

The group field now also have and end version. All fields between the two are part of that group.  This allows you to have multiple groups with optional non grouped fields in between.

(Nested groups are not possible but if needed @Parbhat has a way to implement that but it takes time.)

**Comment by Parbhat** [comment]
Created issue #1259 for the alternative implement using stream block for Q3.

**Comment by Parbhat** [comment]
Thanks for the details @frjo. One point to add is: Fields within group should be optional to successfully submit the form if user chooses second choice of group field.

**Comment by danblah** [comment]
Is this on test or prod?

**Comment by frjo** [comment]
Testing on test.
