### ISSUE TITLE
In site footer, replace BBG logo with USAGM

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#1264]
Please find the new image attached here. I don't think I'm able to do this through the CMS, or at least I couldn't find the place to do so. Thank you.

![USAGM-BBG-logo-horiz-RGB-hires](https://user-images.githubusercontent.com/28866038/58971230-38c87f80-8778-11e9-9cc8-8481ae8119a6.png)

**Comment by danblah** [comment]
Seems this is a transparent png but its showing up with an unacceptable white background on our website. Can we make it transparent so that its not ugly?

**Comment by danblah** [comment]
Can we also trip this logo so that its only the stuff left of the | (don't include the |)?

**Comment by frjo** [comment]
@danblah Will fix that. Many organisations are sensitive about their logos so I was hesitant to start cutting at it.

**Comment by dmcdev1** [comment]
thanks @frjo for the color fix, definitely agree we can't publish it with the color scheme as it appears in the attached logo - I assumed it would automatically adjust the color scheme, but if that's not the case and you need a new/manually edited version, just let me know. also, re: editing the logo @danblah - I actually looked for a version of the logo you're describing as I agree there's just a lot of text in there for a small logo...but every version used by USAGM includes the text on the right hand side. So I think it'd be best if we just leave it as is and avoid any issues.

**Comment by danblah** [comment]
The size isn't the issue for me, its the color. You won't be able to see it due to the OTF blue background color or the size. My vote is still to remove it.

**Comment by frjo** [comment]
@danblah 

1. Should the logo not have a white background as I have given it on test?
2. Should it even be only white and transparent as the current BBG logo in the footer on live?

**Comment by frjo** [comment]
New logo to test on test.

I have cut of the right part and not added a white background. This made it necessary to make the text white as well, otherwise it was nearly invisible.

**Comment by danblah** [comment]
Looks great!

**Comment by dmcdev1** [comment]
looks ok, but it'd be great if we could get rid of the red in the logo and have it like was before, all white.

let me know if the attached version works, I'd like to see it on test for comparison.
![USAGM_logo_white](https://user-images.githubusercontent.com/28866038/60748170-6277f080-9f48-11e9-9c80-ffafee8c0b67.png)

**Comment by frjo** [comment]
@dmcdev1 @danblah You want the red arcs in the logo to be white instead?  Would have been easier if you explained that you wanted a 100% white logo to start with. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dmcdev1** [comment]
looks good to me @frjo,  thanks
