### ISSUE TITLE
Progressing an submission to 'Advisory Council Review' fails

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1265]
It take a long time and then you get an error.

![Screenshot 2019-06-06 at 12 39 09 PM](https://user-images.githubusercontent.com/191392/59058521-209e5080-889d-11e9-8d14-4885a41399a4.png)

On local dev env I get 

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /apply/submissions/xxxx/.

Reason: Error reading from remote server
```

Other stats works.

**Comment by frjo** [comment]
@Parbhat I get nothing in my log file on local dev. Any ideas where to start looking?

**Comment by Parbhat** [comment]
@frjo I can not reproduce the issue locally. Changing the status of a submission to AC review works fine. 

>Proxy Error

>The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /apply/submissions/xxxx/.

>Reason: Error reading from remote server

Is this the error from Heroku logs?

**Comment by frjo** [comment]
@Parbhat I get no logs at all.

Can you test to assign partners to a submission and then try to change the status to AC review?

When I removed partners from a submission it problem disappeared. Investigating now.

**Comment by Parbhat** [comment]
@frjo No issues after adding partners to submission and then changing the status to AC review.

**Comment by Parbhat** [comment]
Is the issue appears on live site again? Looks like a Heroku issue as sentry should have recorded the issue for the code bug.

**Comment by frjo** [comment]
I believe I have tracked it down to this function:

https://github.com/OpenTechFund/opentech.fund/blob/00d4c34feafea68bfd47c34ad9727108929b8e00/opentech/apply/funds/models/submissions.py#L630-L634

The `reviewers | partners` sometimes creates what seems to be duplicates. The querysets look as they should separately but, and this is a bit weird, some users created *a lot* of duplicates, and other only a few. Most none.

Any idea what is going on here?

**Comment by frjo** [comment]
The duplicates numbers in the hundreds so the system chokes/timeouts when it tries to send out all the mails.

The mails should be sent with a queue, but that is another issue.
