### ISSUE TITLE
Accurate number of reviewers should appear in summary

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1269]
**Describe the bug
An accurate number of AC reviewers should appear in the List View summary. The number "42" appears next to the spotlight when it should be 2-3 maximum or only the total number of individuals that have been assigned to review.

**To Reproduce**
![image](https://user-images.githubusercontent.com/20019656/59115061-74994b80-8916-11e9-92e6-b111825bb176.png)

**Expected behavior**
Only reviewers who signs up should appear in summary. Perhaps 2-3 individuals maximum.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

**Comment by frjo** [comment]
@fourthletter I believe this is accurate numbers. This submission have all but one AC reviewer assigned and then a number of staff.

**Comment by danblah** [comment]
*nod*
To adjust that number, add/remove reviewers from the fund page here: https://apply.opentech.fund/admin/pages/729/edit/?next=/admin/funds/fundtype/ (which currently has 42ish reviewers selected. All of them will get an individual notification when a submission is progressed into AC review.

**Comment by fourthletter** [comment]
@frjo We could close this issue since this is the intended design feature. Thanks!
