### ISSUE TITLE
Make new accounts active directly

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1275]
A number of people seem to miss or ignore the activation e-mail. This adds support work for the staff and hassel for the user.

By making the accounts active directly and setting a temp password the password reset function will work for all accounts.

Add link to the password recover function to the activation e-mail. To be used if the activation link has expired (8 days as of now)

**Comment by frjo** [comment]
@danblah @fourthletter Please test this from all angels you can think of. Quite important that users accounts work.

I have made the following changes:

* New accounts are set to active directly with a very long temporary random password. The temporary password is needed so the password reset function works.
* The activation is now only about setting their own password.
* Added a link to the password reset form in the activation e-mail. Useful if they do not use the activation link within 8 days so it expire.

**Comment by danblah** [comment]
Change the text to be:

`If you do not complete the activation process within {{ timeout_days }} days you can use the password reset form at: {% if site %}{{ site.root_url }}{% else %}{{ base_url }}{% endif %}{% url 'users:password_reset' %}`

Just confirming workflow here please @frjo:

1. Applicant applies
2. Account is created, random password set, set as active (a django thing)
3. App sends email with activation email that brings them to a change password page if they click
4. If they don't click, After 8 days, activation link expires (they click it it'll say something like a 404 or 403 or whatever)
5. Regardless, account stays marked as active to django

And then we need these tickets for the following functions:
* Looks for active accounts that have not logged in for more than 120 days and marks then inactive (requiring admin to manually mark active)
* Looks for any inactive accounts w/o any associated content (reviews, submissions, determinations, etc) and deletes them.

I tested this, creating a new account (see https://test-apply.opentech.fund/django-admin/activity/event/322/change/?_changelist_filters=submission__id%3D40). Where is the activation email being sent? I'm not seeing it there in the msg log.

**Comment by frjo** [comment]
Related #1281

@danblah  The workflow is correct. The e-mail is sent to the account address, that part of the functionality is untouched.

I have updated the PR with the improved text in the e-mail as well.

**Comment by danblah** [comment]
Hmph. Weird. I totally got the activation email as expected, its just not showing up in the message log page. Any reason for that? Otherwise, tested and seems well to me.
