### ISSUE TITLE
External "Leads" assigned to round or lab that gets staff permissions for related submissions

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1276]

**Comment by saoun** [comment]
what does this mean @frjo ?

**Comment by frjo** [comment]
I think OTF wanted to be able to assign outside people (non staff) as leads and that they then would get staff permissions for only those submissions.

I'm always hesitant of letting non staff in with high permissions.

**Comment by saoun** [comment]
I see. I will close this for now since I can't see how it would be relevant with the current workflow. 

@danblah if there's something I missed here, please ping and we will reopen.
