### ISSUE TITLE
Incorrect Timestamp on Reviews in WebApp

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1286]
- Account name or name of person: Di
- Title of submission (app URLs alone are OK): https://apply.opentech.fund/apply/submissions/1445/

**Describe the bug**
Every review has been timestamped as 2019-06-03

**Expected behavior**
Timestamp should reflect the actual date of submission. The current behavior shows every review submitted with the same date. If this is in fact accurate then I am amazed. 

**Priority**
- Medium (slowing you down)

**Affected roles**
- Reviewers

**Screenshots**
<img width="315" alt="Screen Shot 2019-07-03 at 10 57 27 AM" src="https://user-images.githubusercontent.com/20019656/60602472-d74cfe00-9d81-11e9-8896-cb2be694b0b8.png">

**Comment by frjo** [comment]
@fourthletter That is the updated date and according to the database it's correct. Some code did a mass update of the reviews at the date. I believe it was one of the things Todd did in his minisprint.

There is also a created date that shows the date the content was created. We can switch to display that instead if it makes more sense to you. Or we can pick one to display in all places where only one date fits and then on the review detail view show both.

**Comment by fourthletter** [comment]
Please have the submission/application show specific date the content was created. Will this impact or change how dates on the review detail view? Displaying two dates in the review detail view would clutter this view.

**Comment by frjo** [comment]
@fourthletter You can decide what date to use in any/all the places we have review dates.

It sounds like you want to replace "modified date" with "created date" in all places.

Just understand that you can then not see when a review has been updated/changed/edit.

**Comment by danblah** [comment]
Let's try created date for reviews now and then be sure there is a modified/edit date somewhere in the actual review (if not already).

**Comment by frjo** [comment]
Please test on the test site. Reviews now use the created date instead of the updated date.

On the Review detail view the updated date will show as (Last updated 2019-08-19) if it differs from the created date.

**Comment by fourthletter** [comment]
Review now use the created date and the detail view shows lasted updated date. Test worked! (image below)

![image](https://user-images.githubusercontent.com/20019656/63345991-057ea100-c322-11e9-933f-b73f54a38217.png)
