### ISSUE TITLE
Applicant should not see who the reviewer is or their score on the submission page or activity feed.

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1287]
- Account name or name of person: Di
- Title of submission (app URLs alone are OK): https://apply.opentech.fund/apply/submissions/4028/#activity-feed

**Describe the bug**
Applicant could see reviewers and scores when they visit the activity feed. This content should be private.

**Expected behavior**
Applicants see the workflow status of their submission and external comments in the activity. However, they should not be able to access other private information. 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff
- Applicants

**Comment by danblah** [comment]
This information is hidden. Applicants don't see the same thing staff do. They only see for example without a link:

Action

Reviewer – 2019-06-28 21:27

Submitted a review
