### ISSUE TITLE
django-storages 2.0 will no longer default to public-read

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1290]
django-storages gives this notice:

"The default behavior of S3Boto3Storage is insecure and will change in django-storages 2.0. By default files and new buckets are saved with an ACL of 'public-read' (globally publicly readable). Version 2.0 will default to using the bucket's ACL. To opt into the new behavior set AWS_DEFAULT_ACL = None, otherwise to silence this warning explicitly set AWS_DEFAULT_ACL."

I suggest we set "AWS_DEFAULT_ACL = None" now and add a bucket policy on the public s3 buckets that allow GetObject on all files for public.

This will prepare the system for django-storages 2.0. The end result will be identical to now, the difference is that instead of marking each individual file with public read access, we set that on the whole bucket.

Set bucket policy on all public S3 bucket to GetObject

```
{
  "Id": "Policy1562302603386",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1562302600239",
      "Action": [
        "s3:GetObject"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::xxx-public.opentech.fund/*",
      "Principal": "*"
    }
  ]
}
```

**Comment by frjo** [comment]
@danblah Sounds ok?

**Comment by danblah** [comment]
Ok!

**Comment by frjo** [comment]
This is now implemented on all environments.
