### ISSUE TITLE
Highlight opening of field groups to make it clear to the user what is happening

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1297]

**Comment by danblah** [comment]
Heya, reviewing this but don't understand the testing criteria. Please provide.

**Comment by frjo** [comment]
The background of the field group gets highlighted and then fades out when opening it. Is the styling effect  better or worse for the user?

**Comment by frjo** [comment]
Test form here https://test-apply.opentech.fund/cpf-test-fund/

**Comment by saoun** [comment]
tested, all good!
