### ISSUE TITLE
Reviewers who send in applications can not edit them

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1298]

**Comment by frjo** [comment]
This solution adds a new group (role) called "Applicant". All applicants will need to belong to this group. New user accounts should get this group when they submit an application and I have code that updates all old accounts.

Needed to do a number of followup changes for this so please look out for edge cases.

**Comment by fourthletter** [comment]
@frjo Please proceed with your proposed solution. Thank you!

**Comment by frjo** [comment]
@fourthletter This is already on test for you to test.

**Comment by fourthletter** [comment]
@frjo I am not able to edit my reviews

Test1: https://test-apply.opentech.fund/apply/submissions/33/reviews/18/
Test2: https://test-apply.opentech.fund/apply/submissions/35/reviews/22/

**Comment by frjo** [comment]
@fourthletter When an application just have been sent in and is in Screening the applicant can not edit it.

I now moved https://test-apply.opentech.fund/apply/submissions/35/ to "Need more info" and now the "Test applicant" can edit it. So I think it works as it should?

Please continue testing to see that this works as it should.

**Comment by fourthletter** [comment]
@frjo Yes, this test works. Thank you!
