### ISSUE TITLE
The submission revision diff view sometimes makes Google Chrome unhappy

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1299]
On complex diffs with a lot of formatted text Chrome is not able to process the output of the view. Safari and Firefox are not effected.

**Comment by frjo** [comment]
@danblah @fourthletter Please test the revised diff function on test.

E.g. https://test-apply.opentech.fund/apply/submissions/33/revisions/compare/57/56/

I tested the current diff function and compared it with a diff in my editor with the content directly from the database. They did not agree on much, and I' know that my editor works.

I then set out to fix the sites current diff function and I got it to show correct results, but at a price. 

I'm stripping all formatting and line breaks from the text for each question. Only each field label (H4) remains formatted.

**Comment by fourthletter** [comment]
@frjo This looks good, test worked. Thanks!
