### ISSUE TITLE
Make "internal" the default option on comments

### ISSUE THREAD

**Issue by arduina** [OpenTechFund/opentech.fund#1303]
The default option on comments is "private", which makes it visible to the applicant and staff. I would suggest to make "internal" the default to prevent this from happening accidentally, as comments sometimes include sensitive information or comments are not supposed to be communicated to the applicant.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff
- Applicants
- Reviewers

**Comment by danblah** [comment]
See https://github.com/OpenTechFund/opentech.fund/issues/1174 as well

**Comment by fourthletter** [comment]
Related to #944

**Comment by frjo** [comment]
Please test this on test. Default for staff is "team" and for others "applicant" as before.
