### ISSUE TITLE
Redirects from the old.opentech.fund domain don't redirect

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#1324]
**Describe the bug**
The site redirects for broken links and such only work from **opentech.fund**, not **old.opentech.fund**. I've come across links to the old.opentech.fund site in the wild but can't create the needed redirect at present.   

**To Reproduce**
1. Go to https://old.opentech.fund/apply/alternative-sources-support/ for example
2. It should fwd you to https://guide.opentech.fund/appendix-iv-alternative-sources-of-support
3. But it doesn't because I can't add the redirect

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- General public

**Screenshots**
<img width="838" alt="Screen Shot 2019-07-24 at 10 16 22 AM" src="https://user-images.githubusercontent.com/28866038/61810264-1e1b9a00-adfc-11e9-90b8-aaea94dfab18.png">

**Comment by frjo** [comment]
The domain archive.opentech.fund and old.opentech.fund are only used for the old Drupal site. We first created one of them then Dan thought the other name was better.

They should not be used for the current site.

**Comment by dmcdev1** [comment]
I hear that @frjo - I don't use those domains for anything, but somehow they are ending up being used out there in the wild. I'm guessing that is because they are indexed/searchable. See this screenshot for example - I put in "open tech fund Szeming" (first name of a fellow) and the first result is from the archive.opentech.fund domain: 

<img width="885" alt="Screen Shot 2019-07-25 at 11 11 30 AM" src="https://user-images.githubusercontent.com/28866038/61894145-006a3580-aecd-11e9-9ec5-9f101cf20c03.png">

Whereas this is the case I think we should explore being able to setup redirects between these domains if possible.

**Comment by danblah** [comment]
ive removed public access from old.otf and archive.otf. the results should go a way as things are recrawled.
