### ISSUE TITLE
Application Detail Page: Copy relevant submission fields from accepted submission

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1326]
- [x] On creation of project the following fields are copied from the submission:
Title 
Email  
Address 
Value 
Full Name 
- [x] QA complete

**Comment by abigail-hampson** [comment]
Looks good

**Comment by abigail-hampson** [comment]
Hello, 

This is now ready for testing against the acceptance criteria, if you have created a project the above fields should be automatically populated if they were present on the submission.

Thanks, 
Abigail

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Thanks!🔥
