### ISSUE TITLE
Project Detail View: Assign Lead 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1328]
**NB: updated Program Manager to Lead**

- [x] Lead can be assigned 
- [x] Lead is limited to OTF staff
- [x] Reusing the modal component 
- [x] Slack message is sent to OTF staff member to tell them they have been assigned to the project 
- [x] Projects can be reassigned 
- [x] Lead can't be unassigned 
- [x] Can only have one Lead at a time 
- [x] Lead is listed below the title in the same style as an application submission lead 
- [x] QA is complete

**Comment by ghickman** [comment]
Should a Lead be assigned when we create a Project?

**Comment by abigail-hampson** [comment]
I think it shouldn't have to be, it can be or it can be added later. Todd do you agree?

**Comment by abigail-hampson** [comment]
Still says program manager on the main project page other than that looks good

**Comment by abigail-hampson** [comment]
This is still showing Program Manager for me - https://dev-apply.opentech.fund/apply/projects/2/

**Comment by abigail-hampson** [comment]
Looks good, ready to go to test

**Comment by abigail-hampson** [comment]
This can now be tested against the acceptance criteria above, this can be tested by assigning the project lead on a project page

**Comment by frjo** [comment]
@abigail-hampson When I Try to set lead I get an 500 error.

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. The test was as smooth as nutella. Thanks!

**Comment by frjo** [comment]
@fourthletter You did not the an error when assigning a lead?

**Comment by fourthletter** [comment]
@todd-dembrey @frjo 

I found the application that receives errors: https://test-apply.opentech.fund/apply/projects/4/
[ ] Go to submission
[ ] Click on 'Lead'
[ ] See error (image below)

![image](https://user-images.githubusercontent.com/20019656/64734330-6aa65c00-d4b4-11e9-853b-22acda82bfcb.png)

**Comment by danblah** [comment]
Tested, works but I'm not sure about the "Lead can't be unassigned" test. 🤷‍♂
Otherwise, all good.
