### ISSUE TITLE
Project detail view: Linking activity/ existing model comms to project 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1329]
generic FK 

- [x] Activity model updated to allow FK to projects as well as submissions 
- [ ] Activities created for project link to project 
- [ ] Create project event logs the activity 
- [ ] Assign program manager event logs the activity

**Comment by abigail-hampson** [comment]
Looks good to me

**Comment by abigail-hampson** [comment]
is this on test?

**Comment by abigail-hampson** [comment]
Hello, this can now be tested on test against the acceptance criteria. This can be tested by creating a project and assigning a lead, this will trigger the events which display on the screen

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. Test was as smooth as a rock in a pond. Thanks!

![image](https://user-images.githubusercontent.com/20019656/64556975-8c65de80-d30e-11e9-939b-4028a1fccf98.png)
