### ISSUE TITLE
PAF Page: Make PAF Page 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1330]
Contracting fields on project 

-  [ ] If an approval form has not been started, there is a link to create an approval form from the project page 
- [ ] If an application form exists there is the ability to edit this 
- [ ] Application form opens in a new page 
- [ ] Application form has the following fields: 
project title 
personal/organisational name
email
phone 
address
project value 
proposed start 
proposed end 

 - [ ] From the application form page there is the ability to save and return to the project page 
- [ ] Project page information updated based on content of approval form 
- [x] QA is complete

**Comment by abigail-hampson** [comment]
Looks good to me, ready to go to test

**Comment by abigail-hampson** [comment]
Hello, this can now be tested on test. You can test this by going onto a project and creating and editing and approval form

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Test was as smooth as butter. Thanks!
