### ISSUE TITLE
Project Detail: PAF Doc Upload - Upload new doc 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1331]
- [ ] Supporting documents section has the upload button which opens a model to upload a document, name it and assign the document category 
- [ ] On upload users are redirected back to an anchor on the document section
- [ ] Django message shows on success 
- [ ] Failure behaviour is the same as the current failure behaviour (reopens the modal on failure)
- [ ] Files are listed below supporting documents 
- [x] QA complete

**Comment by abigail-hampson** [comment]
Anchor doesn't seem to be working 
Doesn't seem clear how to open the doc upload box 
Otherwise looks good

**Comment by abigail-hampson** [comment]
Hello, this is now ready for testing. Could you test with a project that is newly created against the acceptance criteria above? 
Thanks!

**Comment by fourthletter** [comment]
I was not able to complete this test and upload a document because the 'category' section wasn't functional. 


![image](https://user-images.githubusercontent.com/20019656/64530801-fc0ea600-d2db-11e9-8ce6-79bacd081a4a.png)

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional during test. Test was as smooth as custard. Thanks!
