### ISSUE TITLE
Detail view supporting documents component FE

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1337]
- [ ] Create rows that can accommodate two links
- [ ] Supporting documents - Upload new, opens a modal 
- [ ] Two states for the ticks - complete and incomplete 
- [ ] Added documents appear as design

Actual functionality of the links to be handled in BE ticket

**Comment by chris-lawton** [comment]
Reviewed with Todd
- Download all has been removed
- Download proposal has been removed
- Supporting docs link - only Upload new button should be present

**Comment by abigail-hampson** [comment]
The added docs don't seem to appear quite as the design does - https://dev-apply.opentech.fund/apply/projects/2/
