### ISSUE TITLE
Application Detail Page: Create project when accepted determination sent

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1343]
- [ ] When an accepted determination is sent a project is created 
- [x] QA is complete

**Comment by ghickman** [comment]
Should we redirect to the Project detail page as part of this?

**Comment by abigail-hampson** [comment]
Looks good to me!

**Comment by abigail-hampson** [comment]
Is this on test?

**Comment by abigail-hampson** [comment]
Hello, this is ready to be tested on dev against the acceptance criteria. This can be tested by setting an accepted determination and the project page being created from this

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Test was smooth as silk. Thanks!
