### ISSUE TITLE
PAF Doc upload: Document categories 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1344]
- [ ] From the Wagtail admin I can define the categories of documents (name and minimum required) 
- [ ] These types are listed on the project page within the supporting documents section of the PAF form
- [ ] Ordered alphabetically  
- [x] QA is complete

**Comment by abigail-hampson** [comment]
This only shows name and minimum, not the type of document - unless this is purely for defining the types with a name and minimum not a file type for each

**Comment by todd-dembrey** [comment]
We never intended to use filetypes, hence the change to category. I think the acceptance criteria were using the old nomenclature. have updated to be in line with what we discussed. This should now meet the criteria.

**Comment by abigail-hampson** [comment]
Makes sense, this is good to go to test then

**Comment by abigail-hampson** [comment]
This is now ready to test against the criteria above. This can be tested by adding categories in the Wagtail admin and testing these are used by uploading documents on a project page

**Comment by fourthletter** [comment]
I added categories in the Wagtail admin [https://test-apply.opentech.fund/admin/application_projects/documentcategory/] and uploaded documents on a project page. Test was smooth as peanut butter. Thanks!
