### ISSUE TITLE
Send to director doc confirmation

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1345]
- [ ] If not all minimum required document categories are met the send for approval modal will tell you what's missing and confirm you're still happy to send this

**Comment by abigail-hampson** [comment]
Looks good to me

**Comment by abigail-hampson** [comment]
Hi Di, 

This ticket is now ready for testing on test against the acceptance criteria. This can be tested by not uploading all recommended files and submitting for director approval. 

Thanks, 
Abigail

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Test was smooth as ice. Thanks!
