### ISSUE TITLE
Removing Files 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1347]
- [ ] files can be removed by posting a form to the backend

**Comment by abigail-hampson** [comment]
Looks good, can be pushed to test

**Comment by abigail-hampson** [comment]
Hello, 

This is now ready for testing against the acceptance criteria, you can test this by uploading a document to a project and then removing it with the remove button

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Test was as smooth as a github issue bound in leather. Thanks!
