### ISSUE TITLE
'Show more' on Project page 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1348]
- [ ] Show more reveals the additional fields when clicked on

**Comment by chris-lawton** [comment]
This is now on dev - https://dev-apply.opentech.fund/apply/submissions/9/

**Comment by abigail-hampson** [comment]
Looks good, ready to go to test

**Comment by abigail-hampson** [comment]
is this on test?

**Comment by abigail-hampson** [comment]
This is now ready for testing, the 'show more' will show on project pages to show more fields

**Comment by frjo** [comment]
@abigail-hampson I have seen this earlier but not any longer either on dev or test.

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional. Test was as smooth as a cool breeze. Thanks!
