### ISSUE TITLE
FE General Review and Tidy 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1349]
- [ ] Review current OTF site for FE bugs 
- [ ] Fixes to bugs

**Comment by chris-lawton** [comment]
Fixes carried out in this ticket:

- ensure a tab is activated when there’s a trailing hash in the url (e.g. https://dev-apply.opentech.fund/apply/submissions/9/# would previously show an empty page)

- improve spacing of buttons in the sidebar (they had no left/right space previously) 

- centre align activity feed + and - icons

- correct width of comments column in submissions table

- ensure status block titles don't bleed out of their container

- correct alignment of action button icons

- improve layout of comments form on mobile

- prevent last status bar label from overlapping content and creating

- hyphenate all submissions table columns containing long worded items

- improve layout of submission action links (delete & edit in the top right corner)
