### ISSUE TITLE
Project detail page in progress state

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1379]
- [ ] Template updating to reflect the design (contracts subheading within supporting docs sidebar) 
- [ ] PAF block moved to side bar 
- [ ] RFP block added 
- [ ] Applicant can only see proposal and contracts

**Comment by fourthletter** [comment]
✔Template updating to reflect the design (contracts subheading within supporting docs sidebar)
✔PAF block moved to side bar
✔RFP block added

Applicant can only see proposal and contracts, but can NOT open. Applicant clicks on proposal or PAF and gets 403 Forbidden.

![Screenshot 2019-09-11 at 2 03 50 PM](https://user-images.githubusercontent.com/20019656/64725439-96b8e180-d4a2-11e9-9364-74ba4bdb3ecc.png)
