### ISSUE TITLE
Allow ordering of statuses in the update status form on submissions

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1407]
Now the statuses are sorted be the machine name (key) of the status, e.g "post_review_discussion". This looks very arbitrary to a human.

The overall goal is to have the first option be the most common one and the rest to be in some logical order.

Would it be possible to get the status in the same order they are set in "transitions" for each status? Then we could manually order them there to have them in the most social order, I think they already are in decent shape for that.

https://github.com/OpenTechFund/opentech.fund/blob/3d2e02a16e38894282ebf2f5f79eab405a61c784/opentech/apply/funds/workflow.py#L194-L200

The default now is almost never the right one now so if staff is a bit too quick the wrong status is often set.

**Comment by frjo** [comment]
@Parbhat @todd-dembrey Any good ideas on this?

**Comment by Parbhat** [comment]
@frjo Django fsm's method `get_available_user_FIELD_transitions` return transitions [sorted](https://github.com/viewflow/django-fsm/blob/c86cd3eb949467626ffc68249ad001746333c38e/django_fsm/__init__.py#L382) by transition name. For custom order, we can sort it again [here](https://github.com/OpenTechFund/opentech.fund/blob/3d2e02a16e38894282ebf2f5f79eab405a61c784/opentech/apply/funds/forms.py#L29). It will need an `order` with value say 3 to each phase dictionary like:

```python
    {
        'internal_review': {
            'transitions': {
                INITIAL_STATE: 'Screening (back)',
                'post_review_discussion': 'Close Review',
            },
            'display': 'Internal Review',
            'public': 'OTF Review',
            'stage': Request,
            'permissions': default_permissions,
            'order': 3,
        },
    },

```

Based on the value of the order for each phase we can update the status form choices list.

**Comment by frjo** [comment]
@saoun @fourthletter This is not something OTF has asked for but I believe it has been a problem non the less.

The issue is the order that the statuses are listed in the "Update status" form on submissions. The one OTF staff use every time a submission need to change state.

I believe there would be less mistakes if the first status is the most common one and the rest follow a logical order.

All the workflows with states and transitions are setup in the workflow.py file like this:

https://github.com/OpenTechFund/opentech.fund/blob/fe9bab2040478a1cca4d116082a6712b32ba0812/opentech/apply/funds/workflow.py#L191-L817

The PR I created sorts the status popup meny the same way the status is listed in "transistion" for each status.

I have ordered the transitions in a way that look good to me but please have a look and see what you think.

You test on the test site at https://test-apply.opentech.fund

**Comment by saoun** [comment]
I think this works on my end. Just tested. But since I'm not the most familiar with the flow of an application right now, better for @danblah or @fourthletter to check also
