### ISSUE TITLE
Modal Form Inputs are Missing

### ISSUE THREAD

**Issue by ghickman** [OpenTechFund/opentech.fund#1411]
The form modals we use in various places (Submission, Project, etc) have no UI elements for file pickers or checkboxes:

![](https://cl.ly/4c5265f00962/Image%202019-08-13%20at%202.31.45%20pm.png)

**Comment by chris-lawton** [comment]
The site uses custom checkboxes/radios/inputs but for them to work they require the correct markup and classes to be in place. 

An example of a file input can be seen on https://apply.opentech.fund/rapid-response-fund/ (scroll down to 'upload'). Inspecting it there are some additional classes on the containing element `form__group form__group--file` and also on the label `form__question form__question--multi_file_field multi_file_input`. These are also used by the JS to list out the uploaded documents and their file size. 

So i think the work here is around adding those classes in `delegated_form_base.html`.
