### ISSUE TITLE
Comments can't be edited

### ISSUE THREAD

**Issue by saoun** [OpenTechFund/opentech.fund#1413]
As submitted by one of our partners:

Steps to reproduce:
1) Create a comment
https://apply.opentech.fund/apply/submissions/3851/#communications  
2) Click on "Edit"
3) Observe that nothing happens as there is no target in the link.
```
<a class="link link--edit-submission is-active js-edit-comment" href="#">
Edit
<svg class="icon icon--pen"><use xlink:href="#pen"></use></svg>
</a>
```

To resolve: If editing is not supported, remove "edit" options from the UI, if it is supported, add in the appropriate link target.

**Comment by saoun** [comment]
maybe related to this? https://github.com/OpenTechFund/opentech.fund/issues/1228

**Comment by frjo** [comment]
It's an ajax function so it needs no href, but it do requires a JavaScript file. That files was by mistake only added for admins and staff. I have created a PR to add it for everyone.

Please test it on test and if it works for you as well we can deploy it to live.

**Comment by saoun** [comment]
Looks like it's working on my end!
