### ISSUE TITLE
Table formatting do not display in DIFP proposal

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1419]
Hello! It's been while, I'm here to report a new bug.

- Di
- Title of submission (app URLs alone are OK): https://apply.opentech.fund/apply/submissions/4854/

**Describe the bug**
Please look at section "Milestones and dates" -- table on application does not display. Please click on the edit function to see what the applicant created.

**To Reproduce**
1. Go to https://apply.opentech.fund/apply/submissions/4854/
2. Scroll down to 'Milestones and dates'

**Expected behavior**
Table formatting should display.

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff
- Applicants
- Reviewers

**Screenshots**
![image](https://user-images.githubusercontent.com/20019656/63118566-2040c680-bf6c-11e9-9275-27aa1ac271ed.png)

**Comment by frjo** [comment]
This is one complicated table. The code start of like this, and that before any content:

```
<div dir="ltr" style="margin-left: 0pt;" align="left">
<table style="border: none; border-collapse: collapse;"><colgroup><col width="49" /><col width="388" /><col width="15" /><col width="12" /><col width="11" /><col width="12" /><col width="14" /><col width="12" /><col width="11" /><col width="12" /><col width="13" /><col width="21" /><col width="22" /><col width="24" /></colgroup>
<tbody>
<tr style="height: 20pt;">
<td style="vertical-align: bottom; background-color: #d9d9d9; padding: 2pt 2pt 2pt 2pt; overflow: hidden; overflow-wrap: break-word; border: solid #000000 0.75pt;" colspan="2" rowspan="2">
<p dir="ltr" style="line-height: 2.4; text-align: center; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 10pt; font-family: Arial; color: #000000; background-color: transparent; font-weight: bold; font-style: normal; font-variant: normal; text-decoration: none; vertical-align: baseline; white-space: pre-wrap;">
```

A lot of that code is cleaned by the WebApp for style and security reasons. All the styles are removed e.g.

If we:

* add 'col' and 'colgroup' to BLEACH_ALLOWED_TAGS 
* add 'width', 'colspan' and 'rowspan' to BLEACH_ALLOWED_ATTRIBUTES

It will start to look like something and be barely readable.

To get it to look as intended we would need to:

* add 'col' and 'colgroup' to BLEACH_ALLOWED_TAGS 
* add 'style', 'width', 'colspan' and 'rowspan' to BLEACH_ALLOWED_ATTRIBUTES
* add 'background-color', 'white-space', 'padding', 'border', 'overflow', 'overflow-wrap', 'vertical-align', 'text-align', 'font-weight' etc. to BLEACH_ALLOWED_STYLES

In my opinion this kind of complicated data belongs in an attached PDF. But if you want to allow this it's easy to change.
