### ISSUE TITLE
Project List View 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1424]
'All' Projects view `/projects/all/`

- Columns
    - title
    - status
    - lead
    - fund
    - end date
    - Last Payment request
    - Fund allocation - display "{amount paid} / {total allocated}"
- Default ordering: End Date ascending
- Orderable by:
    - Title
    - Status
    - lead
    - Fund
    - Last Payment Request
    - End Date
    - Fund allocation -> Amount Paid (% of total)
- Filterable by:
    - Status
    - lead
    - Fund
- Empty Text: No Projects Available
- Link title to project page

-  #1340 - Update OTF dashboard table to link to this page when performing ordering/filtering

**Comment by fourthletter** [comment]
All acceptance criteria visible and functional during test. Thanks! 💥

The default ordering was not by End Date ascending, but was grouped by (1) fund then (2) end date ascending. This should be fine. Thank you.
