### ISSUE TITLE
PR List View 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1425]
`/projects/payment-requests/all`
- Includes the following columns
    - Project
    - Amount Requested
    - Status
    - Date
    - Fund
- Filterable by: 
    - project
    - status
    - fund
- Default ordering: Date Ascending
- Orderable on:
    - date
    - amount
- link row to project page- anchored on PR block
- Empty Text: No Requests Available

- Update dashboard link from PR summary table

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Thanks.

My All PR List Page was different wording than above criteria. Also, the default ordering is descending, list starts with latest date then goes backwards. This is okay, these are superficial features. Thanks.

![image](https://user-images.githubusercontent.com/20019656/66438083-98ba8580-e9f9-11e9-9802-518b02af613d.png)

**Comment by todd-dembrey** [comment]
@fourthletter We made some changes to the headings as part of a UX review. thanks for the feedback.
