### ISSUE TITLE
Project Overview page

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#1429]
`/projects/`
- [ ] Accessible by staff only
- [ ] Includes Project Status summary block (see submissions page for example)
    - Link to  all projects prefiltered on status
![image](https://user-images.githubusercontent.com/6338661/63760847-fff00080-c8b7-11e9-9038-700a1ef71dd1.png)

- [ ] Includes Projects summary table - as per Project list view
    - limit 10
    - link "all projects" to project list view
- [ ] Includes PR summary table - as per PR list view
    - limit 10
    - link "all payment requests" to PR list view 
- [ ] Add `Projects` to the main nav linking to this page

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Thanks! 💥
