### ISSUE TITLE
Attachment function associated with several funds are unhappy

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1439]
- Account name or name of person: Di
- Any personally identifying information: I have black hair
- Title of submission: Issue occurring in different funds and fellowship applications:
1) https://apply.opentech.fund/apply/submissions/4565/#submission-details 
2) https://apply.opentech.fund/apply/submissions/4869/ 

**Describe the bug**
1) In https://apply.opentech.fund/apply/submissions/4565/#submission-details , applicant uploaded multiple copies of the same documents. 

2) In https://apply.opentech.fund/apply/submissions/4869/ and several other DIFP proposals are unable to upload more than ONE document. 

**Expected behavior**

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff
- Applicants
- Reviewers

**Screenshots**

**Desktop (please complete the following information):**

**Comment by frjo** [comment]
@fourthletter 
1. The file upload widget is primitive and should be replaced with something more user friendly but it does list the files being uploaded.
2. There are one "File field" and one "Multiple File field" available when you create application forms. The person that created the DIFP forms used the first that only allows single file uploads. Change it to "Multiple File field" if you want users to be able to upload multiple files.

**Comment by fourthletter** [comment]
@frjo Thank you for addressing these concerns. I will take care of adding multiple file fields for DIFP and delete the extra uploaded materials that derived from the primitive widget.

**Comment by fourthletter** [comment]
@frjo I added the multiple file fields to DIFP. However, proposals have already been submitted by applicants. Does this mean the multiple file fields will not be available to applicants that have already submitted applications? https://apply.opentech.fund/admin/funds/applicationform/edit/60/

**Comment by frjo** [comment]
@fourthletter Yes, the form as it was when the application was submitted is stored on each submission.

This is what allows you to edit the form at any time without destroying already submitted application. Only application submitted after the change are effected.

**Comment by fourthletter** [comment]
closing this issue because problem is addressed by #1440
