### ISSUE TITLE
As a manager, ability to undo previous actions in a workflow or on content, or revert back to previous states for proposals

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1449]
- Account name or name of person: Di
- Any personally identifying information: I own a parrot
- Title of submission (app URLs alone are OK):

**Is your feature request related to a problem? Please describe.**
As a manager, ability to undo previous actions in a workflow or on content, or revert back to previous states for **proposals**. Related to #348 

**Is your feature request related to an existing functionality? Please describe.**
Staff is able to revert status in concept note, but not proposal stage.

**Describe the solution you'd like**
Staff needs to revert:
Final determination OR Accepted --> Ready for Final Determination
Ready for Final Determination  --> Ready For Discussion
Ready For Discussion  --> Advisory Council Review
Advisory Council Review --> Ready For Discussion
Ready For Discussion --> OTF Review
OTF Review --> Proposal Received

**Describe alternatives you've considered**
An alternative is remove restrictions for core functionalities like sending determinations from statuses. Staff member should be able to send a determination (need more info, dismiss, accept) in ANY status.

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff

**Comment by frjo** [comment]
* Final determination OR Accepted --> Ready for Final Determination
    * Not possible without bigger changes. 
* Ready for Final Determination --> Ready For Discussion
    * Will add in new PR
* Ready For Discussion --> Advisory Council Review
    * Already possible
* Advisory Council Review --> Ready For Discussion
    * Already possible
* Ready For Discussion --> OTF Review
    * Already possible
* OTF Review --> Proposal Received
    * Already possible

@fourthletter From what I can see most of these are already possible. It does not work for you? Can you giva a URL to a submission that has the problem?

**Comment by fourthletter** [comment]
@frjo Thank you for identifying it's **Ready for Final Determination --> Ready For Discussion**

It's particularly difficult for staff to navigate because the status change option is misleading.

**Comment by frjo** [comment]
If they are misleading something needs to change. Create a new issue where you describe the problem. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo I sent you four applications on slack that need to go back to AC from ready for final determination. The person moved it in error.

**Comment by fourthletter** [comment]
I found a few bugs related to reverting back to previous states for proposals:

_Example1: https://apply.opentech.fund/apply/submissions/5213/_
Example 1 is a test created on the live site. The submission is currently in the "Ready In Final Determination" but there isn't an option to revert backwards. 
[ ] Go to https://apply.opentech.fund/apply/submissions/5213/
[ ] Click on update status
[ ] User could only accept or dismiss. 
[ ] User should be able to revert back to previous status.

_Example2: https://test-apply.opentech.fund/apply/submissions/18/#submission-details
Example3: https://test-apply.opentech.fund/apply/submissions/88/_
Examples 2 & 3 are from the test site. These submissions could be reverted. However, there are two "Ready for Discussion" statuses so it's jump back further than the previous status.

**Comment by frjo** [comment]
@fourthletter 

> Example1: https://apply.opentech.fund/apply/submissions/5213/

Yes, this is on live where this code is not yet running.

> Examples 2 & 3 are from the test site. These submissions could be reverted. However, there are two "Ready for Discussion" statuses so it's jump back further than the previous status.

I had put in the wrong state, post_proposal_review_discussion instead of post_external_review_discussion. I have updated the pr and pushed it out to test so now it should work.

> Images appeared when I attempt to progress to a different status in above tests:

You are referring to the error messages, red with white text?

This I can not reproduce. Can you see if @saoun see this as well?
