### ISSUE TITLE
Spam protect the newsletter form to avoid unneeded log warnings

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1454]

**Comment by frjo** [comment]
Test this on the test site, check so the newsletter signup form still works.

The javascript should stop most spam boots and we can avoid the stream of error messages that are coming in.

**Comment by fourthletter** [comment]
I signed up for a newsletter on test site and live site. I haven't received confirmation from either sites. 

I did not receive any errors when I signed up for the newsletter on the test site. I think we should deploy.

I received this bar on the live site: https://apply.opentech.fund/apply/submissions/4962/#submission-details
