### ISSUE TITLE
Status Workflow Bar Converted to Old Workflow 

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1459]
- Account name or name of person: Di
- Any personally identifying information: I like long walks on the beach

**Describe the bug**
Submissions below are tests on the live webapp. The workflow status bar is different than the status bar that appears on other submissions. I'm unsure the cause of this behavior.

Examples:
Test 1: https://apply.opentech.fund/apply/submissions/4964/
Test 2: https://apply.opentech.fund/apply/submissions/4964/

**To Reproduce**
1. Go to Test 1: https://apply.opentech.fund/apply/submissions/4964/ and Test 2: https://apply.opentech.fund/apply/submissions/4964/

<img width="1254" alt="Screen Shot 2019-08-23 at 4 35 09 PM" src="https://user-images.githubusercontent.com/20019656/63622216-12222400-c5c4-11e9-8489-9545060ae397.png">

**Expected behavior**

<img width="1250" alt="Screen Shot 2019-08-23 at 4 34 25 PM" src="https://user-images.githubusercontent.com/20019656/63622203-059dcb80-c5c4-11e9-885e-cc1a835c9ea6.png">

**Affected roles**
- Staff

**Screenshots**

**Comment by frjo** [comment]
@fourthletter Staff and applicants see the states differently. Both of these you have submitted.

Two me they both look exactly like all other proposals in that round.
