### ISSUE TITLE
Preserve URL during Login

### ISSUE THREAD

**Issue by tarakiyee** [OpenTechFund/opentech.fund#1468]
When clicking on a Webapp link while logged out, I get redirected to the login page. Upon logging in, instead of being redirected to the original URL, I always get redirected to the dashboard. I would then need to follow the URL again to access what I needed to. 

I would like to be able to go to the URL directly after logging in. 

Priority: Medium 

**Affected roles**
- Staff
- Applicants
- Reviewers
- Partners

**Ideal deadline**
April 25th

**Comment by frjo** [comment]
@tarakiyee Can you post an example url that you try to access where this happens?

Redirect after login should already work but maybe some urls have a bug.

**Comment by frjo** [comment]
I see now that redirect works for normal logins but not for Google logins that staff uses. This is a bug and I have created a PR to fix it.
