### ISSUE TITLE
CPF applications shows months instead of weeks

### ISSUE THREAD

**Issue by tarakiyee** [OpenTechFund/opentech.fund#1484]
**Describe the bug**
CPF applications show "X Months" under project duration on the view submission page but in the application, the project duration should be in weeks. 

**To Reproduce**
Check this link for example: https://apply.opentech.fund/apply/submissions/4954/

**Expected behavior**
The view submission page should show the project duration is actually in weeks. 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff
- AC 

**Desktop (please complete the following information):**
 - OS: Chromebook

**Comment by tarakiyee** [comment]
Actually on further investigation, it appears the system has created two CPF forms, and the latter one was in months, rather than weeks. I've changed it, but can we check the database to make sure there is consistency?

Also, does the system create a new form for every round? I don't understand this bit. 

Original form: https://apply.opentech.fund/admin/funds/applicationform/edit/55/
"New" form: https://apply.opentech.fund/admin/funds/applicationform/edit/56/

**Comment by frjo** [comment]
@tarakiyee Yes, the system clones the forms that are attached to the fund when you create a new round.

If you want to change a form for a specific round you change the form attached to that round.

If you want to change the form on all future rounds you change the form attached to the fund.

On https://apply.opentech.fund/admin/funds/round/ you have links to the forms attached to each round.

On https://apply.opentech.fund/admin/funds/applicationform/ where you see all application forms you have a filter top right to help you find the form you want.

**Comment by tarakiyee** [comment]
Thank you for the clarification. 

Can we just go through the database of CFP applications, and make sure for consistency's sake, that everything is in weeks?

**Comment by frjo** [comment]
@tarakiyee The easiest and quickest way is to open up all the CFP application forms in browser tabs and check/update them.
