### ISSUE TITLE
Improve memory usage in SubmissionOverviewView, SubmissionListView and SubmissionsByRound

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1495]
https://scoutapm.com/apps/28725?time=d:1-day&section=memory

**Comment by frjo** [comment]
@Parbhat Do not know how much can be done but it would be good if you can take a look.

**Comment by frjo** [comment]
api_views.SubmissionList and SubmissionListView could also be worth looking at.

**Comment by Parbhat** [comment]
@frjo I will check these views if we can reduce the DB queries etc. to improve performance.
