### ISSUE TITLE
Word Limits on Applications

### ISSUE THREAD

**Issue by tarakiyee** [OpenTechFund/opentech.fund#1500]
We often get proposals that are way too long. We would like the ability to set word count limits on certain application fields. 

**Priority**
- High (keeping you from completing day-to-day tasks)

**Affected roles**
- Staff
- Reviewers
- Partners

**Comment by fourthletter** [comment]
Related to #577 #705

**Comment by danblah** [comment]
Closing, dup of #577 #705
