### ISSUE TITLE
Note Section in Detailed View Does Not Like Me

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1503]
{\__/} 
( • . •)      
/ >🐞   - Any personally identifying information: I found a bug
- Title of TEST submission: https://test-apply.opentech.fund/apply/rounds/824/?submission=81

**Describe the bug**
Note section in detailed view won't let you submit content. 

**To Reproduce**
1. Go to 'detailed view'
2. Click on 'Notes'
3. Enter information and try to 'submit'
4. See error :(

**Expected behavior**
Information should be saved in comment section.

**Priority**
- Low priority (annoying, would be nice to not see) --> I could use the comment section in the submission directly.

**Affected roles**
- Staff

**Screenshots**
![image](https://user-images.githubusercontent.com/20019656/64645117-2ba7d600-d3e2-11e9-878c-22ff17093ac1.png)

**Comment by saoun** [comment]
Bug still there. Behavior:

- Write a comment, hit submit, and get this error: "Unexpected token < in JSON at position 0"
- Comment doesn't appear
- After refreshing the page, the comment appears

![image](https://user-images.githubusercontent.com/11432628/65056989-e0407b00-d93f-11e9-82fc-877d2f8cf597.png)

This only happens to new comments. If you edit an existing comment, the error doesn't show

**Comment by saoun** [comment]
Other UI comment: 

When clicking on "Edit," it's very hard to tell that the place to edit is the submit box, as opposed to the comment box (where the comment already is). Everything greys out and it looks like the page freezes. 

Is it possible to make the edit within that comment box itself where the comment already is, as opposed to sending the user back to the submit box? It would be way more intuitive.

**Comment by frjo** [comment]
@saoun The error you are seeing is different from the one @fourthletter reported. I will add a separate issue for that one.

Regarding the UI, please add an issue about it. This is part of the react app (javascript) and I do not know much about how it works.

**Comment by frjo** [comment]
https://github.com/OpenTechFund/opentech.fund/issues/1527

**Comment by saoun** [comment]
Great, thanks @frjo. Will add a ticket for the UI

**Comment by fourthletter** [comment]
@frjo Thank you for fixing bug, feature worked during test.
