### ISSUE TITLE
Restore determination draft feature

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1523]
This bug was introduces when we implemented the multiple proposal form feature, see links below.

If I revert the class "ConceptDeterminationForm" to just "pass" the draft feature works again.

https://github.com/OpenTechFund/opentech.fund/commit/7f239ccbf3b081e3ac1f3d6976b3f71ea91c9cd5

https://github.com/OpenTechFund/opentech.fund/blob/1a7645bb449c3b67a17005db48efda5f3da5a6cb/opentech/apply/determinations/forms.py#L362-L384

**Comment by frjo** [comment]
@Parbhat Could you take a look at this? I have tracked down the reason but I do not see how to fix it.

**Comment by fourthletter** [comment]
This could be unrelated, but the batch action does not function as well.

**Comment by Parbhat** [comment]
@fourthletter Bug in batch action is related to this issue. @frjo has tested the batch fix on PR #1531.
