### ISSUE TITLE
Production settings cause static files to be stored in /staticfiles/, not /static/

### ISSUE THREAD

**Issue by maxpearl** [OpenTechFund/opentech.fund#1561]
A deployment issue:

Using DJANGO_SETTINGS_MODULE=opentech.settings.dev creates static files in the expected directory defined by base.py: /static/, however, when using DJANGO_SETTINGS_MODULE=opentech.settings.production, `python manage.py collectstatic` creates static files in a directory called /staticfiles/.

**Comment by frjo** [comment]
This is due to the ”django_heroku” library that via `django_heroku.settings(locals())` in the production.py file among other things sets `STATIC_ROOT` so it points to `/staticfiles/` dir.

I think the solution is to create at least two production settings files, one for Heroku and one generic.
