### ISSUE TITLE
Change Determination Text to "Need More Information"

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#1582]
**Is your feature request related to a problem? Please describe.**
Applicants receive determination letters from OTF with the sub-heading "Need More Info." This is not clear to many applicants and text should be changed to "Need More Information."

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff
- Applicants

**Comment by frjo** [comment]
@fourthletter  It's "Needs more info" (with an s on needs). Should it be "Need More Information" or "Needs More Information"?

**Comment by fourthletter** [comment]
@frjo please use "More Information Required"

**Comment by saoun** [comment]
Looks good on my end
