### ISSUE TITLE
As a manager, lets automate 'In Discussion' status once an application in 'Submit for review' is assigned reviewers or is reviewed

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#159]
Once any application or proposal receives two reviews it should be automatically reclassified as 'in discussion' if it is in the submit for review state.

**Comment by gibbsmaya** [comment]
Let's take this into discussions around potentially automating some status transitions. This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.
