### ISSUE TITLE
CSS - reduce font size of dashboard

### ISSUE THREAD

**Issue by saoun** [OpenTechFund/opentech.fund#1609]
Quick CSS request: could you please reduce the size of these 3 boxes + the font size to match the font size of the header? It's way too big now. 

![image](https://user-images.githubusercontent.com/11432628/67307063-8706d100-f515-11e9-9931-7d4640d28f13.png)

**Comment by frjo** [comment]
@saoun How about this?

![Skärmavbild 2019-10-23 kl  08 50 50](https://user-images.githubusercontent.com/191392/67365642-49846100-f572-11e9-98da-276068486e02.png)

**Comment by saoun** [comment]
@frjo Yes for the font of the text. 

- For the blue number, can you reduce it by almost half? Kind of like this. (The format isn't 100% correct from my image)

- And since the fonts will be reduced, the inside padding might need reducing as well. It's okay if the boxes are smaller with more margin between each box. 


![image](https://user-images.githubusercontent.com/11432628/67414863-83408080-f5e1-11e9-869c-be4edb7b6de3.png)

**Comment by frjo** [comment]
This is ok?

![dashboard_boxes](https://user-images.githubusercontent.com/191392/67470947-e4526d80-f64e-11e9-89f5-4cddcc5e9672.png)

**Comment by saoun** [comment]
Yes for the font size. A couple of more CSS fixes:

- Increase the margin/padding between each box (to about 3x the size now)
- Reduce the size of the boxes (less padding right) 
- Delete the "View" that appears when you hover the box. Instead, when a user hovers over the box, change the color of the entire box (to maybe grey or light blue), OR change the color of the text (like a hyperlink color change)

Thanks so much!

**Comment by frjo** [comment]
I have increased the margin between the boxes. That also makes each box smaller. They are spaced out on the available page width so that are get equal hight and width.

The "View" hover effect is a separate issue in my opinion, it's a style that is used in several places and if we should change it on all of them. Please add an issue about it if you want it done.

This will get deployed tomorrow morning.

**Comment by saoun** [comment]
ok great, will make another ticket. thanks!
