### ISSUE TITLE
Marking report as skipped 

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#1620]
- [x] OTF staff can mark any not-submitted report as "skip"

- [x]  Project can no longer submit a report for that period
- [x]  Report no longer appears above the reporting table for applicant
- [x]  Report appears in report table. date submitted => "Skipped"
- [x] OTF staff can "Unskip" a report 
- [x] Email is sent to applicant when a report is skipped or unskipped

**Comment by abigail-hampson** [comment]
Looks good, ready to go to test

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional. Thanks! 💥
