### ISSUE TITLE
Adjust frequency of reporting

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#1621]
- [ ] Default reporting frequency of 1 per month.
- [ ] Options:
* integer
* period => options = [ week, month ]

- [ ] Report required on same day each month or first available day prior e.g  30th February becomes 28th February

- [ ] configuration only available to OTF staff
- [ ] reporting frequency visible to applicant

- [ ] Changing the frequency only affects the next report. 
- [ ] only change the deadline of the next report if the new reporting period ends before the next reporting period
  * last report 3 months ago, new reporting 2 months => report due end of the reporting period month 
  * last report 3 months ago, new reporting 6 months => report due 3 months

- [ ] Applicants receive an email when the frequency is changed

**Comment by fourthletter** [comment]
I marked the acceptance criteria that are visible and functional below.

I've encountered two issues: 1) I'm unable to change the deadline or date that automatically generated after a project has been approved. 2) The verbiage about when a project ends or the "end date" designated in the box is incorrect, the project end date shouldn't be 2019-11-19.

- [X ] Default reporting frequency of 1 per month.
- [X ] Options:
* integer
* period => options = [ week, month ]
- [ X] Report required on same day each month or first available day prior e.g  30th February becomes 28th February
- [X ] configuration only available to OTF staff
- [X ] reporting frequency visible to applicant
- [X ] Changing the frequency only affects the next report. 

- [ ] only change the deadline of the next report if the new reporting period ends before the next reporting period
  * last report 3 months ago, new reporting 2 months => report due end of the reporting period month 
  * last report 3 months ago, new reporting 6 months => report due 3 months

**Does this mean I need to wait until the reporting period until I can change the deadline?**

- [ X] Applicants receive an email when the frequency is changed 

![image](https://user-images.githubusercontent.com/20019656/69065417-ba8e2b80-09ed-11ea-8325-d73f74fbf8ec.png)
