### ISSUE TITLE
OTF staff can edit a submitted report

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#1625]
- [x] Same form as creating a report
- [x] Cannot change privacy state of report
- [x] Staff edits create a new version

**Comment by todd-dembrey** [comment]
This is now on dev - the edit button should appear alongside submitted reports.

I feel the privacy change prevention makes sense but might not survive in practice. Lets review with OTF.

The only way to check the version is through uploading a file. The last number in the url should update when you re-submit.

**Comment by abigail-hampson** [comment]
All good, ready to go to test

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thanks! 💥
