### ISSUE TITLE
Report Page FE 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1643]
Includes:

- [x] Alert for reporting period at the top of the form 
- [x] Modal for saving as draft and confirming submission 
- [x] General FE tidy of form page

**Comment by abigail-hampson** [comment]
Just missing confirmation modals

**Comment by chris-lawton** [comment]
PR for confirmation modals: https://github.com/OpenTechFund/opentech.fund/pull/1678

**Comment by abigail-hampson** [comment]
Looks good, ready to go to test

**Comment by fourthletter** [comment]
All acceptance criteria are visible. Thanks! :boom:
