### ISSUE TITLE
Project Page FE 

### ISSUE THREAD

**Issue by abigail-hampson** [OpenTechFund/opentech.fund#1645]
Includes:
- [x] General update and tidy of FE styles 
- [x] Reporting table 
- [x] Past reports table 
- [x] Past reports shows a max of 8, clicking on the show more button shows 10 more

**Comment by abigail-hampson** [comment]
Looks good to me, can go to test

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional. Thanks! 💥
