### ISSUE TITLE
Remove code no longer needed from Django 2.1.x in ImageFieldBlock

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1650]
See comments in get_field_kwargs().

**Comment by frjo** [comment]
@Parbhat We can remove the get_field_kwargs() completely, can we not?

https://github.com/OpenTechFund/opentech.fund/blob/2ffd404d628ad4f255ac3892cef306980f6e4a4d/opentech/apply/stream_forms/blocks.py#L390-L395

**Comment by Parbhat** [comment]
@frjo Yeah, we can remove it now. Thanks for noticing
