### ISSUE TITLE
Set timezone to UTC to avoid summer time

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1652]

**Comment by frjo** [comment]
@todd-dembrey Any issues changing TIME_ZONE = 'Europe/London' to TIME_ZONE = 'UTC'?

**Comment by todd-dembrey** [comment]
We have `USE_TZ` set to True so all times are stored in the db as UTC anyway. I cant see an immediate issue with changing to UTC as the default timezone as it should be for display purposes

**Comment by frjo** [comment]
It's an issue when rounds close US East coast time. They differ an hour summer vs winter.

**Comment by fourthletter** [comment]
Please deploy! Thanks.
