### ISSUE TITLE
Order by last update added over 4s to the query time on SubmissionsTable views

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1665]
* Order by last update: 4800ms
* Order by submit time: 380ms

Seems like this is something that should be possible to optimise.

https://github.com/OpenTechFund/opentech.fund/blob/1dfe5f080432ed3af04d81dec3bc83341146d2f8/opentech/apply/funds/tables.py#L68

https://github.com/OpenTechFund/opentech.fund/blob/1dfe5f080432ed3af04d81dec3bc83341146d2f8/opentech/apply/funds/models/submissions.py#L142-L148

**Comment by frjo** [comment]
@Parbhat Can you take a look at this? It's not the query itself that is slow, only when you orderBy last_update it becomes slow.

Compare  "/apply/submissions/all/?sort=last_update" vs "/apply/submissions/all/?sort=submit_time"

**Comment by Parbhat** [comment]
@frjo Yeah, will work on it.
