### ISSUE TITLE
As a manager/reviewer, ability to "flag" applications for things like: out of remit; spam; testing; priority; read later; assign to user; etc and then the ability to view/filter applications by these flags

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#172]

**Comment by danblah** [comment]
Related, maybe duplicates #328 and #548

**Comment by gibbsmaya** [comment]
This is planned to be covered (somewhat) in the work we are doing in the Winter 2019 Sprints. Adding to project board and can split out tickets for areas that are left uncovered once work is complete.
