### ISSUE TITLE
Update Django to 2.2.x and Wagtail to 2.7.x

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1728]
Django 2.2.x is a LTS (Long Term Support release) so it's something we can stick with until Q1 2022 if we want.

Wagtail 2.7.x is the version that supports Django 2.2.x.

There was a security update on 2019-12-18 that patched a serious issue in the password reset function. This is the main reason we want to push out Django 2.2.x a soon as possible since it has a fix for that.

Until the fix is deployed we have blocked access to the password reset function for normal users.

**Comment by frjo** [comment]
@danblah @fourthletter @saoun Would be really doom if you could do some testing on this.

These updates touch more or less everything. So I recommend to test things like:

1. Submit an application as an applicant, both logged in and not logged in.
2. Administer the new application as staff, writing reviews, determinations etc.
3. Review applications as a reviewer.
4. Edit/resubmit an application as a applicant.
5. Administer application forms and rounds in wagtail admin.

Wagtail admin has got a facelift, some good improvements to the UI I think.

**Comment by fourthletter** [comment]
The majority of the above tests work. Number 5: Administer application forms and rounds in wagtail admin presents several issues.

[ ] I was unable to add a new round. Go to Add Round and click on any Fund like  [Fund] Core Infrastructure Fund. I get an internal server error 500.

[ ] Attempting to edit a Fund was presented an error.

I can successfully copy a Fund.

**Comment by saoun** [comment]
@frjo, same comments as @fourthletter: tests 1 to 4 worked fine on my end, but 5 failed in the same spots (500 errors on adding rounds etc.

**Comment by frjo** [comment]
@saoun @fourthletter A change in Wagtail 2.7 I had missed, fixed now. Creating rounds seems to work now.
