### ISSUE TITLE
CSS - reduce size of project form

### ISSUE THREAD

**Issue by saoun** [OpenTechFund/opentech.fund#1730]
referring this project: https://apply.opentech.fund/apply/projects/1/

can we reduce the entire size of the box "Supporting documents" to match the one that's "Actions to take"? 

Everything from font size, to padding, margins, etc. so they match in design.

![image](https://user-images.githubusercontent.com/11432628/71198367-9c705100-2261-11ea-80b5-f3867ac39d8c.png)

**Comment by saoun** [comment]
Perfect, thanks!

**Comment by frjo** [comment]
@saoun There is no need to close issues that you have approved. Github automatically closes them when the related pull request is merged.
