### ISSUE TITLE
Remove sensitive information from determination and comments e-mails

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1731]
E-mails should be notifications, for full information users need to go to the web app.

**Comment by frjo** [comment]
I have removed all the extra fields from the determinations e-mails, leaving only the determination message with a link to the full determination.

Removed the comment message from the comment e-mails to applicants. Only a notification about new comment on submission x with a link now.

**Comment by saoun** [comment]
Tested with red team, and works. Ready for deployment
