### ISSUE TITLE
Rename opentech django app to hypha

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#1755]

**Comment by saoun** [comment]
Isn't this the same as https://github.com/OpenTechFund/opentech.fund/issues/1544?

also related to https://github.com/OpenTechFund/opentech.fund/issues/1277

**Comment by frjo** [comment]
Yes, duplicate. Closing. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
