### ISSUE TITLE
Create a stand alone page/form that allows someone to sign up to the OTF-Announce list (google group) and Newsletter (mailchimp)

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#181]
- [ ] Allow team to edit the page title and description
- [ ] Collect email, first name, and last name (only email required)
- [ ] Two check boxes, one for OTF Announcements and another for Daily Newsletter
- [ ] On submit, send an email confirmation with link for confirm. On confirm, direct add to Google and Mailchimp API's.
- [ ] If no confirmation after 48hrs, send an email saying the request has been disregarded, and to visit url if they'd like to try again, then disregard request.

**Comment by saoun** [comment]
@frjo im guessing this already exists?
