### ISSUE TITLE
Modify email template sent to individual reviewers when app is set to "council review"

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#182]
Dear reviewer,

A new [node:content-type] has been added to your review list:

Title: [node:title]
Link: [node:url]
Write a review: [site:url]node/add/concept-note-review?field_review_concept_note=[node:nid]

[If any nodes in their review list have 1 less reviews, display, else do not include]

And also, there are other application(s) on your list for review:
[list all applications in their list with 1 or less reviews]
* [Node:title]: [node:url]

[else]

This is the only application in your review queue! Well done and thank you <3

Here's some current numbers:

[number of reviews from users]: Total number of application reviews from you
[average rating from user reviews]: Your average application rating (on a scale of 0 to 5)
[total number of reviews]: The total number of application reviews
[total number of submission responses]: The total number of submission responses sent to applicants
[total number of concept notes] / [total number of proposals] / [total number of approved proposals]: That's the total number of concept notes received / proposals received / and proposals accepted to date
[total number of pending applications]: Total number of pending applications
[total number of dismissed applications]: Total number of applications we've dismissed :-/
[sum of amount field in all approved applications / sum of amount field in all applications]: That's the total amount of money we've awarded / and the total amount of funds requested of us in USD
Kind regards,
[App Lead]

**Comment by saoun** [comment]
@frjo what is the current email template? 

also, how easy is it to implement this now?

**Comment by frjo** [comment]
Current template: https://github.com/OpenTechFund/opentech.fund/blob/09c7aff7394252f6d395afeca5843a88bf927af3/opentech/apply/activity/templates/messages/email/ready_to_review.html#L1-L9

I think we should close this and concentrate on https://github.com/OpenTechFund/opentech.fund/issues/1491

The goal is to get reviewers to review their applications and I think the reminders is a better and cleaner way to do this.

**Comment by saoun** [comment]
sounds good. I'll close this. However, these stats and number listed in the proposed email template are important and it's something that the staff has asked for, for the AC review. I'll copy them over to a new open ticket
