### ISSUE TITLE
As an approved applicant, ability to "Request Payment" for an open contract assigned to me

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#185]
- [ ] Add two fields to an application in OTF extra info and display in the OTF info box (hide if empty): Contract/PO # and Fiscal Year
- [ ] Create a new content type, Payment request (see below for fields), enable revisions by default
- [ ] While an application is in the Open state (only available to a app that has been in approved), expose a "Request payment" button, that creates a new Payment request referenced to the application
- [ ] Allow anyone with edit permissions (team, owner, and others assigned via OTF extras) to create a new Payment request
- [ ] Create new workflow for Payment request type: Submit for review (initial after save), Approved (only set by team), Reimbursed (only set by finance user)
- [ ] Create a new finance role, which only has access to Request Payment content types in Approved or after.
- [ ] Create a "Status" tab for the proposal (/node/####/status), that displays a view listing all Payment requests, anyone with edit permissions can view. Fields: Submitted date[link to node], Approved date, Amount, Submitted by, Approved by, Current state
- [ ] Add to the OTF info box (hide if empty): Payment requests: ## / ## (Completed / Submitted) and Balance: $$$$ / $$$$ (Total amount completed / Budgeted)
- [ ] Create #notify and email rules for state changes and actions (see below)

**Comment by danblah** [comment]
Closing, being done with current sprints.
