### ISSUE TITLE
As an applicant/reviewer, ability to reply to comment and determination notifications via email/slack/signal (with attachments)

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#233]
* Allow applicant to reply via email to a submission response email, converting their reply to a comment in the WebApp for the appropriate application
* Allow anyone with edit access to begin a comment on an application/submission response/review, with email notifications sent out, and ability to reply comment via email
Allow known emails of editors for open proposals to create status reports and payment requests from email

**Comment by fourthletter** [comment]
Similar to #292 in Q3

**Comment by saoun** [comment]
closing this as it is relevant to this https://github.com/OpenTechFund/opentech.fund/issues/292
