### ISSUE TITLE
We can't access attributes of an object inside blocktrans

### ISSUE THREAD

**Issue by sks444** [OpenTechFund/opentech.fund#2606]
At many places in our templates we are using dotted expressions inside `{% blocktrans %}{% endblocktrans %}`.

One example is at the [base template of email](https://github.com/HyphaApp/hypha/blob/923f0131c2ea9c20ebad4a1cded353beed07efaa/hypha/apply/activity/templates/messages/email/base.html?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L12).

That doesn't work.

We need to bind the expression to a local variable for use within the translation block. 

E.g.

```html
{% blocktrans %}Kind Regards,
The {{ ORG_SHORT_NAME }} Team

-- 
{{ ORG_LONG_NAME }}
{{ PUBLIC_SITE.root_url }}{% endblocktrans %}
```

Should be:
```html
{% blocktrans with root_url=PUBLIC_SITE.root_url %}Kind Regards,
The {{ ORG_SHORT_NAME }} Team

-- 
{{ ORG_LONG_NAME }}
{{ root_url }}{% endblocktrans %}
```

See: https://stackoverflow.com/a/9007830

cc: @frjo

**Comment by frjo** [comment]
@sks444 Thanks for alerting me of this, will make the needed changes.
