### ISSUE TITLE
The ability for a user to create a custom list of submissions they have access to by providing an option for them to flag/bookmark/follow it on the submission page. this list should show up in a new list at the bottom of their dashboard.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#269]

**Comment by fourthletter** [comment]
[] Staff could use this feature to create one link for review calls. 
[] Submissions are easier to read when they're grouped together.
[] Staff will NO longer need to change the status of a particular application several times back and forth during the course of several weeks. The state "Ready for Discussion" is significant for the workflow status and not a designation for review calls.

**Comment by fourthletter** [comment]
Related to #1177

**Comment by fourthletter** [comment]
@frjo The flags worked and it showed up as a list under my dashboard.

[ ] Can I create a url form this list of flagged items?
[ ] Can I flag multiple items, like how I can assign multiple reviewers?
[ ] I do not see the list for "staff flagged"

**Comment by frjo** [comment]
@fourthletter  Staff flagged items show at the bottom of https://test-apply.opentech.fund/apply/submissions/.

You can also see them here https://test-apply.opentech.fund/apply/submissions/flagged/staff/. If there are more than five (5) items there will be a "See all" link on the submissions overview, just as for the other tables.

You can flag as many items as you like, no limits. But there are only two *types* of flags as of now.

1. Each staff user can have a private list of flagged item.
2. A "staff flagged" list that is common for all staff.

**Comment by fourthletter** [comment]
Could you please change staff flagged list title to "Team Action List." Please deploy feature. Thanks! 

During test...
[ ] User can see "my list" displayed in dashboard and "staff list" in submissions tab. 
[ ] Other team members can see the "staff" list as well.
