### ISSUE TITLE
As a manager/reviewer, a unique view for rounds that replaces the need of manual google doc curation

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#274]

**Comment by frjo** [comment]
@danblah What information is needed on this view? What tasks is it the manger does in the Google doc today?

**Comment by danblah** [comment]
See this: https://docs.google.com/document/d/1sF1jW82eG4WOGVylHxDAWlpfHZhIgcq5tKYIhn_j3dE/edit#heading=h.3sfh9f10soud (lemme know if you can't view)

**Comment by frjo** [comment]
Have asked for permission now in Google docs.

**Comment by danblah** [comment]
added @otf account, dm me if you've another account to add.

**Comment by gibbsmaya** [comment]
@frjo to keep you in the loop, this is one of the things we will be exploring with the otf team next week so we will pick this up as a task.

**Comment by tarakiyee** [comment]
I suggest replacing this workflow with "review slates", so a manager can compile a subset of applications (Out of Remit, ready for review, etc), and push those to the team to review either at their own leisure or during a review call. Those review slates would allow for collaborative note taking, and a "next step" field, which would record the decision of the review (which would be send a determination, or schedule a call, etc). For the "ready to review" slates, there should be a way of highlighting which application is being actively discussed at the moment.

**Comment by gibbsmaya** [comment]
This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.
