### ISSUE TITLE
External Reviewers list needs to comes from the fund's reviewer

### ISSUE THREAD

**Issue by sandeepsajan0** [OpenTechFund/opentech.fund#2783]
External reviewers list shows all reviewers to select for any submission. Because its queryset is getting all [reviewers here](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/forms.py#L194).

<img width="765" alt="image" src="https://user-images.githubusercontent.com/23638629/159711839-28cc45ee-342a-4240-8d85-2e68689068c3.png">

But it should show the reviewers who have added to that particular type of fund(like only Reviewer2 in this case).
 
<img width="942" alt="image" src="https://user-images.githubusercontent.com/23638629/159712517-d3c0f345-78d6-41ed-b5f5-bf0a3dda3f01.png">

@frjo @sks444 @fourthletter What are your thoughts on this?

**Comment by frjo** [comment]
Thanks for bringing this up.

As of now, the selection of reviewers staff make on the Fund/Lab gets automatically assigned to all submissions for that Fund/Lab.

On each individual submission, the form you show above, staff can update who is assigned to that submission.

I think it therefor makes sense to show all reviewers in that form.

In practice the form is used when:
* staff has forgotten/not understod that reviewers should be assigned on the Fund/Lab
* a new reviewer has signed up and staff want that person to review some existing submissions.

What do other people think? @fourthletter ?

**Comment by fourthletter** [comment]
> In practice the form is used when:
> staff has forgotten/not understod that reviewers should be assigned on the Fund/Lab
> a new reviewer has signed up and staff went that person to review some existing submissions.

This functionality is useful for a staff to quickly identify which reviewers are associated with their fund, this prevents them from having to comb through a long list of ALL individuals associated with a role.

## Next Steps:
We could research how to similarly manage individuals associated with the 'Partner' role

**Comment by frjo** [comment]
Then it is decided, the reviewers popup on submissions should be filtered by the reviewers selection on the Fund/Lab. Let's implement it.

No research needed for how to implement this for partners, we just do exactly how it is done for reviewers. Please add a separate issue for that.

**Comment by fourthletter** [comment]
Related to improve search for individuals on partner, reviewer list https://github.com/HyphaApp/hypha/issues/2868

**Comment by fourthletter** [comment]
Managers currently associate reviewers with a Fund/Lab/Round via the WagTail Admin. This is where the segmentation occurs, not on the application interface. 

While it would be useful to segment or to have a more narrow list of reviewers to choose from on the application platform, the scope of this issue has not been fully thought out. I will close this issue for now. In the future we could potentially identify a use case based on research and a detailed approach to resolve this challenge.
