### ISSUE TITLE
As a manager, i need an easy way to track all set deadline dates given to an applicant or staff member

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#285]

**Comment by fourthletter** [comment]
Relates to #273

**Comment by frjo** [comment]
Deadlines should be added as metadata, similar to how meta categories are added.

@fourthletter There was talk about a number of different deadlines, can you please list them here.

**Comment by danblah** [comment]
Deadlines for, in order of importance to the team (criteria for meeting deadline):

* Response to determination (applicant submits communication or submission revision)
  * This would cover invite to proposal
* AC reviews (any two assigned AC members submit reviews)

* Team review assignment (two team members are assigned/self-assign to review)
* Team reviews (any two team members submit reviews)
* Determination (determination msg sent by lead/someone on the team)

These would ideally be something set by hitting a button in the "Actions to take" box. We'll need some interface for viewing/filtering deadlines and also creating actions on setting and deadlines passing.
