### ISSUE TITLE
As a manager, ability from a round overview page, to view all activity for applications in that round and to post comments related to the round a comment relating to a round, not specific to applications only

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#290]

**Comment by danblah** [comment]
Total number of applications, amounts requested, number of open applications, amount of funds approved, averages, etc, ability to view and filter associated applications on the round page as you can on the submissions tab, activity feed as you see on the submissions tab but only for those apps, ability to comment on the round generally, field that links to the external doc that is being used by the round lead to capture notes

**Comment by gibbsmaya** [comment]
@danblah this hasn't really come up in the work we have been doing over the last few weeks. The requirement always seems to have been that comments relate to a specific application. Can you please expand here on what the requirements is so I can assess whether we look to include it in Winder 2019 Sprints?
