### ISSUE TITLE
As a manager, the ability to customize available options from global fields when displayed on application

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#311]

**Comment by frjo** [comment]
@danblah @fourthletter Need more information to understand the issue. What "global fields" are we e.g. talking about?

**Comment by fourthletter** [comment]
@frjo I believe we're referring to the region question included in funding applications:
![image](https://user-images.githubusercontent.com/20019656/62884523-c68a9300-bd04-11e9-8cbd-f08197e40821.png)

**Comment by frjo** [comment]
This is already possible. Regions are a "Category questions" taxonomy. Go to the Wagtail admin and you find "Category questions" below"Apply".
