### ISSUE TITLE
As an applicant/reviewer, i want clear visibility of tips and information that will guide me in completing each section

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#315]

**Comment by danblah** [comment]
I don't think the application platform has anymore to do here. Better help text (already supported) and links to guide.otf would do it.

**Comment by fourthletter** [comment]
@frjo suggested changing text box in application to accommodate hyperlinks.

**Comment by frjo** [comment]
We are fixing this in https://github.com/OpenTechFund/opentech.fund/issues/1490
