### ISSUE TITLE
As a manager, an overview page for each round (submission group), displaying key details, current status, and listing associated applications 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#320]

**Comment by danblah** [comment]
Total number of applications, amounts requested, number of open applications, amount of funds approved, averages, etc, ability to view and filter associated applications on the round page as you can on the submissions tab, activity feed as you see on the submissions tab but only for those apps, ability to comment on the round generally, field that links to the external doc that is being used by the round lead to capture notes

**Comment by gibbsmaya** [comment]
This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.
