### ISSUE TITLE
As a manager, I want the ability to assign myself (or others) as lead for a batch of submissions

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#327]

**Comment by gibbsmaya** [comment]
Within the plans for the Winter 2019 Sprints we are planning to add batch ability to assign reviewers. Lead is defined automatically by the lead of the round. @danblah what is the use case for batch assigning lead?

Adding to project board.

**Comment by frjo** [comment]
The Lead for a round can change, some submission gets reassigned to another Lead etc. This happens regularly and a batch function would make it a lot easier for the staff.

**Comment by frjo** [comment]
Ready to test on test. https://test-apply.opentech.fund/apply/submissions/all/

**Comment by fourthletter** [comment]
@frjo Testing worked! Thank you.
