### ISSUE TITLE
Add MFA/2FA options for all user accounts, including support for authenticator app and/or yubikey/hardware keys first

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#331]

**Comment by frjo** [comment]
https://github.com/LabD/wagtail-2fa

**Comment by frjo** [comment]
@danblah Do OTF already use some YubiKey validation services? If not we need to pick one (build one?) to support YubiKey logins.

**Comment by danblah** [comment]
https://github.com/gavinwahl/django-u2f
https://pypi.org/project/django-mfa2/
For browser based support (no additional software on user end0

**Comment by frjo** [comment]
This can now be tested on test. Accounts that use Google oauth can not access 2FA on purpose so you need to use other accounts to test.

You can first login with your real accounts to set up your test accounts at https://test-apply.opentech.fund/admin/users/

When you have logged in to your test account go to the account page https://test-apply.opentech.fund/account/ and you find the 2FA settings, "Account security", in the middle, below the reset password section.

Setting up 2FA should be straight forward, the process is the same as for most other systems that uses 2FA. I have tested it with the Authy app on iOS and had no problems.

**Comment by fourthletter** [comment]
Relates to #238

**Comment by danblah** [comment]
Worked.

* The code input field is a weird box that if i hit the small up or down arrows, raises or lowers the number. Can we remove that for just a text field?
* On the completion page (https://test-apply.opentech.fund/account/two_factor/setup/complete/) where it says "Congratulations, you've successfully enabled two-factor authentication.", can we add a sentence that says be sure to generate and download backup codes, in case you loose your device (https://test-apply.opentech.fund/account/two_factor/backup/tokens/). 
* On the https://test-apply.opentech.fund/account/two_factor/backup/tokens/, can we bump the "Back to Account Security" to be under the "Generate tokens" button?
* Can we get a #notify when someone enables or disables 2fa?

None of the below should hold up deployment but if they aren't quick fixes, can you make a follow-up ticket for them and put that into the 2019-Q3 milestone?
