### ISSUE TITLE
As a manager/reviewer, easy access to completed reviews and notes while composing a determination response

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#341]

**Comment by fourthletter** [comment]
Does this issue include templates determination language automatically populating the text box when team member drafts a letter? Example: Team member selects "approve" and template determination language about approval populates in text box.

**Comment by frjo** [comment]
@fourthletter No, that is a separate issue. If one do not exist please create one and specify how you like the feature to work and what options are needed.

**Comment by frjo** [comment]
The determination create form opens in a new tab so the submission detail views, with reviews etc. are just a tab away.

If that is not enough, would you like to have a sidebar with reviews and notes on the determination create form page as well?
