### ISSUE TITLE
As a reviewer/manager, visibility of any other related submissions or information linked to an applicant and current application

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#347]

**Comment by gibbsmaya** [comment]
@danblah I'd be interested to know what info you mean here. Currently past submissions by the same applicant are displayed on the submission screen. Is this what you mean? Or are you referring to submissions related some other way?

**Comment by fourthletter** [comment]
This is particularly useful for PMs to view projects that have been accepted or are in post-approval.

**Comment by danblah** [comment]
Assuming this is now covered with the "Related submissions" box at the bottom left of a submission
