### ISSUE TITLE
As a manager, ability to undo previous actions in a workflow or on content, or revert back to previous states

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#348]

**Comment by danblah** [comment]
Ideally, there is an option to provide a comment/why this is happening, that goes to the applicant and shows up in communications.

**Comment by todd-dembrey** [comment]
With the notifications are you happy to keep the history of the action that is being undone and add in a new set of notifications for the undoing?

I think the internal activity and slack messaging for OTF staff should not be too much of an issue, but would be interested in how this is communicated to the applicant. How do you feel about the following?

e.g. 
Activity 
* Dan Blah progressed application from A to B
* Dan Blah reverted the change of application from A to B. <reason for change>

Emails
* Dear Applicant, your application has been moved from A to B
* Dear Applicant, your application has been moved back into A. <reason for change>

**Comment by fourthletter** [comment]
@todd-dembrey We do NOT need applicants to receive a notification when staff reverts an application back to previous states (moving an application from B back to A). This is typically done to correct an error or make adjustments before moving forward on the workflow.

**Comment by frjo** [comment]
It might be sufficient to add transitions to workflow states allowing staff to go backwards in needed places. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
Turns out the main reason staff want this is to group submissions together so they can be filtered in the submission/all list and links sent out. 

Changing status to get this feature is the wrong solutions I think. Status should be status and nothing else. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
A meta category vocab has been added but not a way to tag submissions with them. I think this would be better solutions to arbitrary group submissions. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
We need to undo previous actions in a workflow or revert back to a previous state when:

[] Submission was moved to different state in error
[] Staff realized a state restricts them from specific actions like sending a determination #1121 
[] Reviewers can't access a review form unless it is in a specific state #1153
[] Staff creates one link to share with coworkers from the status. Example: All submissions in "Ready to Discuss" are filtered into one link. Multiple links are need when applications are in different states.
[] Applications in the detailed view (image of detailed view below) are sorted by states. These submissions are easier to read when they're grouped together.
![image](https://user-images.githubusercontent.com/20019656/56849881-cc499d80-68fa-11e9-8d36-3e5260cc4579.png)

[] Staff needs to change the status of a particular application several times back and forth during the course of several weeks. The states "Ready for Discussion" and "Ready for Preliminary Determination" are used several times when we:
1) staff discuss application during meeting  ("Ready for Discussion")
2) send a need more info determination ("Ready for Preliminary Determination")
3) applicant responds but staff have additional questions ("Ready for Discussion")
4) send a need more info determination ("Ready for Preliminary Determination")
5) applicant responds but staff have additional questions ("Ready for Discussion")
6) send a need more info OR dismiss determination ("Ready for Preliminary Determination")

**Comment by danblah** [comment]
Bump bump

**Comment by frjo** [comment]
@fourthletter Do staff want to be able to move from any state to more or less any other state?

Or can you create a list of states that they need to revert to? Something like:

* From state a -> able to revert to state x
* From state b -> able to revert to state y
* From state c -> able to revert to state z

**Comment by fourthletter** [comment]
@frjo Staff prefers to move from any state to more or less any other state. 

We want to ensure this feature does NOT alert applicants when a revert or multiple moves occur. Please let me know if you have other questions.

**Comment by frjo** [comment]
@fourthletter For that to become a reality the workflow system needs to be rethought and rebuilt.

What I can do for now is add specific previous states to the list of states one can transition a submission to. When going backwards I can tell the system not to send out notifications.

**Comment by frjo** [comment]
@fourthletter Ready to test on test.

I have added the ability to transition submissions to the previous state when possible. The state has "(back)" added to the name to make it easier to find and understand.

Applicants will not get e-mails when moving the state backwards but all other notifications goes out as normal.

**Comment by danblah** [comment]
Looks good and works for me
