### ISSUE TITLE
Generate static version of the public site

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#354]

**Comment by danblah** [comment]
Whats up with this?

**Comment by frjo** [comment]
I do not think this is worth the effort.

We cache everything on the public site on Cloudflare so that works in many cases like a static site. If the public site goes down e.g. Cloudflare can continue serving the cached version to visitors.

The security benefits to a static site is substantial. But for OTF (and all Hypha other users) the apply site is where all the important stuff is and that must be dynamic in any case.

**Comment by saoun** [comment]
Sounds good to me!
