### ISSUE TITLE
`Open` rounds should be the default for the `Rounds` filter in beta

### ISSUE THREAD

**Issue by wes-otf** [OpenTechFund/opentech.fund#3857]
In the beta submissions view, `Open` rounds should be the default open tab rather than `Closed`

**Edit**: Unpublished rounds that were not closed also do not appear in either list, I would expect these to probably appear in closed

**Comment by theskumar** [comment]
Current implementation mimics the logic on the "My Dashboard" page. I believe the reasoning behind show the "Closed" by default was the fact that staff won't need to refer to the open rounds as often as closed rounds.

That said, should the logic is changed in beta view then it should be updated on the dashboard as well?

**Comment by wes-otf** [comment]
@theskumar this totally makes sense, they should be mirrored logically. What sections are you referencing though? I looked at the "My Dashboard" filter sections and it looks like it didn't differentiate between open and closed rounds on the filtered tab. This was under "previous reviews":
<img width="1312" alt="Screenshot 2024-04-10 at 13 42 02" src="https://github.com/HyphaApp/hypha/assets/145372368/458fa9ce-9332-48fe-b0cb-5b9595533926">

**Comment by frjo** [comment]
If a staff member is set as lead for a round or lab it shows up in "Your rounds and labs" on the dashboard.

<img width="1169" alt="Skärmavbild 2024-04-11 kl  08 56 19" src="https://github.com/HyphaApp/hypha/assets/191392/1769529c-1159-49a8-bae5-f65b7c3bbd67">

The table defaults to "Closed". Saurabh wonders if this should also change to be inline with the filters in the submission all list view.

**Comment by wes-otf** [comment]
Ah I had yet to see that menu so that clarified quite a bit! Latest changes to #3864 reflect this.
