### ISSUE TITLE
Admins (blah) not able to see the "VIEW MESSAGE LOG" page

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#497]
Confirming this is still an issue for my admin account (even after resetting pwd, etc).

**Comment by frjo** [comment]
Only super admins see this but you account is that. You also only see it on a specific submission page.

I e.g. see it on https://apply.opentech.fund/apply/submissions/15/

**Comment by danblah** [comment]
This ended when i logged out and re logged in, closing it.
