### ISSUE TITLE
Many fields in the current IFF form are marked required in the editor interface but on the public application form they are not required.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#503]
See the different between https://apply.opentech.fund/internet-freedom-fund/ and the edit page for that application. I can apply with very little information.

**Comment by frjo** [comment]
I believe it works, if one edit the correct application form. Look for the one used by the current round to see the changes.

Best to edit all the instances of the forms so it becomes correct the next round as well.

The single checkboxes lack a "required" box but there is a pr under testing that fixes that.

**Comment by danblah** [comment]
Totally not an issue, closing. Now wondering if when an application is copied the required is also copied. Will test and create a ticket if issue arises.
