### ISSUE TITLE
Rebuilding the front end stack with gulp 4, move all scripts except jQuery lib to footer and more

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#508]
The main.js file is loaded in the header. Find out if this is really needed for some reason or if it can be moved to the footer for improved front end performance.

```
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
```

**Comment by todd-dembrey** [comment]
Agreed, this is preferable. However the way we have handled the address field and tinymce mean we have put it where it is. 

I looked into deferring the javascript from the django forms but was not successful.

**Comment by todd-dembrey** [comment]
`base-apply.html` is also used for the editing of the submission. We could look at varying the templates within apply for this specific case.
