### ISSUE TITLE
Ability for applicants to add (and invite if user doesn't exist) additional users (applicants) to edit/view an existing application

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#524]

**Comment by danblah** [comment]
- [ ] Add a "Collaborators" box to the submission.
- [ ] Create an "Add collaborator" button.
- [ ] Allow the author or OTF staff to add collaborators.
- [ ] Upon clicking, pop up a window just like the "Partner" button that allows the user to put in an email address, then hit update.
- [ ] If known user matches email, give that user permissions to edit, see it in their dashboard, etc (same as primary applicant)
- [ ] If unknown users, kick off new user process
- [ ] List all collaborators in the new box 
- [ ] Allow OTF staff or primary author the ability to remove collaborators

**Comment by danblah** [comment]
See #663. Doing that ticket would likely make this redundant.

**Comment by fourthletter** [comment]
Relates to #177 and #324

**Comment by frjo** [comment]
@danblah @fourthletter Is this separate from the partners? It sounds like the partners feature but with a different name.

**Comment by danblah** [comment]
As far as the workflow on editing a submission, yeah very similar, except this would allow the author to invite/create a user and give the access to the submission.

**Comment by frjo** [comment]
@danblah so it’s the applicant that should be able to use this function? 

Should the invited user have the same permissions as an applicant?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danblah** [comment]
Yes and yes (only to that submission). We don't want the applicant to see the whole list of users, just an add email box (maybe later, the ability to see any users they've previously invited or who invited them).
