### ISSUE TITLE
In Staff Reviews for Concept notes, the "Other Comments" field is marked required

### ISSUE THREAD

**Issue by becklm** [OpenTechFund/opentech.fund#528]
Further, the other fields that are required to be filled in are not marked required.

**Comment by frjo** [comment]
I believe all fields that are required to add to a form also becomes required when filling out the form.

@todd-dembrey Maybe can explain how this works.

**Comment by todd-dembrey** [comment]
Yes, that is the case. If a field must be included within the form it is marked as required. I think that assumption holds True for Applications, but might be a bit odd for Reviews. We could look to add an option to make these non-required within the Review forms. 

It is hardcoded here: 
https://github.com/OpenTechFund/opentech.fund/blob/4b878dc87440127e15f6afc40b50a0cbd119277a/opentech/apply/utils/blocks.py#L151

We would look to vary it here:
https://github.com/OpenTechFund/opentech.fund/blob/4b878dc87440127e15f6afc40b50a0cbd119277a/opentech/apply/review/blocks.py#L38:35

We would also want to make sure we have a default blank string for these.
