### ISSUE TITLE
When an RFP closes, the button/link to the application should cease to work

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#534]
When the Learning Lab RFP closed on Friday, people were still able to click the "Apply for this RFP" button and got a server error. The button should instead switch to "closed" once the deadline's passed.

**Comment by todd-dembrey** [comment]
Relevant Sentry error: https://sentry.io/otf/otf-webapp/issues/674272017/events/30510733320/

It looks like I've failed to provide a fallback for the RFP when the round is closed. 

Essentially it should  have the same behaviour as funds, see below:

https://github.com/OpenTechFund/opentech.fund/blob/33226c791da32c295d3b8e91364a2559290ce0a6/opentech/apply/funds/templates/funds/fund_type.html#L25-L28
