### ISSUE TITLE
Mailgun web hooks CSRF verification failed Request aborted

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#536]
When Mailgun tries to tell the Django app about events Django answers with a Forbidden (403) because CSRF verification failed, no Referer header.

**Comment by todd-dembrey** [comment]
I'm a little confused by this. Anymail exempts the view from csrf. Unless i'm adding it back in later. Will look into that.

https://github.com/anymail/django-anymail/blob/3f2c6d6917816ef0b476885f773bd0b367b880f5/anymail/webhooks/base.py#L107-L109

**Comment by todd-dembrey** [comment]
Is there more info available from Mailgun about this?

**Comment by frjo** [comment]
Using the proper URL https://qwerty:qwerty@apply.opentech.fund/activity/anymail/mailgun/tracking/ seems to resolve this issue. The ”/activity” was missing before but fixed now after instructions from @todd-dembrey.

**Comment by frjo** [comment]
This seems to work now, thanks @todd-dembrey.
