### ISSUE TITLE
Can Django not send password resets to accounts with an empty password

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#537]
The imported accounts had an empty password and the password reset does not work on these accounts. Setting an placeholder password makes the password reset works again.

How does this work with accounts that the system creates when people submit applications? These accounts have empty passwords as well?

**Comment by todd-dembrey** [comment]
We rely on the core django behaviour at the moment. relevant part below.

This prevents:
* inactive users -> new users who must use the activation email
* unusable passwords -> Oauth users 
from using the reset form.

We should probably have set imported applicants as active and with a random **useable** password. 

There should probably be a way to request the activation email again...

```
    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.

        This allows subclasses to more easily customize the default policies
        that prevent inactive users and users with unusable passwords from
        resetting their password.
        """
        active_users = UserModel._default_manager.filter(**{
            '%s__iexact' % UserModel.get_email_field_name(): email,
            'is_active': True,
        })
        return (u for u in active_users if u.has_usable_password())
```
