### ISSUE TITLE
Special characters not rendering in legal name field

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#543]
see https://apply.opentech.fund/apply/submissions/113/

**Comment by todd-dembrey** [comment]
I cannot replicate this in the testing environment. We faithfully transfer the submitted name into the User model and do not mess with it. I cannot see where we would escape `'<>:`, we only bleach out tags.

The name displayed on the page there is the fullname from the user model. Editing the user model will fix this.

**Comment by todd-dembrey** [comment]
@danblah Have you got any other examples?

**Comment by frjo** [comment]
I think understand the issue now. The "Legal name" field on submissions are linked to the user accounts "Full name" field.

If one tries to update the name on a submission it directly reverts to the name for the account. This can give the impression that it's not working.

@danblah Update the user name first and then resale the submission will fix the name issue.

**Comment by danblah** [comment]
Is it useful to have two separate fields for Your Name (applicant and required for acct purposes) and Legal Name (contracting party, may be the same but also may be an org name, maybe not required on initially)? We've done this for the eng lab app (https://apply.opentech.fund/admin/funds/applicationform/edit/32/)

**Comment by danblah** [comment]
added @otf account, dm me if you've another account to add.

**Comment by danblah** [comment]
To fix this, go to the applicant's user account and fix their name (this is in /admin). Then all of their applications will render rightly.
