### ISSUE TITLE
Uploaded files are not listed in the upload field when editing

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#544]

**Comment by frjo** [comment]
@todd-dembrey This issue pussels me and I would appreciate some pointers. 

Since it seems files are lost when you resave a submission it would be good to get fixed. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
@todd-dembrey Tested the file uploads more. And I think the field was removed when I tested locally only because the actual files was not present. When I now test they are not removed.

But if I edit and upload more files they replaces the current ones. I think it would be better if it works in the usual manner.

**Comment by todd-dembrey** [comment]
Yeah, the behaviour was confusing. I've rewritten the file handling on the multi upload case. It is much better now.
