### ISSUE TITLE
Double check all of these access permissions

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#545]
For these types of content

- [ ] Applications
- [ ] Reviews
- [ ] Determinations

**Applications**

- Owner(s): view/edit (when in right status)
- Team: view/edit (always)
- Applicant: view/edit (when in right status)
- Reviewers; view (when in right status)

**Reviews**

- Owner: view/edit
- Team: view/edit
- Applicant: None
- Reviewers: None

**Determinations**

- Owner: view/edit
- Team: view/edit
- Reviewers: view
- Applicant: view

**Comment by frjo** [comment]
What is mangers supposed to be able to do that staff are not?

**Comment by danblah** [comment]
Staff = Managers = Team, Staff != Admins
For at least OTF, all staff members have all the same permissions
What are some things that you've manager down to do that staff aren't able to do (just to make sure I'm understanding)?

**Comment by frjo** [comment]
So the manger group (role) is irrelevant for OTF.

I need to investigate more before I know what, if any, differences there are now.

**Comment by frjo** [comment]
https://github.com/OpenTechFund/opentech.fund/pull/551

**Comment by frjo** [comment]
I have deployed the fix so staff can view all reviews.
