### ISSUE TITLE
When creating determinations, remove all of the pre-filled text

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#546]
Because 

* It's not formatted
* It does not always show up or does inconsistently
* Doesn't play nice when the lead needs to put in additional text
* Is ultimately taking up more time than saving it

Let's remove it immediately and will create another issue for improved functionality for later release.

**Comment by frjo** [comment]
You can eat the text yourself here: https://apply.opentech.fund/admin/settings/determinations/determinationmessagesettings/2/

**Comment by frjo** [comment]
@danblah I have now disabled the javascript that copy the text. Will deploy that soon.

Will add another issue to improve this feature.
