### ISSUE TITLE
The Cloudflare firewall is getting triggered often, prompting a captcha waaaay to much for team members inputting text into determinations etc.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#547]
What can we do to ideally keep the security high while not getting team triggers? Wondering if https://github.com/privacypass/challenge-bypass-extension is useful here? Team members have a browser extension that sends their IP address to cloudflare for being whitelisted? Something on the app side? Some cloudflare wap firewall westting?

**Comment by frjo** [comment]
I have disabled Flash and Wordpress rules in Cloudflare Web Application Firewall for opentech.fund.

I see you have already whitelisted some IPs, for you offices I assume.

**Comment by frjo** [comment]
I have also now disabled the  OWASP XSS rules that got triggered a lot by staff. Reports indicate that this solves the problem.

@danblah I know you are uncomfortable with lowering any security. But the rules for opentech.fund are significantly stricter set than they are for otf.is.

The otf.is domain has no Web Application Firewall and no OWASP rules in place.

The opentech.fund domain has both and only a single one of a dussin relevant OWASP rules deactivated. That rule had to many false positives to be used, it was a mess for staff and surly for many other users as well.
