### ISSUE TITLE
A batch ability to select multiple applications and dismiss them outright using the same pre-defined determination message

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#548]
This is very much related but not the same to #172

**Comment by danblah** [comment]
A comment from the team:

How can we get this reflected in the backend i.e. if we batch dismiss applications with predetermined messages I want to be able to have that reflected in the database. This would be so we can tell people in 2019, 20% of CNs to IFF were rejected for focusing on ICT4D, 15% due to a lack of adequate detail, etc. I think that would be really powerful information to automate so if we are going that route I'd like to be sure it is at least in the pipeline

**Comment by gibbsmaya** [comment]
This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.
