### ISSUE TITLE
A view in the apply admin for only active rounds (with dates) with quick links to edit the round, associated fund, currently used applications, and review forms.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#549]
Maybe just a revamp on the existing rounds and sealed rounds page that by default hides inactive rounds, and shows additional buttons? Right now, it' super super super confusing to have to go to 3 different panels and easily end up editing an older application, fund, etc.

**Comment by frjo** [comment]
I think adding links to the round, fund, application form and review form to the current RoundListView at "/apply/rounds/" would be best.

A similar UI to the how the BaseAdminSubmissionsTable at "/apply/submissions/all/" does it. Having extra information in a mould out row.

**Comment by frjo** [comment]
@fourthletter @danblah Ready for testing at https://test-apply.opentech.fund/admin/funds/round/

**Comment by fourthletter** [comment]
@frjo  I like the new interface because it's centralized. Thanks!

[]What does "SEALED" mean?
[] How do I archive a round?
[] Which rounds are currently active and which ones are inactive (passed an end date)?

**Comment by frjo** [comment]
Sealed rounds are rounds that staff can not view before a specific date. Mainly used for taking in bids I believe.

Rounds are open or closed, no concept of "archived" exist.

In the list you see start and end date and from that you can see who are open/closed.

**Comment by danblah** [comment]
This is great! So much better. Thanks!
