### ISSUE TITLE
Allow reviews to be edited by staff and author

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#552]

**Comment by danblah** [comment]
Assuming this will require enabling revisions for the content type. If so, we'd need to clearly indicate that an edit/new revision has been created when the viewer is reviewing a review.

**Comment by danblah** [comment]
I want to bump this up as something to get moving on.

**Comment by fourthletter** [comment]
Related to #1162 #714 #702

**Comment by fourthletter** [comment]
@frjo AC reviewer was not able to edit their own review https://apply.opentech.fund/apply/submissions/4027/reviews/5276/

**Comment by frjo** [comment]
@danblah Is it a requirement that the reviews have revisions?

**Comment by danblah** [comment]
No, but please make a follow up ticket for this functionality.

**Comment by frjo** [comment]
Revisions moved to #1311

**Comment by fourthletter** [comment]
@frjo Test worked. Thanks!

**Comment by frjo** [comment]
@fourthletter Found my bug and fixed it, so now it should work.

**Comment by fourthletter** [comment]
@frjo Test was successful. Thanks!
