### ISSUE TITLE
Submission list view is slow

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#562]
See https://apm.scoutapp.com/apps/28725/endpoints/Q29udHJvbGxlci9vcGVudGVjaC5hcHBseS5mdW5kcy52aWV3cy5TdWJtaXNzaW9uTGlzdFZpZXc=/trace/1360015991?section=time&nplusone=7624.189

**Comment by todd-dembrey** [comment]
So this is triggering when we deserialize the fields here:

https://github.com/OpenTechFund/opentech.fund/blob/c126ba39bb1076abce301e6281e21c2e8fe71efe/opentech/apply/funds/models/mixins.py#L66

Essentially `field.value` is populated with the category and we dont need all that for what we are doing.

```
>>> field.block
<opentech.apply.categories.blocks.CategoryQuestionBlock object at 0x7f949da4e908>                                                                                                                                                 
>>> field.value
StructValue([
    ('field_label', 'A category question'), 
    ('help_text', ''), 
    ('required', True), 
    ('category', <Category: Project status>), 
    ('multi',False)],
)   
``` 

It looks like we want to avoid the instantiation that happens in `__getitem__` of the StreamValue:
https://github.com/wagtail/wagtail/blob/088d3ffc219c6a06a5d3daff7ece2a8c9b92f683/wagtail/core/blocks/stream_block.py#L381-L392

and just do the bit we need:
```
for field in form_fields.stream_data:
    block = form_fields.stream_block.child_blocks[field['type']]
    if isintance(block ...
```
