### ISSUE TITLE
Ability to attach files and format text (wysiwyg editor) for communication messages (comments in the communications tab)

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#567]

**Comment by danblah** [comment]
Is it possible to bounce this up? Many applicants are finding this a serious limitation.

**Comment by frjo** [comment]
@danblah  As a first step I have updated the formatting of comments so line breaks in comments are translated to br-tags. This makes it far easier to read long comments.

I also made the date ISO-standard and moved the display of the name a bit.

How does this look?

**Comment by frjo** [comment]
What other formatting besides line breaks is really needed?

Should not files be uploaded to the submission directly?

**Comment by danblah** [comment]
On attaching files
* Yes, add the ability to attach files to submissions within the comment that then show as additional files on the submissions page
* But also, the file should display on the comment it was uploaded to (so you can see the context for the files upload)

On formatting, there is other things. A markdown editor would totally do it.
