### ISSUE TITLE
Lab applications are are forced to include the same required fields as funds, but those are not relevant/appropriate for all lab applications.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#568]
Let's undo making them actually required but show them in the add new field as distinct/important fields for now

**Comment by frjo** [comment]
See https://github.com/OpenTechFund/opentech.fund/pull/592

**Comment by frjo** [comment]
@todd-dembrey 

* Title
    * All
* Value
    * Fellowship applications and Labs are mostly for services not money.
* E-mail
    * All
* Address
    * Should not be required I think.
* Full name
    * All
* Duration
    * All, I think
