### ISSUE TITLE
Ensure that system doesn't crash when mailgun not set

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#569]

**Comment by danblah** [comment]
Done?

**Comment by danblah** [comment]
@frjo and @Parbhat, did we resolve this?

**Comment by Parbhat** [comment]
Do not know about the crash issue mentioned in the issue. Looks like it is not specifically related to mailgun. And code should correctly handle email failures. @frjo may know more about this.

**Comment by frjo** [comment]
I have not tested this, but will do.

**Comment by frjo** [comment]
I  believe this is fixed since some time. By default 'django.core.mail.backends.smtp.EmailBackend' is used.
