### ISSUE TITLE
Proposals should be retaining all information from concept note, after invite to proposal function

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#570]

**Comment by frjo** [comment]
@danblah All fields that are named the same will copy over the information I believe.

Where does it not work?

**Comment by frjo** [comment]
@todd-dembrey Howis thisset up, are all fields named the same copied over?

**Comment by todd-dembrey** [comment]
This method handles progression to the next stage.
https://github.com/OpenTechFund/opentech.fund/blob/461ec88c221a981f9b33a7a95b9af4e787c4d5b9/opentech/apply/funds/models/submissions.py#L400

Currently we just get the new fields for the next stage and do nothing. The next time you try to render the application it looks for the `form_field` id in the `form_data`.
https://github.com/OpenTechFund/opentech.fund/blob/461ec88c221a981f9b33a7a95b9af4e787c4d5b9/opentech/apply/funds/models/submissions.py#L414 

We discussed right at the start of the project that we would not handle consistent data between stages (except named fields) at this point.

I would probably add some logic around line 414 with the following effect:
```
    new_form_fields = self.get_from_parent('get_defined_fields')(target)
    self.form_data = update_data_for_new_form(self.form-data, self.form_fields, new_form_fields)
    self.form_fields = new_form_fields
```

`update_data_for_new_form` would do its best to compare the two sets of fields and try and find similar fields and map them over. I don't think we can every get everything but we can do a good job of most of the fields.

**Comment by todd-dembrey** [comment]
We could also look into making it easier for the applicant to access their conecpt whilst writing the proposal?
