### ISSUE TITLE
Automatically move an application from "Screening" to "Internal review" when either a reviewer is assigned or a review is submitted.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#571]

**Comment by gibbsmaya** [comment]
We should take this into the discussion we will be having around potentially automating some of the workflow transitions. This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.

**Comment by fourthletter** [comment]
Currently, team members **manually** change the status from "screening" to "internal review" to indicate a concept note that is within remit, ready for reviews, and could be discussed during a review call. The "internal review" distinction is important for note-taking in the detailed view as well. Automating this would expedite the process, but loses the PM ability to filter submissions that are ready for primary and secondary reviews.

**Comment by frjo** [comment]
This is ready for test on test.

**Comment by fourthletter** [comment]
Feature was visible and functional during test. Thanks!
