### ISSUE TITLE
Define and institute a password policy for all accounts and required mfa for privileged accounts

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#572]
See below and #238 and #331 
A minimum of 12 characters and a check with zxcvbn or similar tool is
my recommendation. Plain and simple.

https://github.com/dropbox/zxcvbn
https://github.com/dwolfhub/zxcvbn-python

https://pages.nist.gov/800-63-3/sp800-63b.html#102-usability-considerations-by-authenticator-type

**Comment by frjo** [comment]
See https://github.com/OpenTechFund/opentech.fund/pull/594
