### ISSUE TITLE
Expand the category widget to handle large categories

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#574]
The countries category has a lot of terms and displaying them as a long serie of checkboxes it not optimal. A better widget option for this would be good. Maybe something like the ”Statuses” on the /submissions page.

**Comment by frjo** [comment]
@danblah This is already fixed. See e.g. the country field here https://apply.opentech.fund/internet-freedom-fund/

Categories with more than 32 terms will get this widget. I.e. only the Country category for now.
