### ISSUE TITLE
Wysiwyg vs markdown?

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#580]
Should we go back to markdown, both?

**Comment by frjo** [comment]
I think we are to far down the rabbit hole to revert back to Markdown now.

**Comment by danblah** [comment]
Let's add markdown for communication/comment for sure. I'd like us to move back to markdown and allow a markdown editor for all fields that aren't one line, with some additional features:

* Markdown editor displayed by default
* Editor has link / overlay for formatting help (does not go to another page, stays on page)
* Editor has link / overlay for taking richtext and converting it to md (does not go to another page, stays on page see https://github.com/euangoddard/clipboard2markdown)
* Editor has link / overlay for previewing a field (not whole document) and does not go to another page, just stays

**Comment by danblah** [comment]
Same for all public facing pages we edit.
