### ISSUE TITLE
Add contact information to confirmation screen

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#585]
As discussed in demo, the confirmation screen presented when an application form is submitted should include some additional text to prompt a user to contact OTF if no email has been received.

Currently confirmation screen says:

```
Thank you for your submission to the Open Technology Fund. An e-mail
with more information has been sent to the address you entered.
```

We should add a line saying:

```
If you do not receive an email within 15 minutes please check your
spam folder and contact help@opentech.fund for further assistance.
```

**Comment by frjo** [comment]
PR: https://github.com/OpenTechFund/opentech.fund/pull/530
