### ISSUE TITLE
Automatically change an application's status from "Internal review" to "Ready for discussion" after it's received 2 reviews

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#588]

**Comment by gibbsmaya** [comment]
We should cover this in the discussion we will be having around potentially automating transitions between statuses. This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.

**Comment by fourthletter** [comment]
I think automating this status after two reviews would be helpful. However, doesn't the Red Team Lab move forward to AC with only one review?

**Comment by frjo** [comment]
This is ready for test on test.

**Comment by fourthletter** [comment]
Status automatically changed from internal review to ready for discussion during test for multiple submissions. Thanks!
