### ISSUE TITLE
As an admin, how can I delete/rename a Category Option and not loose any related data?

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#589]
Currently a user can delete options from the category. However these will eventually relate to submissions from the users and deleting or changing the data would invalidate what they have submitted.

We should consider how we want to handle this.

**Comment by todd-dembrey** [comment]
@danblah What happens if a user adds in a previously used option? Should we resurrect the old one?

**Comment by danblah** [comment]
My current understanding is that editing existing for style/corrections is ok, adding new terms is ok, deleting old terms is not.

When deleting, ID's are preserved but the content of the category is deleted, which means we don't know what was saved looking back. We need the content to be saved so that when looking back, we can both get the id and the content.

**Comment by danblah** [comment]
Resolved by https://github.com/OpenTechFund/opentech.fund/issues/1183
