### ISSUE TITLE
Create a permission to expose the "VIEW MESSAGE LOG" ability to users in a group (staff)

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#590]
Right now this is only available to admins. This is becoming super important for round leads to confirm what's been sent and for us to figure out what edits to the msgs templates we need to make.

**Comment by frjo** [comment]
@Parbhat Getting the "View message log" link to show up for staff is easy in "applicationsubmission_detail.html". But how to give staff access to "admin:activity_event_changelist"?

**Comment by Parbhat** [comment]
@frjo We need to first remove `if` condition from the [template](https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/funds/templates/funds/applicationsubmission_detail.html#L35). Then the View message log tab will be visible to Staff group but they will get 403 forbidden error while visiting the link. To make the page accessible to them Admin user needs to give staff group new permission with name `activity | event | Can change event` from/django-admin/auth/group/4/change/ . From Django 2.1, there will also a [View permission](https://docs.djangoproject.com/en/2.1/releases/2.1/#model-view-permission).

**Comment by frjo** [comment]
@Parbhat  Does this looks right to you? https://github.com/OpenTechFund/opentech.fund/pull/828
