### ISSUE TITLE
Cannot edit some individual project pages 

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#599]
See here: https://apply.opentech.fund/admin/pages/315/edit/#tab-content

Attempting to edit https://www.opentech.fund/results/supported-projects/adversary-lab/. There is a broken link in the intro text (because of the `.` it seems) and the body text is not visible in the CMS (clicking the drop down doesn't work). 
<img width="1087" alt="screen shot 2018-09-19 at 1 56 28 pm" src="https://user-images.githubusercontent.com/28866038/45771728-de9c8400-bc13-11e8-9784-a525a72e7d76.png">

**Comment by frjo** [comment]
@dmcdev1 This is fixed on live now from the command line. It was a bug in the migration. Just let me know if you encounter others.
