### ISSUE TITLE
For submissions, a new team only visible review or comment type that is notes on a specific submission from an all team call

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#619]

**Comment by tmsndrs** [comment]
UX tasks 
- [ ] Mockup UI
- [ ] Test with OTF staff

**Comment by gibbsmaya** [comment]
This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.

As a side note @frjo, yes this is exactly what the internal comments are for but they don't seem to be well understood. We are going to repurpose this into a more well-understood concept int he work we are doing.
