### ISSUE TITLE
Is the amount of emails/notifications going to the applicants to much?

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#625]
Team is wondering if we're sending to many msgs out to applicants? We should def. ask around and design a survey for folks. If the result ends up being yes, one discussed alternative is to identify which states are most important for a notification to go out and only notify on those, making it clear in the first notification that they will only get notifications at these stages and then building features that allow them to get an update of recent activity at any time (and/or let them choose default notification settings in their profile).

**Comment by gibbsmaya** [comment]
We should incorporate this into our discussion around 'applicant friendly states' for the application timeline. This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.
