### ISSUE TITLE
Create demo content to be used for sandbox/test/dev

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#627]
The Sandbox site https://sandbox.opentech.fund/ now has demo content that resets every 24h.

The database dump exist only on the sandbox branch in ”public/sandbox_db.dump”. It has only content and users that I have created from scratch, starting from an completely empty database.

All the demo users have the same password "sandbox-guest”, see more at https://sandbox.opentech.fund/demo-about/about-sandbox/

This is the command that is run daily by Heroku Scheduler:

~~~~
curl -s https://cli-assets.heroku.com/heroku-cli/channels/stable/heroku-cli-linux-x64.tar.gz | tar -xz && mv heroku-cli* heroku-cli && ./heroku-cli/bin/heroku pg:backups:restore 'https://github.com/OpenTechFund/opentech.fund/raw/sandbox/public/sandbox_db.dump' DATABASE_URL -a sandbox-opentech-fund --confirm sandbox-opentech-fund
~~~~

**Comment by frjo** [comment]
@danblah Two questions/issues:

1. Should the passwords be out in the open for everyone to see as they are now? Another option is to have people interested contacting OTF and we give them the password so they can test? The second option would make the problem with junk/spam less troublesome but be a hurdle for real users.
2. Is the domo content ok as it’s now or do you want to improve it? (It’s really slapped together now.)

**Comment by danblah** [comment]
Let's add some submissions for each fund, some reviews, and submission responses. Adding in @jheretic who's going to be taking on the ci/cd stuff here. if y'all are ok with the acct creds being out there, ok with me. we could alternatively create a tiny little app that allows people to request unique acct creds by putting in an email that's been validated as real.

**Comment by danblah** [comment]
I think most ideal for testing/bug bounty etc... would be if we could actually mirror specific types of content from production, for example: all the public facing content (in use applications, people, updates, frontpage, etc).

**Comment by frjo** [comment]
Having content on the site that looks the same as the real content will confuse people. Normal users never look at the adressbar, or anything else that they do not absolutly need to.

**Comment by zerolab** [comment]
This could possibly be addressed with an environment indicator (e.g. https://github.com/teapow/django-envi)
