### ISSUE TITLE
Why is the Learning Lab RFP (closed, not promoted) still showing up on the front page at the bottom?

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#633]

**Comment by frjo** [comment]
I do not think there are any features for removing content from pages based on application status on the other end. @todd-dembrey maybe can correct me if I'm wrong here.

**Comment by todd-dembrey** [comment]
We do not currently have a way to get a

**Comment by todd-dembrey** [comment]
We do not have a way to easily grab the related "open" funds/labs/rfp as part of a queryset from the public site. We have tried to avoid adding too much coupling between the sites.

The following function handles to population of the lists, specifically line 131.
https://github.com/OpenTechFund/opentech.fund/blob/47c90ea4cbe431a65267fd276606742797e9592c/opentech/public/home/models.py#L126-L132

You could use change this method to get all of the related objects and yield while a counter is less than a value whilst checking for `.is_open`  
https://github.com/OpenTechFund/opentech.fund/blob/47c90ea4cbe431a65267fd276606742797e9592c/opentech/public/funds/models.py#L182

This is going to be less performant, but much easier to implement.

e.g. 
```python
extra_qs = page_type.objects.public().live().exclude(id__in=selected)
displayed = 0
for page in self.sorted_by_deadline(extra_qs):
    if page.is_open:
        yield page
        displayed += 1
    if displayed >= extra_needed:
        break
```

see below for some of the complexity about adding queries to the Applications objects:
https://github.com/OpenTechFund/opentech.fund/blob/47c90ea4cbe431a65267fd276606742797e9592c/opentech/apply/funds/models/applications.py#L29-L34

**Comment by danblah** [comment]
SO ANNOYING, FIX THIS! I want that Requests for Partners section on the home page to disappear if there are no actual open requests!
