### ISSUE TITLE
Within submissions, change the uploaded files link behavior to include a shareable link that upon clicking checks user permissions and then delivers file

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#637]
Right now, it links to a non-sharable link, unique to the user that can't be shared through external mediums to users with permissions to view the file, so others get a 404 unless they go to the submission directly and then click the file attachment themselves.

**Comment by danblah** [comment]
Seems to work.
1. Go to submission
2. Upload file
3. Save
4. Right click and copy url to file
5. Log out
6. Paste url into address bar
7. Log in, redirects to file, which redirects to s3 url including access key given out by app

**Comment by frjo** [comment]
That is how it works for me as well. It's implemented very mush like how Drupals private files does it.
