### ISSUE TITLE
Form field template improvements

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#643]
https://github.com/OpenTechFund/opentech.fund/blob/52d9c47cc0092a5a81722a4d3f6cba3e628fed32/opentech/apply/templates/forms/includes/field.html#L8

Is required an attribute for the label element?

https://github.com/OpenTechFund/opentech.fund/blob/52d9c47cc0092a5a81722a4d3f6cba3e628fed32/opentech/apply/templates/forms/includes/field.html#L34-L36

What is the purpose of this extra empty label element?

**Comment by danblah** [comment]
@frjo closing this. if you need to reopen it, do so and move it to q3.
