### ISSUE TITLE
Link submission user to account page for admin view.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#649]
Saving doesn't actual change the email field. See https://apply.opentech.fund/apply/submissions/332 as an example.

**Comment by frjo** [comment]
@danblah I believe the e-mail is picked up from the user account so changed it there and all should be well.

**Comment by frjo** [comment]
A link to the user account from a submission might be a good idea.

**Comment by danblah** [comment]
Totally agree, that in a submission, a link to the account edit page for name and email would be awesome.
