### ISSUE TITLE
Max memory exeded on Heroku web dynos 1X (512 MB)

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#659]
@danblah  I just now upgrades the dynos to 2x so we get 1 GB memory.

We should investigate what eats up the RAM.

It was hovering around 350 MB until yesterday when it hit the roof. I restarted the dynos but is quite quickly climed up to 400+ so then I upgraded. The extra cost is 100 USD per month.

~~~~
 Oct 16 08:37:11 live-opentech-fund heroku/web.1: Error R14 (Memory quota exceeded)
~~~~

**Comment by todd-dembrey** [comment]
Interesting. It seems to be back to normal levels (~350 - which is normal for most wagtail/django apps.)  since you added the extra dyno.

For the record the memory went up from 16th Oct 2018 15:10-15:40

**Comment by frjo** [comment]
I have now downgraded back to 1x WEB_CONCURRENCY and set WEB_CONCURRENCY down from 3 to 2.

It seems each process takes around 130 MB so currently 260 MB is used.
