### ISSUE TITLE
Is Travis CI still needed with CirleCI running?

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#668]
The only reason I prefer CirlceCI is speed.

CircleCI 2 min 28 sec
TravisCI 4 min 29 sec

And that is when TravisCI run at once, many times it’s queued for som time as well.

I have yet to add coverage and codecov to CicleCI but have started that work here https://github.com/OpenTechFund/opentech.fund/pull/667

After this is all done is there a reson to keep using TravisCI as well?

**Comment by todd-dembrey** [comment]
Happy to remove Travis. I was familiar with it which is why i chose it initially. 

Is Circle CI building on PR or commit?

**Comment by frjo** [comment]
On PR as it’s now.
