### ISSUE TITLE
Automatically move a submissions status to submit when a comment is submitted from applicant

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#672]
Right now this happens when the applicant saves edits to the submission but not when they respond to the determination with a comment (which we ask them to do more often than create edits). The current functionality requires the lead to manually change the status to submit to allow for other states. 

Alternatively, we could add a button or checkbox to the applicant's comment box that says they are submitting their response to the determination, which would then move the status to submit.

**Comment by gibbsmaya** [comment]
We should cover this as part of the discussion around potentially automating some workflow transitions. This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.

**Comment by tarakiyee** [comment]
Maybe instead of automatically sending an application to discussion, a notification to the round lead would be better? It happens so often that a response from the applicant is not always adequate, necessitating further follow up before discussion.
