### ISSUE TITLE
AC reviewer permissions/view issue 

### ISSUE THREAD

**Issue by dmcdev1** [OpenTechFund/opentech.fund#686]
AC member says they can't see other reviews when submitting a review. cc @danblah @frjo

**Comment by frjo** [comment]
@dmcdev1 Should they be able to see all other AC reviews or all reviews, even from staff?

**Comment by frjo** [comment]
This was built on purpose so not really a bug. The PR will allow all users in the reviewers group to view all other reviews.

**Comment by danblah** [comment]
Yeah, this is not intended functionality. As it is now, AC members have access to:

* All determinations posted by OTF
* Which OTF team members reviewed and their outcome, but not the full review
* Any "Reviewers and Staff" or "Public" communications
* Full activity feed

Two related and missing enhancements are:

* Ability for AC members to allow other AC members to see their review
* Ability for AC members to search for any submission that has ever been in an AC review state within funds/labs they are currently assigned to.

**Comment by frjo** [comment]
So reviewers should not automatically see all other reviews from other reviewers?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danblah** [comment]
Yeah, that's right. See Yeah, that's right. See #754 for the additional feature
