### ISSUE TITLE
Define and implement the primary and secondary reviewer workflow now being used for concept note reviews 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#694]

**Comment by gibbsmaya** [comment]
This is planned to be covered in the work we are doing in the Winter 2019 Sprints. We may not cover it fully in terms of specifying primary and secondary reviewers but I suggest reassessing this issues once the new round management interfaces are in place. Adding to project board for now.

**Comment by danblah** [comment]
Closing, as covered other Winter Sprint tickets..
