### ISSUE TITLE
Improve wording of ambiguous field titles for submissions

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#703]

**Comment by tmsndrs** [comment]
UX tasks
- [ ] Review and make recommendations

**Comment by frjo** [comment]
Is the the field titles staff see when they create the forms or the finished forms that the applicants fill in. If the later it's not an UX task.

**Comment by tmsndrs** [comment]
Hey @frjo yes it's the form the applicant see. There's a tasks to list the field titles that people were confused about and suggest alternatives.
