### ISSUE TITLE
Allow users to add tabled data when providing budget information

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#704]

**Comment by tmsndrs** [comment]
UX tasks
- [ ] Review and make recommendation

**Comment by frjo** [comment]
We added the table related tags to BLEACH_ALLOWED_TAGS in another issue allowing applicants to paste in tables.

They could, and did, paste in tables before but the output was nearly impossible to read. Now they render as tables as they should.

If this doesn't resolve the issue please reopen.
