### ISSUE TITLE
For all text fields, present a warning that their response is long to the applicant when they approach 800 characters and a warning that their response is to long when they approach 1000 characters

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#705]

**Comment by tmsndrs** [comment]
UX Tasks

- [ ] Create a list of long text fields
- [ ] Gather ideal counts from OTF
- [ ] Make UI suggestion for how to present values

**Comment by fourthletter** [comment]
Related to #577

**Comment by frjo** [comment]
The TinyMCE editor has a word count feature. I added a small javascript to format the word count with warnings as seen in the images below.

An average English word is around 5.1 characters so I set the limits to 170 and 200 words.

Can this work?

Test here: https://test-apply.opentech.fund/rapid-response-fund/

![word_count_1](https://user-images.githubusercontent.com/191392/65223852-553bbe00-dac2-11e9-81c2-aed2f0358bc7.png)
![word_count_2](https://user-images.githubusercontent.com/191392/65223865-58cf4500-dac2-11e9-8101-570e83141ecf.png)
![word_count_3](https://user-images.githubusercontent.com/191392/65223879-5d93f900-dac2-11e9-94a6-d975e45f0fb4.png)

**Comment by danblah** [comment]
Upon testing, I see the word count but not the warnings at all.

**Comment by frjo** [comment]
Just retested on https://test-apply.opentech.fund/rapid-response-fund/ in both Safari and Chrome and it seems to work.

Clearing browser cache/hard reloading the page to get new css maybe?

**Comment by frjo** [comment]
![word_count_warning_chrome](https://user-images.githubusercontent.com/191392/65251458-a0bc8f00-daf7-11e9-8e50-2baa6161c089.png)

**Comment by danblah** [comment]
Working. Can we bump it up to 800 and 1000 by default? Can you make a ticket that allows for "Over" to be set by a manager in the form editor, where the "Close to" warning comes up at 80% of the max?

**Comment by frjo** [comment]
@danblah The issue says 1000 characters.  Divided by 5 makes around 200 words. 

You want to set it to 1000 words? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
@frjo We are limiting some application questions/text fields to either **1000 words OR 500 words**. This depends on the questions. Is it possible for staff to choose this limit in wagtail admin or should I specify which questions or text fields?
