### ISSUE TITLE
Change the "Submit" button for all applications to "Submit for review".

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#709]

**Comment by tmsndrs** [comment]
On the form page itself I've just made a small copy change to the button to be explicit you're submitting it for review not just a generic form submission. I did toy with the idea of having a warning to let users know that their application won't be editable but I think that's implied in submitting for review. 

<img width="666" alt="screen shot 2018-11-20 at 15 30 09" src="https://user-images.githubusercontent.com/7290588/48783859-500eb680-ecd9-11e8-94ff-312b0a16e04d.png">

**Comment by danblah** [comment]
And also i think adding a hover on the lock when they are viewing the submission may help.

**Comment by danblah** [comment]
Looks good to me, lets deploy.
