### ISSUE TITLE
Improve findability of concept note once an application has reached proposal stage as applicants may use content from the concept note for their proposal

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#713]

**Comment by tmsndrs** [comment]
UX Tasks 

- [ ] Review and make a proposal.

**Comment by gibbsmaya** [comment]
During build we had the concept note linked to from the proposal form in the right hand column, so the applicant could easily access this while writing their proposal. This seems to not be there anymore so not sure what has knocked it out, but I suggest we reinstate this, at least as a quick solution for now.

**Comment by frjo** [comment]
They are still there from what I can see. Past submissions are also listed.
