### ISSUE TITLE
As a reviewer, ability to see ‘historic’ applications they have reviewed on their dashboard

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#715]

**Comment by tmsndrs** [comment]
**UX task**
- [ ] mockup UI for historic reviews

**Comment by gibbsmaya** [comment]
@tmsndrs , I'm not sure this needs any UX/design work - the dashboard already contains multiple lists of applications (a list for applications needing review, a list for applications awaiting determination etc) which users see dependent on their roles. So I think this is simply adding an additional list for historic applications. I think this one can go straight to dev. Let me know what you think. Adding @todd-dembrey too.

**Comment by tmsndrs** [comment]
I don't think we should show a list of all historic reviews directly on the dashboard. It will be a really long list as doesn't let users focus on the things that matter most.

**Comment by gibbsmaya** [comment]
This is planned to be covered in the work we are doing in the Winter 2019 Sprints. Adding to project board.

**Comment by danblah** [comment]
Closing, covered in Winter Sprint.
