### ISSUE TITLE
Bring back the short proposal form for concept notes that are requesting less than 100k

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#717]
@frjo and @todd-dembrey, not sure how big/small this is. in the previous app, a concept note with the amount value of 100k or less was assigned a less onerous form to complete when invited to proposal. can we bring this back quickly?

**Comment by frjo** [comment]
@danblah This is some work I believe. Setting up a separate fund/round/forms for this is of cource possible but I assube that is not an option.

You want to add three application forms to a fund. One concept note form . Two proposal forms, one small and one large. Then when an Concept note is invited for a proposal the system shoul look at the amount requested and for 100k or less pick the small form and for larger amounts pick the larger form.

In another issue you also mentioned wanting to allow the lead to pick between the different proposal forms manually when progressing an application, is that still so?

**Comment by tmsndrs** [comment]
Currently the field in the concept note that asks for the amount is also not specifically in $ so we would need to change that if we want to use that value here.

**Comment by danblah** [comment]
Would this be easier if which proposal to create and go to next was a manual process? maybe something that a manager selects/checks at the invite to proposal status update?

How about this workflow...

* Manager creates three application forms (concept note, standard proposal, small proposal)
* Manager creates/edits fund page which now has a non-required field within the forms box for "Small amount form" 
* Manager selects the appropriate form if the fund requires.
* When a submission is within a round that has a small amount form set, after the manager selects "Invite to proposal" and progress, add an option for the manager to select "Use small amount form".
* Upon sending of determination, the small amount form is used to create the proposal the applicant is invited to complete.

**Comment by danblah** [comment]
@frjo, bumping this.

**Comment by danblah** [comment]
Adding this to the mini sprint @frjo and @fourthletter cause its needed. We should probably start a discussion here on how best to do this.

**Comment by todd-dembrey** [comment]
@danblah I think your implementation in https://github.com/OpenTechFund/opentech.fund/issues/717#issuecomment-448318747 is a reasonable approach.

There is an assumption that each phase has 1 form associated with it, I'll need to have a look at how much this would need to change. There is a helper method associated with the form selection for applications so shouldn't be too onerous.

I think we should address this process in two tickets:
1. Ability to include multiple forms at the proposal stage (admin configuration) and a field for selecting the proposal form to use (whilst inviting to proposal). 
2. Ability to vary the Proposal form based on a specified criteria.
  * Criteria to be defined, but would use `MustIncludeBlocks` e.g. `ValueBlock` and a gt/lt selector for variing the value.
  * Adding additional criteria (e.g. geographic/category) could be interesting but might be better handled using the manual assignment process developed in 1.

**Comment by frjo** [comment]
I was pondering a simpler solution with the field groups + trigger fields we added some time back. But for this separate forms is probably better.

**Comment by gibbsmaya** [comment]
Initial work for this is for Todd to outline implementation plan for this work in enough detail so that it can potentially be undertaken by someone other than him.

**Comment by todd-dembrey** [comment]
As the application holds a reference to the form that the user is responding to we only need to make the choice of which forms to use once. So the bulk of this work will focus on storing the form-stage data and the ability to then vary that form on progression. I have outlined below the various changes that are needed as i see them.

**Add in the concept of a stage to the application model.** 
This will involve adding in some concept of stage on the model definition. 
  
* The simplest approach would be adding a `IntegerField` which can be used to represent the Stage that the form is associated with. However this is not a nice user experience.
  * My preferred approach would be to convert the forms field to include a stage block which could give the following data structure:
```
- Application
    - Stage Block
         - Form Block
             - Form 1
    - Stage Block
         - Form Block
             - Form 2
             - Criteria
         - Form Block
             - Form 3
```
* The criteria would be added at a later date and this first implementation would focus on the adding in the stage with multiple forms. 

**Add in the ability to vary the destination form from the determination page.**
  * I was thinking that we could reuse the modal view implemented in the batch determination workflow (see here: https://github.com/OpenTechFund/opentech.fund/blob/a4a9211f0be0851192c6eef9806628eaa8158afd/opentech/apply/determinations/templates/determinations/includes/batch_determination_confirmation.html#L1) 
  * Alternatively we could add this at the end of the determination form, but separating this from the main determination flow perhaps makes the most sense.

**Pass the chosen form from the determination view into the stage progression.** 
  * I have already implemented the changes to ensure that we can pass the kwargs from `perform_transition` through from here. 
    * https://github.com/OpenTechFund/opentech.fund/blob/4a115aef7cae4ec4d63945a6d8dfc1175a099067/opentech/apply/determinations/views.py#L145
    * https://github.com/OpenTechFund/opentech.fund/pull/1227
  * the `progress_application` method can then be updated to pass the form chosen through to the `get_defined_fields`
    * https://github.com/OpenTechFund/opentech.fund/blob/a4a9211f0be0851192c6eef9806628eaa8158afd/opentech/apply/funds/models/submissions.py#L462
  * the `get_defined_fields` will need to be updated to handle the choice between multiple stages where currently it always assumes one form per stage
    * https://github.com/OpenTechFund/opentech.fund/blob/3858f86bb5f1eec4b17122bce84691a7a56fc1cc/opentech/apply/funds/models/utils.py#L80-L85

**Comment by frjo** [comment]
@Parbhat I talks this over with @saoun, @fourthletter and @danblah in a meeting last week and this is what got decided:

* Ability to add any number of proposal forms to a found/round.
* On the determination when staff "invites to a proposal" add a field to select the proposals forms. 
    1. The field should only show if there are more than one option.
    2. Please make the first proposal form the default.

**Comment by Parbhat** [comment]
Requirements look good. Thanks.

**Comment by frjo** [comment]
@danblah @saoun @fourthletter This is now ready to test on https://test-apply.opentech.fund. I believe @Parbhat have implemented it really nicely.

1. Edit a Fund that has Concept/Proposal and add any number of 2 stage proposal forms.
2. Create a new round for that Fund.
3. Submit a Concept.
4. Invite that Concept to a Proposal and you find a proposal form select field at the top of the determination form (if there are more than one proposal form).
5. Pick the Proposal form you want for the submission in question.
6. Conform that the proposal have the correct form and that it can be edited/reviewed etc. as normal.

**Comment by fourthletter** [comment]
Dearest @frjo I've added 2 stage proposal forms to 1) IFF [https://test-apply.opentech.fund/admin/pages/822/edit/?next=/admin/funds/round/] and 2) Rapid Response [https://test-apply.opentech.fund/admin/pages/823/edit/?next=/admin/funds/round/]

While these forms are almost perfect in every way, how do I add forms to the "No, I'm smaller than a bread box" option? 

Example:
https://test-apply.opentech.fund/rapid-response-archive-fund/

![image](https://user-images.githubusercontent.com/20019656/63390455-2e804f80-c37d-11e9-9e22-f1aceca7e438.png)

**Comment by frjo** [comment]
@fourthletter That is not how it's supposed to work. I have set up an example according to my comment above on test now.

This is what I did:

1. Added a second proposal form to the Internet Freedom Fund, see https://test-apply.opentech.fund/admin/pages/729/edit/. For this example I added the "Fellowship Proposal" application form, in reality you would most likely build a custom form to add.
2. Create a new IFF round, see https://test-apply.opentech.fund/admin/pages/823/edit/
3. Submit a concept note for the new round, see https://test-apply.opentech.fund/apply/submissions/76/

You can now go to https://test-apply.opentech.fund/apply/submissions/76/ and invite it to a proposal.

On the Determination form you then get there are a new popup meny at the top where you can pick one of the proposal forms that was added to the Fund in step 1.

**Comment by fourthletter** [comment]
I tested this issue and results were successful. Thanks!

[] Staff sees new popup menu with two different proposals options on determination form
[] Staff sends out proposal option A to applicant A
[] Staff sends out proposal option B to applicant B
[] Both applicants received correct proposals. 
[] Applicants were able to submit proposals to system

**Comment by frjo** [comment]
@fourthletter would it work to have this information show up on the determination? Or can you suggest another place?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
