### ISSUE TITLE
Slack notifications for submitted reviews on an application aren't being delivered 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#719]
See this application specifically: https://apply.opentech.fund/apply/submissions/3363/

**Comment by jheretic** [comment]
A previous update erroneously updated to Coffeescript v2.x, which hubot-slack is not compatible with. I mistakenly pushed up a branch to testing that didn't include this dependency update, so I didn't catch it. Should be fixed now on live per https://github.com/OpenTechFund/botf/commit/a2c34bf747bc024606b0c5aee228854a5ae77b60
