### ISSUE TITLE
When moving a Red Team Lab application into AC review, it sends team members an email and slack notification saying they need to do a review. Only AC members should get that notification.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#727]

**Comment by frjo** [comment]
@danblah This is true for all submissions with external reviewers. We should change so the notification always only goes to the external reviewers and not to OTF staff. Sounds good?

**Comment by danblah** [comment]
That sounds great, thanks!

**Comment by frjo** [comment]
@danblah Is the Slack notification needed at all? It looks like this:

[submission.title] is ready for review. The following are assigned as reviewers: [reviewers]

If we remove the staff from the list of reviewers no Slack users will remain, only external reviewers.

**Comment by danblah** [comment]
Wait, I do think we want existing slack notification. Maybe something that says:

[submission.title] is ready for AC review. The following are assigned as reviewers: [reviewers]
