### ISSUE TITLE
Create a permission and an interface for deleting submissions, giving that permission to team and admins, and notification on action to channel

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#728]

**Comment by Parbhat** [comment]
PR #1145

**Comment by frjo** [comment]
@danblah @fourthletter Deleting a submission will also delete all related determinations, comments, reviews etc.

Do you still want to be able to delete any submission or should we limit it somehow?

Are going to give the delete permission to group "Staff"? By default only super admins can delete.
