### ISSUE TITLE
Ability to reference other submissions in reviews or comments like you can with github issue comments

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#732]

**Comment by frjo** [comment]
@danblah I can easily add a filter that expands like this:

    #123 -> <a href="/apply/submissions/123/”>The submission title</a>

Would that work for you?

**Comment by danblah** [comment]
That is a good start, lets do it.

Lingering concerns/ideals:

- There would be no validation the number is an actual submission
- The current titles don't make it easy to see the submission number (see githubs greyed out issue after the title)
- Would be nice if typing # brought up a search matching either number or title text (just like github)
