### ISSUE TITLE
Language of Determination (Approved) [High/Bug] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#746]
-=Sensitive=-
No

-=Reporter=-
Tara ()

-=Ideal deadline=-

-=Who's affected=-
OTF team, Applicants

-=Description=-
When sending an invite for proposal, the dropdown in the determination message says "approved". This should say "Invite to Proposal" 

-=Objective=-

-=Additiional info=-

-=Timestamp=-
2018-11-27T13:10:03.942Z

**Comment by frjo** [comment]
It’s the same determination that is used for all submissions so there is no easy way to make this happen.

**Comment by danblah** [comment]
Ideally, for all 2-stage submission workflows, the final state for the 1st stage submission is "Dismissed" or "Invite to proposal" and the final state for the 2nd stage submission is "Dismissed" or "Approved". If it's not a trivial fix, do you have other suggestions to ensure applicants aren't confused about what just happened?

**Comment by frjo** [comment]
So it is the language in the e-mail you are concerned with and not the pop up menu mentioned in the issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danblah** [comment]
That's right, the user facing language is most important here.
