### ISSUE TITLE
Audit of Automated Emails [Medium/Improvement] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#747]
-=Sensitive=-
No

-=Reporter=-
Tara ()

-=Ideal deadline=-

-=Who's affected=-
OTF team, AC Members, Applicants, Service partners

-=Description=-
Some of the feedback we got from AC and Applicants is that they are confused by some of the automated emails vs. OTF team communication, and since we don't really have visibility on automated emails, we would like a list of all emails sent out automatically by the system to review. 

-=Objective=-
To streamline communication between OTF and others, automated and not. 

-=Additiional info=-

-=Timestamp=-
2018-11-27T15:51:08.338Z

**Comment by frjo** [comment]
### Applicants:

1. When first submitting an application applicants get a confirmation notification "We appreciate your Internet Freedom Fund application submission…”. They also get an notification with account details at the same time.
2. When a submission chage state without an determination (that send out its own notification) a notification is sent out to the applicant "Your application has been progressed from…”
3. All detarminations send out a notification to the applicant "Your application has been reviewed and the outcome is…”
