### ISSUE TITLE
Side-by-Side Compare Revisions [Medium/Improvement] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#748]
-=Sensitive=-
No

-=Reporter=-
Tara ()

-=Ideal deadline=-

-=Who's affected=-
OTF team

-=Description=-
Can we have side-by-side diffs similar to Drupal/Wikipedia rather than the current inline diff style? 

-=Objective=-
side-by-side is better for comparing written applications, vs. in-line which is better for comparing code. 

-=Additiional info=-

-=Timestamp=-
2018-11-27T15:56:19.567Z

**Comment by frjo** [comment]
@Parbhat Could you take a look at this and see if you can build something that works better?

Also see https://github.com/OpenTechFund/opentech.fund/issues/749 that is related.

**Comment by Parbhat** [comment]
@frjo Confirming the revision discussed here is for Apply site `/apply/submissions/<id>/revisions/compare/<id>/<id>/` and not Wagtail page revisions.

**Comment by frjo** [comment]
@Parbhat Yes, it's submissions on the Apply site, i.e. /apply/submissions/<id>/revisions/compare/<id>/<id>/.

**Comment by Parbhat** [comment]
Issue related to #749 and PR #909

**Comment by frjo** [comment]
Also add non text field comparison to the diff view. It was disabled in https://github.com/OpenTechFund/opentech.fund/pull/909 since it did not work.

**Comment by frjo** [comment]
@fourthletter wrote on #1132:

> This is not a bug. A few team members find it difficult to read revised applications.

> 1) Side-by-Side view to compare original and revised text OR 2) change current green and pink highlight over text to increase readability of revised text.

**Comment by frjo** [comment]
@fourthletter Changing colours are easy, any idea what colours you would prefer? Mainly lighter ones?

**Comment by fourthletter** [comment]
A majority of team members are interested in side-by-side comparison views. 

IF you think changing colors would NOT interfere with above work, a few shades lighter would help. Thanks!

**Comment by frjo** [comment]
Changing colours takes a few minutes so a quick way to improve things until we have time to build a side by side diff. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
I have implemented a *first stab* of this on test now. It does not work correctly yet!

It looks ok for simple plain text entries but on the big formatted text blocks it collapses.

Just see this simple example https://test-apply.opentech.fund/apply/submissions/10/revisions/compare/108/107/.

I believe the basic functionality is there. But I believe I will need some help to get the system to do a proper diff between blocks of html formatted text.

**Comment by frjo** [comment]
What I would like to know at this stage is:

* Does this look something like what you had in mind?

**Comment by frjo** [comment]
I have implemented plain text side by side diff now.

**Comment by saoun** [comment]
Looks good @frjo ! Did you end up stripping the html formatting ?

**Comment by fourthletter** [comment]
Acceptance criteria were visible and functional during test. Thanks!

The side-by-side view feature will be enhanced in the future to increase visibility of rich text.
