### ISSUE TITLE
Attachments in Revision Comparison Page are malformed/don't work [High/Bug] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#749]
-=Sensitive=-
No

-=Reporter=-
Tara ()

-=Ideal deadline=-

-=Who's affected=-
OTF team

-=Description=-
Attachments to applications in the revision comparison view are malformed, including some weird output and don't work when you click on them to view the attachment. 

-=Objective=-

-=Additiional info=-

-=Timestamp=-
2018-11-27T16:06:04.547Z

**Comment by Parbhat** [comment]
@frjo Seems that we can close this Issue after PR #909. And can cover non-text field comparisons in a separate issue or as part of #748.

**Comment by frjo** [comment]
Let's do that.
