### ISSUE TITLE
Verify contact information (email address and/or Signal number) before application can be reviewed and notifications are sent out  [Low/New feature] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#750]
-=Sensitive=-
No

-=Reporter=-
Blah ()

-=Ideal deadline=-

-=Who's affected=-
OTF team, Applicants

-=Description=-
We have a number of applications creating user accounts with invalid email addresses, either in error or deliberately. The result is either spam submissions (that we can't delete) or actual submissions that don't get any notifications or login details.

* Add a step in the submission workflow that sends a confirmation msg for applicants to respond to
* Present a page after submission that allows applicants to either re-send verification if they don't get it or to submit an issue/help ticket for us to look into if they never get it
* Hold/flag unverified submissions for round leads to easily see/address
* Allow applicants to change their email or add a signal number that kicks-off the verification workflow again

-=Objective=-
* Ensure applicants are getting notifications
* Reduce spam/test submissions

-=Additiional info=-

-=Timestamp=-
2018-11-27T16:12:21.209Z

**Comment by frjo** [comment]
The e-mail field should have a backend valid e-mail address verification attached to it. Now it relies on frontend HTML5 ”email” field typ verification that is easy to sidestep and is lax.

**Comment by frjo** [comment]
The pr https://github.com/OpenTechFund/opentech.fund/pull/751 takes care of validating the e-mail field on submission forms.
