### ISSUE TITLE
Speed up submission table/page and search

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#762]
The page and search function at /apply/submissions/ is to slow.

This view uses django-tables2 and django-filter, start looking at:

https://github.com/OpenTechFund/opentech.fund/blob/b6880d1127d0fd9a61fd0779d2dfc7fbcb2f4a30/opentech/apply/funds/tables.py#L130-L143

With well over 3000 submissions a search takes around 5-6s. Just loading the page takes 4s.

The functionality with the filters and the search is good, just the speed is a problem.

**Comment by todd-dembrey** [comment]
#763 should hopefully have improved matters slightly. 

I'll have a look at the queries next week to see if there is an obvious bottle neck that can be addressed.
