### ISSUE TITLE
Round management designs

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#764]
Hi @danblah ,

Here's the (partly) clickable prototype!

https://invis.io/KZPIO1NENQJ#/335805634_Submissions

We've got 
Submissions page
Dashboard
Fund list <---shows batch actions
Fund grid 
Status list
Status grid <----this is the screen for the review call

As discussed, we already have some small changes we need to make to these as we have been going through development planning and areas that need expanding, but I would like these to act as our design concept and for you to agree to these as our basic page structure and design. We will define exact functionality in our written spec and can then tweak design as necessary during the build process.

Would be great to get any feedback from you and confirmation on the above approach by end of Monday next week.

Thanks,
Maya

**Comment by gibbsmaya** [comment]
Hi Dan,

Following our call earlier this week, can you please confirm on this issue that you are happy for us to proceed on this design concept and close down this issue?

Thanks,
Maya

**Comment by danblah** [comment]
All good on our end!
