### ISSUE TITLE
Workflow status definition

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#765]
Hi @danblah ,

Here is Todd's [document](https://docs.google.com/document/d/1tVtSb1zLljcZqpP6Qf1T2m2Ebjp0uFLcjpT0w7v2EWY/edit) which outlines:

- the current statuses within the system including their intended usage and behaviour
- our proposed changes/additions to the statuses

Please review these statuses and proposed changes with the team and feedback to us whether you think these proposed changes would fit your workflow or whether any further discussion is needed. Please feed back to us by end of Monday next week.

There are also two associated tasks which we describe in the document:

- applicant friendly statuses
- automated transitions between statuses

Once we agree on the internal OTF statuses I suggest we then tackle these points.

Thanks,
Maya

**Comment by danblah** [comment]
Yep, we're all good here as well.
