### ISSUE TITLE
Functional Spec | Winter 2019

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#767]
The functional spec for the sprints is included in a link below.

Could you please review and comment on this by Tuesday 18th December in order for us to discuss in the call on Wednesday.

https://docs.google.com/document/d/1KzNNVXD7sylvr9B7GAMlOgKvpAn9aymeTwhUbWTikWk/edit?usp=sharing

**Comment by todd-dembrey** [comment]
@danblah We have updated the functional spec with the extra requirements around Review Roles and Review Consensus that we discussed in the last meeting.

If you could review and confirm this is how you expect it to work that would be great.

**Comment by gibbsmaya** [comment]
Just a further comment on this to give us the go official go ahead on this and also identify if there are any areas that are lower priority.

**Comment by danblah** [comment]
This looks good to me, thanks!
