### ISSUE TITLE
API spec | Winter 2019

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#768]
Below is the API spec I think will be required in order to complete the work outlined in the functional spec #765.

It looks like some of the queries on submissions (status and active) will need to be added after we some work in Sprint 1, but otherwise the rest looks to be independent.

Would appreciate some feedback/comments on this.

https://docs.google.com/document/d/1rh2q7VCxUFu9wem06Z5rutspEJlFBuzgBIUoZGNPM78/edit?usp=sharing

**Comment by frjo** [comment]
I have added the following domains to Cloudflare and Heroku:

* api.opentech.fund
* test-api.opentech.fund
* dev-api.opentech.fund
* sandbox-api.opentech.fund
