### ISSUE TITLE
We need a new role / user type called Host Organization, that can be assigned (added to) submissions from funds/fellows, that can submit reviews and refine submission like an applicant

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#771]

**Comment by danblah** [comment]
* People in this role will be assigned to specific submissions, they won't have access to all submissions within a specific round/fund.
* Managers need the ability to assign them regardless of submission status, unlike AC members.
* They need the ability to both submit reviews and edit the submission
* For two-stage application funds, this would apply to the second-stage application (the proposal)
* It would be nice if this could also apply to the first-stage application as well where person's access/permissions carry over to the second-stage application 
* Ideally, the manager can invite users and associate them to a fund like we do for AC members, so that when assigning them to submissions, there is a short list to choose from

**Comment by danblah** [comment]
Bumping this... we need this before the coming ICFP deadline closes (or nearly after), this months end.

**Comment by newbie15423** [comment]
Noting that it would be much better if this functionality includes "the first-stage application as well where person's access/permissions carry over to the second-stage application" at the outset.
