### ISSUE TITLE
Setup for React

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#772]
Task list

- [x] Update CI to build React
- [x] Create basic React project
- [x] Configure development environment for React

**Comment by gibbsmaya** [comment]
90% of react setup done but need Chris to review local dev environment setup in new year.

**Comment by todd-dembrey** [comment]
This is now working. see #780 for implementation

**Comment by chris-lawton** [comment]
Testing and working as expected
