### ISSUE TITLE
Ability to deploy heroku review apps using either repo test data or a teams private test data

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#777]
See https://devcenter.heroku.com/articles/github-integration-review-apps

**Comment by frjo** [comment]
Our main issue here is that this app needs two domains to function and review apps only get one.

There is also some settings that needs to be done for wagtail sites etc that involves the domain name.

**Comment by saoun** [comment]
@frjo can we close this, or is there something to be one here ?
