### ISSUE TITLE
Approved Proposals Should be Editable [High/Bug] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#781]
-=Sensitive=-
No

-=Reporter=-
Tara

-=Ideal deadline=-
12/31/2018

-=Who's affected=-
OTF team, Applicants

-=Description=-
Proposals in "Approved" state can not be edited by staff or applicants. We need to edit them for post-approval fixes. 

-=Objective=-

-=Additiional info=-

-=Timestamp=-
2018-12-27T16:14:08.495Z

**Comment by frjo** [comment]
@danblah Is this only for proposals or also for the other applications? I guess yes.

Do staff need to edit concept notes that have been invited for proposal? I guess not.

I have made an PR according to my guesses https://github.com/OpenTechFund/opentech.fund/pull/975.
