### ISSUE TITLE
Design: applicant friendly states

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#786]
We have agreed on the following new statuses for the OTF workflow which we have provisionally mapped to applicant friendly statuses:

Old status | New status | Applicant statuses (draft)
-----------|------------|-------------------
In Discussion | Screening | Internal Review
Internal Review | Internal Review | No change for the applicant (remains Internal Review)
In Discussion (2) | Ready For Discussion | No change for the applicant (remains Internal Review)
AC Review | AC Review | AC Review
In Discussion (3) | Ready For Discussion | Internal Review
No current state | Ready for Determination | No change for the applicant (remains Internal Review)
Accepted/Dismissed | Accepted/Dismissed | Accepted/Dismissed

 (better representation of this in a table in this doc on p3 https://docs.google.com/document/d/1tVtSb1zLljcZqpP6Qf1T2m2Ebjp0uFLcjpT0w7v2EWY/edit)

Review needed of the draft applicant friendly states, comparing these to the workflow defined for an applicant in the application guide to ensure consistency. This could result in either changes to the application guide, changes to the system applicant states or both.

**Comment by tmsndrs** [comment]
Status timeline for applicants 

- Concept note received
- OTF review
------------------------------
- Preliminary determination 
-  Submit proposal 
- Proposal received 
- OTF Review 
------------------------------
- AC Review
------------------------------
- Final determination

**Comment by gibbsmaya** [comment]
Thanks @tmsndrs .

@danblah can you please review this and confirm if you are happy with the above for the states the applicant sees?

**Comment by gibbsmaya** [comment]
Hi @danblah 

Just to get you know we are going ahead with this for now and can pick up any labelling changes during testing of the work which is being undertaken in this sprint. Can you please confirm you are happy with this and we can close off this issue?

Thanks,
Maya

**Comment by danblah** [comment]
@fourthletter, @tarakiyee, and @arduina as a heads up here. I'm all good with this.

**Comment by gibbsmaya** [comment]
Great, thanks @danblah . Will close this off and any further feedback can be picked up in the testing of the actual implementation of this.

**Comment by tarakiyee** [comment]
I'm sorry, but what does "preliminary determination" mean? Also, for applicant facing "final review" might make more sense than final determination.

**Comment by tarakiyee** [comment]
I'm sorry, but what does "preliminary determination" mean? Also, for applicant facing "final review" might make more sense than final determination.

Also maybe it makes more sense to go directly to OTF review instead of showing "proposal recieved".
