### ISSUE TITLE
Design: Notes on activity feed

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#787]
Design required for notes tab on activity feed. Notes to be grouped by date added. This needs to be considered both in the main activity feed present at the bottom of pages, and also on an individual submission page with the tabs across the top. Existing styles to be used where possible.

**Comment by tmsndrs** [comment]
![submissions-with-notes](https://user-images.githubusercontent.com/7290588/50701157-a2ffbb80-1044-11e9-8a87-2894eb4da2d9.png)

**Comment by tmsndrs** [comment]
Perhaps we need more meta data against each note other than just who made the note and which application it was on but didn't want to add it unnecessarily.
