### ISSUE TITLE
New filter behaviour and styles

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#789]
#Acceptance criteria

- [x] Filter hidden by default displaying filter icon and text
- [x] Filters displayed as per design when filter icon clicked
- [x] When filters displayed, 'clear filters' text is displayed and if clicked any selected filter is removed and filters are hidden
- [x] Selected filters require 'filter' button to be clicked to apply
- [x] Mobile behaviour TBC - check with Tom S (Agreed to keep current mobile behaviour where filters go fullscreen)
- [x] Filters match design
- [x] QA criteria satisfied

Designs:
![50698632-52d12b00-103d-11e9-8e03-f12258f10c24](https://user-images.githubusercontent.com/19690895/50701289-40f38600-1045-11e9-8c49-b39dfc18bcea.png)
![50698633-52d12b00-103d-11e9-8e22-69208f679121](https://user-images.githubusercontent.com/19690895/50701291-42bd4980-1045-11e9-9054-ed4eded950f0.png)

**Comment by chris-lawton** [comment]
> Mobile behaviour TBC - check with Tom S
Agreed to keep current mobile behaviour where filters go fullscreen

**Comment by chris-lawton** [comment]
This is now ready for review on dev - https://dev-apply.opentech.fund/apply/submissions/

**Comment by gibbsmaya** [comment]
Hi Chris,

This all functions as expected. only think I noticed is there seems to be a bit of a slow transition when filtering where you see the page reloading and the new page 'sliding over' the current page. Is there anything we can do about this?

Also, please ensure this is code reviewed and then we can move this forward.

Thansk,
Maya

**Comment by chris-lawton** [comment]
Hi @gibbsmaya, 

Are you referring to the slide down once you've filtered and the page has reloaded - https://drive.google.com/open?id=1npQhcrxpnqF1vtDe5zRZD1ab1GaPCBpn

The functionality behind that is checking for a query string on page load `/?fund=15` and then applying the class if there is one. Off the top of my head I can't think of a way to avoid this but can do some research if you want. If this page is heading in the direction of using React in the future then it would eradicate this. 

Will assign to Beth for code review once she's been added to the project, which is in progress. 

Cheers,
Chris

**Comment by gibbsmaya** [comment]
Thanks Chris, will leave for now. Leaving with you to assign to Beth.

**Comment by chris-lawton** [comment]
Assigning to Beth for review - https://github.com/OpenTechFund/opentech.fund/pull/797

**Comment by hippogriffic** [comment]
reviewed, approved 👍

**Comment by chris-lawton** [comment]
Hi Maya,

This has now been reviewed and changes from that are now on dev. 

Thanks,
Chris

**Comment by gibbsmaya** [comment]
Hi @fourthletter and @danblah 

This bit of work is ready for you to test on the test site. This work encompasses the new filter styling and behaviour on tables throughout the site. The best place to test this for now is on the main submissions table at https://test-apply.opentech.fund/apply/submissions/. Note this behaviour will be reused throughout other pages where filters are required as per the designs (though these have not yet been implemented). Please also note that this testing is solely of the filter, not the search which sits alongside it. Please test these against the acceptance criteria noted in the initial issue description (note you can ignore the QA checklist that is a dev only thing, so just the list under 'Acceptance criteria') and compare the implementation to the design which is also screenshotted and linked to there.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by danblah** [comment]
Confirming, all looks good here... accepted. Seconding that noticeable delay when applying a filter as well as clearing the filter.

**Comment by gibbsmaya** [comment]
Thanks @danblah. I will raise the delay as a separate issue and we can look into it if time later in the sprint cycles. 

Assigning to @todd-dembrey to arrange deployment to production.
