### ISSUE TITLE
Switcher styling for submissions by round list view - detail view

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#790]
**Acceptance criteria**

- [x] Two buttons switch between list view and detail view
- [x] Buttons styled as per design
- [x] Active state is white
- [x] Hover state TBC - check with Tom S
- [x] QA criteria satisfied

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805632
![screen shot 2019-01-04 at 15 47 18](https://user-images.githubusercontent.com/19690895/50696699-0f27f280-1038-11e9-8dba-ffd58a0b45b8.png)

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Ready for review here - https://github.com/OpenTechFund/opentech.fund/pull/824

The MR is mainly made up of React, Webpack and Template changes so suggest Todd reviews this one .

**Comment by todd-dembrey** [comment]
I have reviewed and deployed. This is now with you @gibbsmaya 

Example page here: https://dev-apply.opentech.fund/apply/submissions/rounds/733/

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah 

This work is now ready for testing. This is a very isolated bit of testing of the switcher buttons between the Submission by round list page (which you will have been looking at as part of testing https://github.com/OpenTechFund/opentech.fund/issues/791) and what will be the submission by round detail view (currently a placeholder page).

You can test this here https://test-apply.opentech.fund/apply/submissions/rounds/732/ which is the IFFund-2018-11 round and you are testing the switcher icons in the top right corner. Please test these against the acceptance criteria noted in the initial issue description and compare the implementation to the design which is also screenshotted and linked to there.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by danblah** [comment]
Button works, looks good, accepted. Looking forward to that new view!

**Comment by gibbsmaya** [comment]
Thanks @danblah . Assigning to @todd-dembrey to arrange deployment to production.
