### ISSUE TITLE
Table on submission by round list view

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#791]
**Acceptance criteria**

- [x] Table contains submission within selected round
- [x] Changes to existing submission table:
- [x] Remove Round column
- [x] Remove Fund column
- [x] Remove Lead column
- [x] Remove Round Filter
- [x] Remove Fund Filter
- [x] Remove Lead Filter

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805636

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
This is now available for testing on dev https://dev-apply.opentech.fund/apply/submissions/rounds/18/

It might also be worth confirming the behaviour of https://dev-apply.opentech.fund/apply/submissions has remained the same.

**Comment by todd-dembrey** [comment]
@emullaney is happy with this. The react is reviewed as part of #789 

@gibbsmaya are you happy with the testing?

**Comment by gibbsmaya** [comment]
Looks good to me. Have tested all acceptance criteria above on new data so https://dev-apply.opentech.fund/apply/submissions/rounds/732/ and https://dev-apply.opentech.fund/apply/submissions/rounds/733/ as example rounds. Happy for this to be marked as done once code review complete and responded to.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah 

This work is now ready for testing. This is a new page on the site displaying a view of submissions within a specific round. There is currently no access to this page via a link on the site (later this will be accessed via the dashboard) but for now we would like you to test the functionality of the page displaying the table listing the submissions within the specified round.

An example of this page can be found here https://test-apply.opentech.fund/apply/submissions/rounds/732/ which is the IFFund-2018-11 round. The only other round which is currently in the test site is CIFund-2018-11 which can be found here https://test-apply.opentech.fund/apply/submissions/rounds/733/. You could test this further by creating a new round and some test submissions against that round. You could then access the page by using the url format of the above links but with the wagtail id of the new round you have setup (you can access this by noting the id in the url of the round page you have created when editing that round page).

Please test these against the acceptance criteria noted in the initial issue description (note you can ignore the QA checklist that is a dev only thing, so just the list under 'Acceptance criteria') and compare the implementation to the design which is also linked to there.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by danblah** [comment]
I'm going off this: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340972072

This looks good per the acceptance criteria, all good to push to live. Looking forward to this views maturity!

**Comment by danblah** [comment]
Button works, changes view (doesn't show anything in the horizontal view yet).

**Comment by gibbsmaya** [comment]
Thanks @danblah . Assigning to @todd-dembrey to arrange deployment to production.
