### ISSUE TITLE
PDF output format should be 8 x 11" and not A4

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#796]
PDF format in WebApp is currently size A4, please change to size 8 x 11" because of printing issues. Thank you.

**Comment by frjo** [comment]
@fourthletter What is the URL to a PDF you have a problem with?

There are no feature yet to produce PDF:s from the new OTF Web App but there are in the old one.

**Comment by fourthletter** [comment]
@frjo Thank you for clarifying. This was an issue in the old web app that we would like to correct in the future.

**Comment by frjo** [comment]
@fourthletter I have changed the PDF print settings in the old Drupal site to ”Letter” instead of the standard A4 size.

A4 is the standard in most countries so they will likely have issues printing now. On the other hand I do not believe there are many people using this feature.
