### ISSUE TITLE
Screening: Wagtail interface and action on submission page

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#805]
Screening will allow Admins to apply a taxonomy to submissions. This taxonomy will not have any effect on business logic and will purely act as meta-data on the submissions.

**Acceptance criteria**

- [x] New taxonomy added to Wagtail 'Screening'
- [x] Taxonomy controlled through Wagtail by admin role only
- [x] New action “Screen application” added to the submissions detail page for roles OTF staff and admin
- [x] "Screen" Action allows selection of one taxonomy term
- [x] Record activity when screening action is taken
- [x] Screening cannot be changed except by admin if the submission has received a final determination (Accepted/Dismissed/Invited to Proposal).

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
I have reviewed @emullaney code and apart from some changes to the tests i'm happy.

@gibbsmaya This is now deploying to the dev environment.It'll be ready for testing soon.

**Comment by gibbsmaya** [comment]
This looks good to me and all works as expected. `one thing I can't test is that the activity has been recorded for the screening activity but I am happy to check this off and retest once it is displaying in the activity feed as per #806 .

@emullaney , can you please confirm that the QA criteria has been done by ticking off the checklist above?

Question for @todd-dembrey  - I was expecting to see the screening taxonomy within the apply section as that is where OTF manage all of their apply config. Is it easy to move it into here?

**Comment by todd-dembrey** [comment]
Good spot on the location of the screening. 

Yes, lets move it from [here](https://github.com/OpenTechFund/opentech.fund/pull/831/files#diff-69d941dc40842a407580b149fc712c63) which handles the public taxonomy to [here](https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/funds/admin.py) which is more focused on the apply side

**Comment by emullaney** [comment]
@todd-dembrey I've moved the Screening taxonomy into the Apply admin.

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now deployed on test

**Comment by fourthletter** [comment]
I am able to view and click on the "Screen application" and "Screening status" as well as see the "in remit" within the drop down menu, **but am not able to see this new option under the Apply menu in the Wagtail admin** at this point. Thanks.

**Comment by gibbsmaya** [comment]
Hi @fourthletter ,

That is the behaviour I expect. Currently you have a 'staff' role which gives you access to the screening actions. As per the acceptance criteria - it is only the 'admin' role that has access to create the actual screening statuses within the Wagtail admin. I suggest that either @danblah tests that area of functionality, as an admin, or can otherwise give you admin access if relevant.

Thanks,
Maya

**Comment by danblah** [comment]
As an admin, I'm also not seeing the taxonomy option. I only see Person and and News types.

**Comment by gibbsmaya** [comment]
As mentioned on the call - this lives in the Apply menu not the Taxonomy menu. Dan confirmed on the call that this is visible to him in this location. @danblah can you confirm then if you are happy for us to mark this as done and deploy to production?

**Comment by danblah** [comment]
Nvm, see it and can edit it under apply. All good here!

**Comment by gibbsmaya** [comment]
Thanks @danblah . Assigning to @todd-dembrey to arrange deployment to production.
