### ISSUE TITLE
Screening: Filters and display

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#806]
**Acceptance criteria**

- [x] Submission detail page will be updated to include the outcome of the screening in the sidebar (as per determination block, placed above determination block)
- [x] Screening block on submission detail page only visible to OTF staff and admin
- [x] 'Screening' to be added as a column in submissions table to display outcome of screening (currently called remit in designs) 
- [x] 'Screening' to be added as filter on submissions table 
- [x] Screening activity will be visible in the activity feed for OTF Staff
- [x] This taxonomy is not visible to the applicant at any time

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805636

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now deployed to dev for testing

**Comment by gibbsmaya** [comment]
This all looks good to me. Marking as done.

**Comment by gibbsmaya** [comment]
@todd-dembrey please can you deploy this to test?

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work follows on from #805 , and consists of displaying the screening action on the submission page, the submissions listing and the activity feed, as well as adding a filter for the screening outcome to the submissions listing.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by danblah** [comment]
See https://test-apply.opentech.fund/apply/submissions/4/#activity-feed, when applying screen term, the activity feed fails to load, shows nothing for team member. Aside from that, all other criteria is met.

**Comment by gibbsmaya** [comment]
THanks for the spot Dan. Strange as it is working in other cases, see https://test-apply.opentech.fund/apply/submissions/6/#activity-feed. @emullaney @todd-dembrey can one of you take a look at this please?

**Comment by todd-dembrey** [comment]
@gibbsmaya I've fixed this on dev. Once #895 Is approved I'll get it onto test and tidy up the data there.

**Comment by fourthletter** [comment]
All acceptance criteria listed above are visible and functional during my testing. Thank you!

**Comment by todd-dembrey** [comment]
#895 is now deployed to test and the activity feed is now rendering for https://test-apply.opentech.fund/apply/submissions/4/#activity-feed

**Comment by gibbsmaya** [comment]
Thanks @todd-dembrey . @danblah @fourthletter can you confirm this is now working for you and confirm if you are happy for this to be moved into production?

**Comment by fourthletter** [comment]
- All acceptance criteria listed above are visible and functional during my test today. Thank you! 
- The activity feed blah mentioned in an earlier comment [https://test-apply.opentech.fund/apply/submissions/4/#activity-feed] successfully loaded with the most recent update during today's test.

**Comment by gibbsmaya** [comment]
Thanks @fourthletter, moving to @todd-dembrey for deployment to production
