### ISSUE TITLE
Screening: Action interface polish

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#807]
Front end review and any tweaks for new screening action and associated displays. To review:

- [x] Screening action button on submission detail page, including performing the action
- [x] Outcome of the screening in the sidebar on submission detail page
- [x] 'Screening' column in submissions table
- [x] 'Screening' filter on submissions table
- [x] Screening activity in the activity feed for OTF Staff

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by gibbsmaya** [comment]
@chris-lawton this is now ready for review. All looks pretty good so don't know if there will actually be any work for you here.

**Comment by chris-lawton** [comment]
All looks good to me. For code review, i've just had a look over the BE merge request at the relevant bits and it's fine.
