### ISSUE TITLE
Rounds block: Submissions page: Backend

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#808]
The round block will be used to list rounds and labs

**Acceptance criteria**
- [x] Contains only “active” rounds and labs - those with undetermined submissions
- [x] Has two tabs in which the submissions are grouped: “open” (end date of round/lab has not passed) and “closed” (end date of round/lab is in the past). 
- [x] Tabs will default to “closed”
- [x] 'View' link in rows will link to Submissions by Round page for the selected Round
- [x] No pagination, 5 rows maximum to be displayed
- [x] If more than 5 rows available, a “Show all” link will be added
- [x] Does not allow ordering of columns
- [x] Show all will link to “All Rounds” page filtered by “open” or “closed” and “active”
- [x] Rounds/labs ordered by end date descending
- [x] Round/lab display columns: Round/Lab Name, Fund Name, Status (open/closed) and end date, Progress (% with final determination)
- [x] QA criteria satisfied

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805634
![screen shot 2019-01-08 at 11 27 03](https://user-images.githubusercontent.com/19690895/50828135-6976cb00-1338-11e9-8a14-350f1ead0346.png)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now deployed to dev for testing

**Comment by gibbsmaya** [comment]
@todd-dembrey, feedback below to be addressed:

- [ ] Can we please change the max number of rounds/labs shown to be 5? Its far too much at 10 now that we can see it in real life! (also once this is done I can test the AC for the show all link)
- [ ] *AC: Contains only “active” rounds and labs - those with undetermined submissions*: I don't think this is working correctly as rounds with no submissions are showing e.g. https://dev-apply.opentech.fund/apply/rounds/230/

**Comment by todd-dembrey** [comment]
* Active limited to rounds with applications
* Max changed to 5

**Comment by gibbsmaya** [comment]
Thanks @todd-dembrey . Assigning to @emullaney for code review.

**Comment by todd-dembrey** [comment]
Erin has code reviewed. Todd to deploy to test

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work consists of the addition of the "All Rounds and Labs" block to the Submissions Overview page at https://test-apply.opentech.fund/apply/submissions/. This is the beginning of making the Submissions page into more of a submissions dashboard rather than a main submission listing (though the main listing will still be accessible!). This work will be extended in future sprints with some tweaks to the submission table that is currently on this page, and the addition of a Submissions by Status section.

For now, we are concentrating this testing on the All Rounds and Labs block. Please test this against the acceptance criteria noted in the initial issue description. Note that the front end of this bit of work (how it visually appears) is recorded in #809 

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
1. The acceptance criteria noted in the initial issue description is all there except for "If more than 5 rows available, a “Show all” link will be added." 
2. All seven total submissions within IFFund-2018-11 are visible, not five as stated in criteria
3. I am not able to see the "Show all" link in the Submissions by Round page.

**Comment by gibbsmaya** [comment]
Hi @fourthletter,

The restriction of 5 entries is just relating to the "All Rounds and Labs" block on the Submission Overview page (https://test-apply.opentech.fund/apply/submissions/) rather than the round page itself once you click through to it (the expected behaviour there is that is does show all submissions for that round). I agree that currently you can't test the restriction of 5 entries in the "All Rounds and Labs" block on the Submission Overview page because there is not enough test data to constitute this. So I either suggest that you create some test rounds to test this or we can double check it when we push to production.

Let me know how you would like to proceed, or if this still doesn't make sense we can have a quick call to review.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are accurate and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter . Moving to @todd-dembrey for deployment to production.
