### ISSUE TITLE
Rounds block: Submissions page: Front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#809]
The round block will be used to list rounds and labs

**Acceptance criteria**
- [x] Open and Closed tabs displayed as per design and allow user to click between the two
- [x] Tabs will default to “closed”
- [x] 'View' link in rows will link to Submissions by Round page for the selected Round
- [x] No pagination, 5 rows maximum to be displayed
- [x] If more than 5 rows available, a “Show all” link displayed
- [x] Round/lab display columns: Round/Lab Name, Fund Name, Status (open/closed) and end date, Progress
- [x] Closed displayed as: Closed <end_date>
- [x] Open displayed as: Open until <end_date>
- [x] No End Date displayed as: Open
- [x] Progress displayed as: % with final determination
- [x] 'View' link added to each row as per design

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805634
![screen shot 2019-01-08 at 11 27 03](https://user-images.githubusercontent.com/19690895/50828135-6976cb00-1338-11e9-8a14-350f1ead0346.png)

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Hey Beth, 
Can you review this please?
https://github.com/OpenTechFund/opentech.fund/pull/830

**Comment by hippogriffic** [comment]
lgtm 👍

**Comment by chris-lawton** [comment]
Thanks Beth!

Moving to blocked until https://github.com/OpenTechFund/opentech.fund/issues/808 is ready for testing.

Note some of the AC in this ticket will need to be implemented by BE, specifically:
- 'View' link in rows will link to Submissions by Round page for the selected Round
- No pagination, 10 rows maximum to be displayed
- If more than 10 rows available, a “Show all” link displayed
- Round/lab display columns: Round/Lab Name, Fund Name, Status (open/closed) and end date, Progress

**Comment by gibbsmaya** [comment]
@chris-lawton this is now ready for you to look at, implemented on https://dev-apply.opentech.fund/apply/submissions/. As you will see it all looks rather big! Think we need to reduce the size of the rows and the text to be more inline with the design. 

Open round date display is incorrect - see acceptance criteria. It currently uses closed format.
No end date lab display is incorrect - see acceptance criteria. Currently not showing anything.

**Comment by chris-lawton** [comment]
@gibbsmaya 

- Reduced the sizing of the round list items including header size, paragraph size and overall item height
- Open and no end dates should now be showing the correct wording

**Comment by gibbsmaya** [comment]
Ah, looks so much better, thanks @chris-lawton ! Just awaiting a tweak on max number of items for list from Todd and can then test the show all link and mark this as done.

**Comment by todd-dembrey** [comment]
Tweaked and deployed.

**Comment by gibbsmaya** [comment]
Thanks. Assigning @todd-dembrey for deployment to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work consists of the front end styles for the work on #808 . Description of what the work is can be found on that issues and this can be tested alongside it testing against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
1. All Rounds and Labs block disappears when I click on "Open" tab. Clicking on "Closed" tab meets all design criteria. 
2. "Open displayed as: Open until <end_date>" is not visible

**Comment by gibbsmaya** [comment]
The block "disappears" because it has no open rounds to display. We should display a message in this case as I agree this is confusing as a user. @chris-lawton can you please add this?

@fourthletter regarding your second point - where are you testing this if no open rounds are appearing in this list?

**Comment by chris-lawton** [comment]
With @todd-dembrey for review - https://github.com/OpenTechFund/opentech.fund/pull/903

**Comment by gibbsmaya** [comment]
Thanks @chris-lawton looks good. @fourthletter handing over to you for final acceptance.

**Comment by fourthletter** [comment]
- All acceptance criteria is accurate and functional. Thanks! 
- 'View' link is no longer visible in the “Show all” page. In lieu of not having "View"; clicking on the Round/Lab Name serves the same function.

**Comment by gibbsmaya** [comment]
Thanks @fourthletter this all meets expected behaviour as these two tables perform different functions and are differently styled. Moving to @todd-dembrey for deployment to production.
