### ISSUE TITLE
All Rounds page: backend

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#811]
Lists all rounds in the same manner as the current Submissions Page

**Acceptance criteria**

- [x] New page to be created at /rounds/
- [x] Page available to OTF staff and admin
- [x] Page contains listing table displaying all Rounds in same manner as current submissions page (https://dev-apply.opentech.fund/apply/submissions/)
- [x] Table columns should be: Round Name, Fund, Lead, Start Date, End Date, Progress (Determination %)
- [x] Filters to be available for this table: Open/Closed, Fund/Lab, Lead, Active/Inactive (Have all submissions received a final determination)
- [x] Paginates as per existing submissions table
- [x] QA criteria satisfied

Design: Not designed - style to match other components/pages. Note that search will be added to this table too at a later date.

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya The ordering icons are not on the table, but the ordering works.

https://dev-apply.opentech.fund/apply/rounds/

**Comment by gibbsmaya** [comment]
@todd-dembrey feedback below - some of the points may be front end related.

- [ ] Progress values should be displayed as 'x% Determined' as per round block.
- [ ] Filters when used should remain open and visible as per main submission table filters.
- [ ] Should we have search here too?

Can't test pagination as not enough rounds - how many rows does it need to paginate?

**Comment by todd-dembrey** [comment]
We are using the default pagination. 25 items

Progress header updated - as discussed, we didn't define the search for the rounds, so have not been included.

**Comment by gibbsmaya** [comment]
Great thanks @todd-dembrey. Assigning to @emullaney for code review.

**Comment by todd-dembrey** [comment]
Todd to deploy to test

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work consists of the master listing for all rounds and can be found at https://test-apply.opentech.fund/apply/rounds/. This displays all rounds with filters to select different subsets of rounds to view. This page is available from the main rounds menu item or from the 'All rounds' link from the round block on the submissions overview page.

Please test this against the acceptance criteria noted in the initial issue description. Note that the front end of this bit of work (how it visually appears) is recorded in #812  and can be tested together. 

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off. 

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional from my vantage point :) 

Is there a difference between Active/Inactive and Open/Closed?

**Comment by gibbsmaya** [comment]
Thanks @fourthletter . In answer to your question, active/inactive refers to whether a round has active action on it, i.e. it has submissions and not all the submissions are determined. Open closed is solely related the dates the round is set to. So for example, you could have a closed round (you have stopped accepting submissions) and the round could be active (not all submissions are determined) or inactive (all submissions are determined). Does that make sense? Are you happy for us to prepare this issue for deployment to production?

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional during today's test. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter . Moving to @todd-dembrey for deployment to production.
