### ISSUE TITLE
All rounds page: front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#812]
Lists all rounds in the same manner as the current Submissions Page

**Acceptance criteria**
- [x] General page layout to follow current submission page styling and layout
- [x] Rounds listing table displaying following existing style patterns from main submissions table and round block 
- [x] Filters to be styled using existing filter style patterns and behaviours
- [x] QA criteria satisfied

Design: Not designed - style to match other components/pages. Note that search will be added to this table too at a later date.

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by gibbsmaya** [comment]
@chris-lawton this is now ready to be reviewed and tweaked. See https://dev-apply.opentech.fund/apply/rounds/. A couple of things I have noticed are the table spacing of columns needs a bit of tweaking, particularly lack of padding before the first column. I also wonder whether style-wise we should match the submission or round block a little better. I don't think we should make the content larger as per round block, but colour-wise and stylewise I think this could look more aligned with existing styles.

**Comment by todd-dembrey** [comment]
TODO: Ordering missing from columns.

**Comment by gibbsmaya** [comment]
@chris-lawton a further point on here is:

- [ ] Filters when used should remain open and visible as per main submission table filters.

**Comment by chris-lawton** [comment]
Added styles to be more consistent with what we have already and fixed the filter issue. 
Have asked Todd to review as i've changed some of the backend code for naming consistency.

MR - https://github.com/OpenTechFund/opentech.fund/pull/868

**Comment by chris-lawton** [comment]
Ordering has now been added to the all rounds block - @todd-dembrey can you take a look over?

**Comment by todd-dembrey** [comment]
This is now reviewed and deployed.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work consists of the master listing for all rounds and can be found at https://test-apply.opentech.fund/apply/rounds/. This issue is solely the front end bit of this work (how it visually appears). The actual functionality is recorded in #811   and can be tested together. 

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off. 

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional :)
