### ISSUE TITLE
Submission by round detail view: Grouped by listing: Front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#813]
Grouped Listing on left hand side of Submission by Round page.
To include skeleton template for 3 columns and mobile

**Acceptance criteria**
- [x] List styled as per design
- [x] Hover states to follow existing styles
- [x] Submissions list is scrollable

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [ ] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Started frontend work here - https://github.com/OpenTechFund/opentech.fund/tree/feature/813-grouped-listing-view-fe

Tomasz is going to merge this into his backend work for https://github.com/OpenTechFund/opentech.fund/issues/814 - once that ticket is done i'll give the frontend a once over, so moving to blocked for the time being.

**Comment by gibbsmaya** [comment]
Front end styles look good to me. @chris-lawton can you do the QA on your side and once complete assign to @todd-dembrey for deployment to test?

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is the front end work relating to #814. Please test this alongside this issue on which there is a much more detailed explanation of the work.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design. 

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by danblah** [comment]
Looks good, acceptance criteria met from my testing.

**Comment by gibbsmaya** [comment]
Thanks @danblah . Assigning to @todd-dembrey to arrange deployment to production.
