### ISSUE TITLE
Submission by round detail view: Application detail view: Backend

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#815]
Submission Detail in centre of Submission by round detail view page 

**Acceptance criteria**
- [x] Defaults to the first submission in the submission listing on page load
- [x] Shows the selected submission in the submission listing thereafter
- [x] Shows the same information as available on the current submission detail page (except the 'edit account' link)
- [x] QA criteria satisfied

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805632

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by gibbsmaya** [comment]
@todd-dembrey I am happy with this. Can you please go through QA checklist your end?

**Comment by todd-dembrey** [comment]
QA confirmed. It is deployed. With you to confirm testing requirements for OTF

**Comment by fourthletter** [comment]
The default detail view is the **last** application in the submission listing. "Maya's test project" appears, not "Maya Tom test 2." All other acceptance criteria is accurate and functional. Thanks!

**Comment by gibbsmaya** [comment]
Hi @fourthletter thanks for testing. Just to confirm, I am also seeing "Maya's test project" as the default detail view on page load, however this looks like it is the first application in the list - the top one. Is this not the case for you? 

Here is a screenshot of what I see:
![screen shot 2019-01-25 at 09 46 36](https://user-images.githubusercontent.com/19690895/51738070-2598fb00-2086-11e9-9c3e-a8e776af047f.png)

Could you send a screenshot please if you are seeing something different?

**Comment by gibbsmaya** [comment]
Hi @fourthletter. Ah I see. The ordering of the statuses is being done in the current sprint (#844) so the order in which these are currently displaying are not consistent. However, the behaviour of the top submission in the list being the default one selected seems to be met in your example, it is just a different one to mine due to the different ordering of statuses. Please confirm if this can be approved and deployed to production.

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional during today's test. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey for deployment to production.
