### ISSUE TITLE
Submission by round detail view: Application detail view: Front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#816]
Submission Detail in centre of Submission by round detail view page 

**Acceptance criteria**
- [x] Styled as per design, using existing styling from submission detail page
- [x] Selected submission is highlighted in submission list as per design
- [x] On mobile, tapping submission is submission list takes you to submission detail view with a 'back' button

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805632

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Frontend work started here - https://github.com/OpenTechFund/opentech.fund/tree/feature/816-app-detail-view-fe

QA for this ticket is now dependent on BE functionality being implemented in https://github.com/OpenTechFund/opentech.fund/issues/815

**Comment by gibbsmaya** [comment]
Testing on https://dev-apply.opentech.fund/apply/rounds/777/

Missing blue left hand highlight on selected submission in grouped by list when submission is selected

**Comment by chris-lawton** [comment]
@gibbsmaya - this is now fixed and on the dev site

(Helen is just being added to the repo then will get her to review my commits associated with this work -https://github.com/OpenTechFund/opentech.fund/commits/feature/816-app-detail-view-fe)

**Comment by gibbsmaya** [comment]
@chris-lawton I still can't see this on dev?

**Comment by chris-lawton** [comment]
@gibbsmaya - i've just pushed a fix for this to the dev site, which is live now. It seems to have fixed it in the scenario where I was able to replicate the issue, so can you take another look over it please?

**Comment by gibbsmaya** [comment]
Yep, looks good to me now. Can you please confirm if this has been code reviewed and if so complete the QA checklist above and then hand to Todd for deployment to test?

**Comment by chris-lawton** [comment]
Hi @helenb - are you able to review the 6 commits here please?
https://github.com/OpenTechFund/opentech.fund/commits/feature/816-app-detail-view-fe

**Comment by helenb** [comment]
Would it be possible to get access to the dev site to see a live example while doing code reviews?

**Comment by helenb** [comment]
Have reviewed as best I can bearing in mind my lack of familiarity with the infrastructure - just a couple of comments.

**Comment by todd-dembrey** [comment]
This is now on test and ready for UAT

**Comment by fourthletter** [comment]
All acceptance criteria is accurate and functional during my test. I was able to toggle easily in between and within submissions using the mobile version. Thanks!

**Comment by gibbsmaya** [comment]
Great. Assigning to @todd-dembrey for deployment to production.
