### ISSUE TITLE
Update Search style and behaviour: Behaviour logic

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#820]
Updates to search behaviour - no longer linking out to new page, instead searching within the some page and allowing filters to be applied.

**Acceptance criteria**

- [x] Search box moved adjacent to filters (out of header area)
- [x] When a user searches the page reloads to show related results
- [x] Search is triggered by hitting enter or the search icon
- [x] User should be able to filter search results or search filtered results
- [x] Search field retains the input value the user has provided after search is applied
- [x] Apply new search behaviour to the Submissions page
- [x] Old search results page removed
- [x] QA criteria satisfied

Designs
![search filter1](https://user-images.githubusercontent.com/7290588/50698632-52d12b00-103d-11e9-8e03-f12258f10c24.png)
![search filter2](https://user-images.githubusercontent.com/7290588/50698633-52d12b00-103d-11e9-8e22-69208f679121.png)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
This is deployed and ready for review at https://dev-apply.opentech.fund/apply/submissions/

**Comment by gibbsmaya** [comment]
Hi @todd-dembrey this is all working well. only thing I noticed which was only by accident as I was trying to work out what the current search page url is, is that there is a page at /search which provides search functionality and is not properly styled. Should we remove this?

**Comment by todd-dembrey** [comment]
@gibbsmaya the fix to the search on apply was a little more involved than expected. 

I have fixed a long running issue with the 404 templates when you are logged in showing the public site. So that is good... We should probably test 404'ing both logged in and out on the apply site.

**Comment by gibbsmaya** [comment]
Great, have tested and confirm this is now as expected. Have also tested 404s on logged in and out on site. Happy for this to be deployed to test.

**Comment by todd-dembrey** [comment]
This is now deployed to test.

**Comment by gibbsmaya** [comment]
Going to hold off handing this over until we do #864 as this is too isolated without this, and we also would not be able to deploy this work to production without that issue included.

FYI @todd-dembrey @danblah

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is on update to the search functionality of submissions. This is best tested on a round page e.g. https://test-apply.opentech.fund/apply/rounds/732/. Please note that the front end of this work (how it looks) is captured on #821 so worth testing these in parallel.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design. 

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Everything in acceptance criteria is accurate and functional. 

In regards to the second acceptance criteria "When a user searches the page reloads to show related results," a minor detail is searching for "maya" didn't narrow the search, but searching for "tom" and "final"  narrowed the search.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, great will mark this as ready for deployment to production with @todd-dembrey .

With regards to your question - I believe the reason the search for "maya" does not narrow the search is because I created all the test applications so "maya" exists either in the name of the submission or in the name of the applicant of each submission. Maybe I should try and be less self-centred ;)
