### ISSUE TITLE
Update Search style and behaviour: Front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#821]
This has been added to the Submissions page. Use that page for testing.

**Acceptance criteria**

- [x] Search box moved adjacent to filters (out of header area) matching design
- [x] Search field retains the input value the user has provided after search is applied

Designs
![search filter1](https://user-images.githubusercontent.com/7290588/50698632-52d12b00-103d-11e9-8e03-f12258f10c24.png)
![search filter2](https://user-images.githubusercontent.com/7290588/50698633-52d12b00-103d-11e9-8e22-69208f679121.png)

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Assigning to Beth for review - https://github.com/OpenTechFund/opentech.fund/pull/854

**Comment by gibbsmaya** [comment]
@chris-lawton I have tested this in the meantime and think it needs a bit of padding between the filters and the search bar on mobile - currently they are up against each other. Beth can review in the meantime and you can pick this up on Friday.

**Comment by chris-lawton** [comment]
Ah, I hadn't pushed my changes to dev as was waiting for review so you may want to give it another once over now it's live on dev.

**Comment by gibbsmaya** [comment]
@todd-dembrey please can you deploy this to test?

**Comment by gibbsmaya** [comment]
Going to hold off handing this over until we do #864 as this is too isolated without this, and we also would not be able to deploy this work to production without that issue included.

FYI @todd-dembrey @danblah

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is on update to the search functionality of submissions. This is best tested on a round page e.g. https://test-apply.opentech.fund/apply/rounds/732/. Please note that the back end of this work is captured on #820  so worth testing these in parallel.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design. 

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Every acceptance criteria is accurate and functional. Yay! 💥

**Comment by gibbsmaya** [comment]
Great. Assigning over to @todd-dembrey for deployment to production.
