### ISSUE TITLE
All submission page: Backend

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#822]
Lists all submissions in the same way the current Submissions page does. 

**Acceptance criteria**
- [x] New 'all submissions' page to be created containing all content from existing submissions page
- [x] New page to sit on url (/apply/submissions/all)
- [x] Listing table to contain the following columns: As current table plus screening
- [x] Filters and Search: As current filters plus screening and reviewed by
- [x] QA criteria satisfied

Design: Not designed - use existing styling and updated components

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by emullaney** [comment]
@todd-dembrey please review when you have time. Note that the "reviewed by" filter is part of the dashboard reviewers block updates, and will not be fixed on this ticket.

**Comment by todd-dembrey** [comment]
@gibbsmaya this is on develop

**Comment by gibbsmaya** [comment]
Looks good to me. @todd-dembrey please deploy to test.

**Comment by todd-dembrey** [comment]
This is now deployed to test and is ready for UAT

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is simple a new page containing the main 'all submissions listing' identical to what you had before but on a different URL (https://test-apply.opentech.fund/apply/submissions/all/) and linked to from the new submissions overview page.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria have been tested, each one is accurate and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Moving to @todd-dembrey for deployment to production.
