### ISSUE TITLE
On invalid account activation links, indicate the reason to the user

### ISSUE THREAD

**Issue by frjo** [OpenTechFund/opentech.fund#823]
Add information that the link has expired, that the account already is active etc.

**Comment by frjo** [comment]
@danblah Does a text like this sounds ok?


~~~~
Invalid activation URL

Two possible reasons:

    The activation link has expired.
    The account has already been activated.

First test to reset your password. If that fails please contact OTF at hello@opentech.fund
~~~~

The "reset your password" and the e-mail adress are links.

**Comment by danblah** [comment]
This is good.

**Comment by danblah** [comment]
Does the initial account email make it clear the account will become inactive if they don't complete the registration process?

**Comment by frjo** [comment]
Will make sure it does. What expirations time should we set for activation links? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fourthletter** [comment]
Could PMs/OTF team members reactivate applicant accounts on our own? Right now PMs are sending out reset password link or temporary password.

**Comment by frjo** [comment]
See my answer on Slack. Please do not reopen resolved issues. Better to open a new one. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
