### ISSUE TITLE
errors in IE11

### ISSUE THREAD

**Issue by chris-lawton** [OpenTechFund/opentech.fund#832]
Getting a few errors when viewing both the public and apply site in IE 11 which I think are related to the JS not being transpiled correctly.

@frjo - do you have any idea as to how many of the users visiting the site are using this browser?

![screen shot 2019-01-10 at 14 28 14](https://user-images.githubusercontent.com/31627284/50975174-d333d800-14e4-11e9-9819-8661e1a61950.png)
![screen shot 2019-01-10 at 14 35 49](https://user-images.githubusercontent.com/31627284/50975273-10986580-14e5-11e9-8c22-94f84ad3cd22.png)

**Comment by frjo** [comment]
@chris-lawton Can't be many but I do not have the numbers. @danblah at OTF will have them.

Have not used "babel" before this project but is it not supposed to pick up the browserslist from package.json? 

It might be that 

~~~~
.pipe($.babel({presets: ['@babel/env']}))
~~~~

 in gulpfile.js should be

~~~~
.pipe($.babel({presets: ['@babel/preset-env']}))
~~~~

I see that in some examples when doing a quick search.
