### ISSUE TITLE
Shorten the list of items in "Related Submissions" box, to only show 5 by default with a show more when there are more

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#834]
See https://apply.opentech.fund/apply/submissions/3498/, there's waaaaaay to many showing there.

**Comment by fourthletter** [comment]
Current test shows more than 5 previous submissions.

![image](https://user-images.githubusercontent.com/20019656/57405868-7bb12a80-71ad-11e9-94f2-de32c9dce13b.png)

**Comment by frjo** [comment]
@fourthletter Yes, the list is cut off by pixels and not item count. Most titles are long and takes up more than one line so I set it to 300px.

**Comment by fourthletter** [comment]
This issue was visible and functional during testing. Thank you!
