### ISSUE TITLE
Submission by round detail view: Grouped by listing: Round details from API

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#844]
Splitting out this task from #814 as API was not ready for this when undertaking that work. 
Remaining tasks is to fetch the round details from the API which will include the "friendly" status names and the ordering of statuses within the round.

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430

**Acceptance criteria**

- [x] Statuses in submission listing are ordered as per order of workflow (i.e. same as status timeline on submissions)
- [x] Status names are human-friendly names, matching the status names in actions and submission status timeline

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now available on dev for testing

This round is a good example: https://dev-apply.opentech.fund/apply/rounds/732/

**Comment by gibbsmaya** [comment]
Looks good to me. Happy for this to be deployed to test @todd-dembrey

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is the naming and ordering of statuses within the left hand submission listing on Submission by Round detail view pages e.g. https://test-apply.opentech.fund/apply/rounds/732/ (click the switcher in the top right to get from the list view to the detail view)

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
The first criteria "Statuses in submission listing are ordered as per order of workflow (i.e. same as status timeline on submissions)" is not reflected during test. The second acceptance criteria is fine.
![image](https://user-images.githubusercontent.com/20019656/52231068-f3a64680-2886-11e9-84aa-c1bf9fe938ac.png)

**Comment by gibbsmaya** [comment]
@fourthletter - this is the Submission by round list view you are looking at. Please click the switcher in the top right of this page to get from the list view to the detail view
![screen shot 2019-02-05 at 09 06 19](https://user-images.githubusercontent.com/19690895/52262785-5cdc9700-2925-11e9-8733-cf057f09f3cd.png)

and then the area this issue is referring to is the left hand column of this page which should look something like this:
![screen shot 2019-02-05 at 09 06 26](https://user-images.githubusercontent.com/19690895/52262803-66fe9580-2925-11e9-9060-864ecd1b3856.png)

**Comment by fourthletter** [comment]
Acceptance criteria are visible and functional during test. Thank you for clarification above. 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey for deployment to live.
