### ISSUE TITLE
Submission by round detail view: Grouped by listing: Status "jump to"

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#845]
Task to add filter style functionality at the top of the grouped listing allowing the user to select a status to "jump to".

Design: to follow existing styles

**Acceptance criteria**

- [x] Filter-style selector is displayed above grouped listing
- [x] All available statuses are present in the options of this selector
- [x] Selecting an option anchors the user down to that status in the grouped list, scrolling to the relevant point in the list

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
This is all React work so handing to Todd for review

**Comment by todd-dembrey** [comment]
Reviewed, generally alright but i'm not happy about the 75 and the general approach of scrolling

**Comment by chris-lawton** [comment]
Have actioned your feedback - can you take a look at the latest two commits please?

**Comment by gibbsmaya** [comment]
To check with Tom S:
Should we somehow show what status has been selected?
Should we default to the first application in the status selected?

**Comment by chris-lawton** [comment]
Tom has suggested that we add space under the last item to allow the that item to be scrolled to in the column

**Comment by chris-lawton** [comment]
@gibbsmaya - I've implemented what Tom suggested which is now live on dev - example here -https://dev-apply.opentech.fund/apply/rounds/777/

**Comment by gibbsmaya** [comment]
Looks good to me. Moving to @todd-dembrey for deployment to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work is the ‘jump to’ filter at the top of the left hand submission listing on Submission by Round detail view pages e.g. https://test-apply.opentech.fund/apply/rounds/732/ (click the switcher in the top right to get from the list view to the detail view). This should allow you to anchor down to the status of interest.

Please test this against the acceptance criteria noted in the initial issue description.
Please let us know if anything is unclear or if you have any questions. Otherwise please provide 
feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Acceptance criteria are visible and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey for deployment to live.
