### ISSUE TITLE
Submission by round list view: activity feed

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#849]
**Acceptance criteria**

- [x] Add activity feed sticky button to page as per main submission listing
- [x] Activity feed functions and displays as per activity feed on main submission listing
- [x] Activity feed displays only activities associated with submissions in the round

Design: as per existing activity feed

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by emullaney** [comment]
@gibbsmaya you should be able to test this on dev now! Sorry for the hold up on moving the ticket.

**Comment by gibbsmaya** [comment]
Looks good to me. Thanks!

**Comment by gibbsmaya** [comment]
@todd-dembrey with you to deploy to test once WS1 has been deployed to production.

**Comment by gibbsmaya** [comment]
Apologies @emullaney, but I have actually found an issue with this. The activity feed should be present on the list view but not on the detail view (using the switcher in the top right). I thought @todd-dembrey had mentioned this in his code review but maybe I was mistaken. Can you please tweak?

**Comment by gibbsmaya** [comment]
With @todd-dembrey to review @chris-lawton changes to hide the activity feed button on the detail view page. I am happy with this so once you have reviewed Todd, please mark this as done and prepare this for deployment to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work is including the activity feed on the Submission by Round list view e.g.https://test-apply.opentech.fund/apply/rounds/732/.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Acceptance criteria are visible and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey for deployment to production.
