### ISSUE TITLE
Submission by round list view: front end polish

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#850]
Front end review of complete page. Page example: https://dev-apply.opentech.fund/apply/rounds/732/

**Acceptance criteria**
- [x] Header bar as per design
- [x] Filter and search displaying as per design
- [x] Table listing styled as per design

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971996

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Hi @helenb - can you review this PR please - https://github.com/OpenTechFund/opentech.fund/pull/904

**Comment by chris-lawton** [comment]
Thanks Helen. 

@gibbsmaya - this is now on dev for review - https://dev-apply.opentech.fund/apply/rounds/743/

**Comment by gibbsmaya** [comment]
Hi @chris-lawton,

This all looks good. Only comment is to add a bit of space between the '|' and the text - the design has a bit more breathing space after the fund name and before the lead.

FYI there may be some further tweaks after reviewing this from a UX perspective which may result in removing the breadcrumb all together but will look at that on a separate issue.

Thanks,
Maya

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

The spacing change you mentioned above is now on dev, along with the changes from #906.
Unsure if once you've checked the spacing change you want to close this ticket in favour of that one?
