### ISSUE TITLE
Submission by status page

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#851]
**Acceptance criteria**

 - [x] As a OTF staff member I can access the page
 - [x] As an application or AC member I cannot access the page
 - [x] Page url is `/submissions/<status-name>/`
 - [x] Page header contains status name
 - [x] Page displays table of submissions for labs and funds in the selected status
 - [x] Table columns are as per main submission table
 - [x] Filters are as per main submission table filters
 - [x] Page matches design as per design notes below

Design: as per status by round page https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971996 but note that header contains status as per header on https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya this is now on dev for testing.

I have left the filter and column in as there are some cases where multiple status appear in the same grouping but have different names - mainly received. It might be better to limit the options to these where this is the case rather than remove it entirely.

Valid slug list shown below:

e.g. https://dev-apply.opentech.fund/apply/submissions/accepted/
```
received
internal-review
in-discussion
more-information
invited-for-proposal
external-review
ready-for-determination
accepted
dismissed
```

**Comment by todd-dembrey** [comment]
@gibbsmaya I have updated the filters to limit the statuses to the relevant ones. It is on Dev

**Comment by gibbsmaya** [comment]
Looks good to me. Please deploy to test and finalise code review.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is the submission by status page displaying all submissions in a particular status on one page. E.g. https://test-apply.opentech.fund/apply/submissions/received/. This is just like the Submission by Round page you reviewed in the last sprint but the submissions are grouped by status instead of round. 

These are the different pages available to access:

https://test-apply.opentech.fund/apply/submissions/received
https://test-apply.opentech.fund/apply/submissions/internal-review
https://test-apply.opentech.fund/apply/submissions/in-discussion
https://test-apply.opentech.fund/apply/submissions/more-information
https://test-apply.opentech.fund/apply/submissions/invited-for-proposal
https://test-apply.opentech.fund/apply/submissions/external-review
https://test-apply.opentech.fund/apply/submissions/ready-for-determination
https://test-apply.opentech.fund/apply/submissions/accepted
https://test-apply.opentech.fund/apply/submissions/dismissed

Note you will need to access these pages directly on these urls for now as there is no link to them from the site at the moment. In the next sprint we will be creating a jumping off point for these pages from the submission overview page.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
"Ready for determination" and "Ready for Final Determination" are three separate statuses that appear in the same Page header contains status name.

The screenshot shows "Ready for Final Determination" submission/application under the "Ready for determination" page header:
![image](https://user-images.githubusercontent.com/20019656/52293637-5c53f880-2945-11e9-95a6-5f7c5436c62a.png)

**Comment by gibbsmaya** [comment]
Hi @fourthletter,

Apologies, I meant to explain something additional when I handed this over. Some of the statuses we have grouped into one page when they have the same meaning or action associated with them. For example, Received shows applications in statuses Received and Screening as these states are the same and require the same follow in step, its just that one is the first state for a proposal and one is the first state for a concept note.

Similarly, with 'Ready for determination', this state changes wording slightly dependent on the type of application. If it is a concept note it is called 'Ready for preliminary determination', for proposals it is called 'Ready for final determination' and for applications in a one stage workflow it is called 'Ready for determination'. However all of these state namings reflect the same state - that the application is ready for a determination of some sort.

We can split these out if this is preferable, but we thought that it made sense to group them together. Let us know what you think or if you need any further clarification.

Thanks,
Maya

**Comment by danblah** [comment]
I'm ok with this. Thanks for the clarification.

**Comment by gibbsmaya** [comment]
Thanks @danblah. Assigning to @todd-dembrey for deployment to production.
