### ISSUE TITLE
Unable to "dismiss" or "invite to propsal" any concept note [High/Bug] 

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#853]
-=Sensitive=-
No

-=Reporter=-

-=Ideal deadline=-

-=Who's affected=-
OTF team, Applicants

-=Description=-
After testing on multiple concept notes under 2019-03 for IFFund, I am unable to progress any of the concept notes to a state that is not "Request more information". I need to dismiss and invite to proposal several concept notes under the 2019-01 round, and am unable to do so.  

My understanding was that this should have been resolved based on this ticket: https://github.com/OpenTechFund/opentech.fund/issues/725

-=Objective=-

-=Additiional info=-

-=Timestamp=-
2019-01-16T16:03:35.703Z

**Comment by frjo** [comment]
When clicking the "Update status" button" do you not see e.g. "Dismissed" as an option? Or do you see it but it has no effect when applied?

Tested it quickly locally with my own account and it seems to work. Could be a permission issue, staff not getting the right ones.

**Comment by fourthletter** [comment]
This issue occurs when I'm in "Add Determination" of the webapp, the only option in the drop down menu is  "Needs more info" and not "Dismiss"
![screenshot 2019-01-16 at 11 44 47 am](https://user-images.githubusercontent.com/20019656/51264437-7d4bae00-1984-11e9-9f00-c85cf648df74.png)

**Comment by fourthletter** [comment]
In the Update Status, I cannot progress to "Dismiss" since "Request More Information" is the only option. 
![screenshot 2019-01-16 at 11 47 59 am](https://user-images.githubusercontent.com/20019656/51264522-b5eb8780-1984-11e9-865e-2b9f6188928a.png)

**Comment by danblah** [comment]
Would this easily sorted by changing there required permission to offer this option (currently LEAD) to STAFF? See https://github.com/OpenTechFund/opentech.fund/blob/95297a041b2edfe0eaf87c55415426e6550e15f5/opentech/apply/funds/workflow.py#L338

If so, that's a quick fix, no?
