### ISSUE TITLE
Batch action: review

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#860]
Batch actions will allow OTF staff to apply the same action to multiple submissions at the same time via the listing table. 

**Acceptance criteria**

- [x] Clicking on an action will show the same interface as used for the current Add reviewers functionality on the individual submission page
- [x] Adding reviewers updates reviewers on submission (updates to submission page and submission listing entry)
- [x] Batch action interface shows extra context about the submissions selected to clarify that this is a batch action
- [x] On batch action submit, page refreshes, batch selections are unselected and message displayed to user confirming action (design of message as per https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971429 but no undo!)
- [x] If error when batch updating display message to user (same design as per action confirmation at top of screen)
- [x] Batch actions available on all submission tables on All Submissions page, Submissions by Round page and Submission by Status page (not submission summary blocks on dashboard or submission overview page)
- [x] Users will have the same permissions to perform changes as they do currently
- [x] Email notifications are unaffected: Applicants will each receive emails as if an action had been taken on their submission only
- [x] Activity feed entries are unaffected: Submissions will have an activity added, it will not be tracked as a batch action 
- [x] Slack notifications updated: only one notification is sent to handle batch message e.g. `“<user> has done <action> to: <submission1><submission2><submission3>”`

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971996
Design of actual action: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781107 / https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781106 (note that as a first round we should just display the application title without a link out and without 'remove' functionality)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
@emullaney - FE work for this is now available at https://github.com/OpenTechFund/opentech.fund/tree/feature/861-batch-actions-fe

**Comment by gibbsmaya** [comment]
Have tested what I can for now. Only point for now:

- Batch action should not be available on submission summary block on https://dev-apply.opentech.fund/apply/submissions/

**Comment by todd-dembrey** [comment]
@gibbsmaya this is now on dev for testing - including slack messaging.

**Comment by todd-dembrey** [comment]
See attached for error message

![image](https://user-images.githubusercontent.com/6338661/52122393-c0f81600-261a-11e9-8230-9abf48956326.png)

**Comment by gibbsmaya** [comment]
Thanks @todd-dembrey . Please go ahead and deploy to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is adding a batch action for adding reviewers. You can access this on the all submissions page at https://test-apply.opentech.fund/apply/submissions/all/. As mentioned on the demo call, we will be adding the ability to batch action status updates and sending determinations which will come in the next sprint.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
**All acceptance criteria are visible and functional.** One minor issue is I do not know what you mean by "Submission by Status page". Thank you unicorns! :unicorn:

**Comment by gibbsmaya** [comment]
Hi @fourthletter,

Thanks for your testing :) In answer to your questions:

1. This means that when you do a batch action, we are showing clearly that this is a batch action rather than an action on a single submission. In this case, this refers to the pop up box for adding reviewers where we are showing "2 submissions selected" and then displaying info about these submissions.
2. An example of a submission by status page is https://test-apply.opentech.fund/apply/submissions/received/

Can you please confirm you are happy with this and then we can prepare for production deployment?

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey for deployment to live.
