### ISSUE TITLE
Batch actions: front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#861]
Batch actions will allow OTF staff to apply the same action to multiple submissions at the same time via the listing table. 

**Acceptance criteria**

- [x] Submission table: Each row has a selectable checkbox in the first column 
- [x] Submission table: Multiple checkboxes are selectable at the same time 
- [x] Submission table: Header Row includes a “select all” checkbox that toggles all other checkboxes to match the state of the select all checkbox
- [x] Submission table: Unselecting a row after a select all will cause the “select all” checkbox to become unchecked
- [x] When at least one submission row is selected using the checkbox, a 'Reviewers' action appears 
- [x] Submission table row checkboxes are styled as per design
- [x] Number of checkboxes selected displayed as per design
- [x] Batch actions displayed as per design
- [x] Batch actions follow on steps styled as per existing design with addition of extra context about the submissions selected to clarify that this is a batch action DESIGN TBC
- [x] Message displayed to user confirming action (once performed) styled as per design (as per https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971429 but no undo!)
- [x] No batch action functionality on mobile

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971996
Disabled batch action: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781111 (note the help text is on hover)
Batch action (actual action): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781107 / https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781106 (3 submissions selected should be show/hide, note that as a first round we should just display the application title without a link out and without 'remove' so please update styles from designs accordingly)

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
@helenb - can you review this please - https://github.com/OpenTechFund/opentech.fund/pull/897

To note: 
This branch will now be picked up backend hence the reason for the logs in the JS and the comment about the form in `batch_update_reviewer_form.html`

**Comment by chris-lawton** [comment]
> Message displayed to user confirming action styled as per design
will need to be completed once BE have implemented their parts

**Comment by gibbsmaya** [comment]
Maya to add AC for disabled batch action buttons including design for disabled state plus help text on hover. Check with Tom what the icon should be for add determination. QA'd what we can currently on the FE only. Rest of AC dependent on backend being complete so on hold for now.

**Comment by helenb** [comment]
Code review comments added.

**Comment by gibbsmaya** [comment]
@chris-lawton I have updated the above design links to demonstrate the design for:

 - disabled batch actions on submissions listing page including on-hover help text
 - modal tweaks for the actual action - tweak to modal style and addition of the number of submissions selected with a show/hide.

Please can you add these into this bit of work to complete the rest of the acceptance criteria?

Thanks,
Maya

**Comment by chris-lawton** [comment]
PR for new modal styles - https://github.com/OpenTechFund/opentech.fund/pull/935/files
@helenb can you review please?

**Comment by helenb** [comment]
Reviewed: just a couple of small points.

**Comment by chris-lawton** [comment]
Thanks Helen.

@gibbsmaya - the updated modal styles are now on dev which also includes the hiding of the status button.

**Comment by gibbsmaya** [comment]
Hi @chris-lawton,

Looks good. A couple of things I can't test for now. One is around the disabled batch action styles as this is not relevant for reviewers at the moment. Can you send me a screenshot of the styles so I can confirm the visual appearance and we can retest the functionality in the next round of batch action work?

Still awaiting some backend work before I can test the message to user post batch action.

Only other thing for now is that on the the default for the hide/show on the modal for batch reviews -it currently defaults to show, can you change this so it defaults to hidden?

Thanks,
Maya

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

I've swapped the default state for the list, so it's hidden when it's first seen (now on dev) and as per standup we're going to move the disabled styles to another ticket to go along with the BE work.

Thanks,
Chris

**Comment by gibbsmaya** [comment]
Looks good. Now just awaiting the notification for confirming the action to be completed on the backend so I can test that.

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

Notification styles are now on dev and attached is a screen of all three (info, debug and error)

<img width="757" alt="screen shot 2019-02-01 at 12 40 49" src="https://user-images.githubusercontent.com/31627284/52124253-8f824900-2620-11e9-9fe5-5663b060232c.png">

Thanks, 
Chris

**Comment by chris-lawton** [comment]
Have also asked @helenb for review of https://github.com/OpenTechFund/opentech.fund/pull/950

**Comment by gibbsmaya** [comment]
Thanks @chris-lawton. @todd-dembrey, please deploy this to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work is the front end work for adding a batch action for adding reviewers (#860). You can access this on the all submissions page at https://test-apply.opentech.fund/apply/submissions/all/.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by helenb** [comment]
Couple of accessibility points noted on #950.

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. 50 points for Gryffindor!

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey for deployment to production.
