### ISSUE TITLE
Search and filters behaviour on submissions overview page

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#864]
**Acceptance criteria**

 - [x] Submission summary table on submissions overview page restricted to 5 most recently updated submissions
 - [x] If more than 5 submissions display 'show all' link which links user to All submissions page
 - [x] Filter/search submit takes user to All submissions page pre-filtered with applied filters or search term
 - [x] No sorting on submission summary table on submissions overview page 

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [ ] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya this is now available for testing on develop

**Comment by gibbsmaya** [comment]
Thanks @todd-dembrey . Have tested and all looks good to me. Please can you complete the QA checklist and then deploy to test?

**Comment by todd-dembrey** [comment]
This is deployed to test and ready for UAT

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is on update to the search and filters behaviour on the  submissions overview page https://dev-apply.opentech.fund/apply/submissions/. Because this is now a summary page, we are only displaying the most recently updated submissions with a show all link to the 'all submissions' listing. Due to this, when search or filtering is used on this summary table, the results are displayed on a pre-filtered/searched version of the 'all submission page. 

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are accurate and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Moving to @todd-dembrey for deployment to production.
