### ISSUE TITLE
Status overview block: backend

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#866]
Designed as the entry to Submissions by Status and provides an overview of the status for all submissions being processed. The statuses will be grouped into similar status to make the visualisation useful across multiple workflow types. 

**Acceptance criteria**

- [x] Status overview block added to Submission overview page
- [x] Statuses should be as follows:
  - [x] Received (all applications in Screening or Proposal received status)
  - [x] Internal Review (all applications in Internal review status)
  - [x] Ready for Discussion (all applications in Ready for discussion status) 
  - [x] More information requested (all applications in More information requested status)
  - [x] Invited for proposal (all applications in Invited for proposal status)
  - [x] Advisory Council Review (all applications in Advisory council review status)
  - [x] Ready for Determination (all applications in Ready for determination, Ready for preliminary determination and Ready for final determination statuses)
  - [x] Accepted (all applications in Accepted status)
  - [x] Dismissed (all applications in Dismissed status)
- [x] Each status displays a count of submissions for the status, counting only “active” rounds and labs 
- [x] Each status inks to the corresponding Submission by Status page.

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805634
Specifically
![screen shot 2019-01-18 at 15 54 35](https://user-images.githubusercontent.com/19690895/51397586-6ef2c300-1b39-11e9-9cd5-e0c02eca689a.png)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now deployed on dev and with Erin for code review. Chris will need to tweak some styling.

Small variation on the AC - We split determined into accepted and dismissed last sprint for the by status view, have continued that here. 
![image](https://user-images.githubusercontent.com/6338661/52771602-35c14c00-302e-11e9-9e2b-29f9ea0ff3de.png)

**Comment by gibbsmaya** [comment]
Hi Todd,

This looks good. I have adjusted the AC based on your comment above and also to match the agreed upon statuses (before we had defined groupings slightly differently). A couple of small things:

 - 3rd status should be named Ready for discussion, not In discussion
 - We should pick a consistent way to present statuses and in fact any titles - currently a mix between sentence case and start case. I think we more frequently use start case so can you ensure all status titles are in this format both in the By Status block (including the title of the block) as well as the titles of each of the By Status pages that it links through to?

Thanks
Maya

**Comment by todd-dembrey** [comment]
I've made the requested changes.

As discussed I've gone for title case for consistency elsewhere on the site.

![image](https://user-images.githubusercontent.com/6338661/52793111-d92d5380-3064-11e9-9774-2e99a5d95f00.png)

I've asked Chris about the alignment of the counts on #1019

**Comment by chris-lawton** [comment]
Have actioned on the PR #1019

**Comment by todd-dembrey** [comment]
All deployed to dev now @gibbsmaya 
![image](https://user-images.githubusercontent.com/6338661/52804451-24069580-307c-11e9-9bf1-71e7ec4193e0.png)

**Comment by todd-dembrey** [comment]
This is now deployed to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work is adding in a "By Status" block to Submissions Overview screen (https://test-apply.opentech.fund/apply/submissions/) to see an overview of how many applications are in each status. This also acts as the entry point to the Submission by Status pages that you tested in the last sprint.

Please test this against the acceptance criteria noted in the initial issue description. Note that we have changed the design from the one linked there as we felt a timeline style design was not appropriate.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thanks! 💥

Will submissions from an active round/lab stay perpetually visible in this block as "Accepted" and "Dismissed"?

**Comment by gibbsmaya** [comment]
That's great, thanks @fourthletter. Submissions will stay in the count until the round it is part of is made inactive (by all submissions within the round being accepted or dismissed).

Assigning to @todd-dembrey for deployment to production.
