### ISSUE TITLE
Status overview block: frontend

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#867]
Designed as the entry to Submissions by Status and provides an overview of the status for all submissions being processed. The statuses will be grouped into similar status to make the visualisation useful across multiple workflow types. 

**Acceptance criteria**

- [x] Status overview block styled as per design - not we have changed the design from the one below as we felt a "timeline" style was not relevant for these statuses since they are not always sequential - it is just really a list of statuses
- [x] 'View' link appears on hover to link through to submission by status page
- [x] On mobile, display statuses + #of applications as list

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805634
Specifically
![screen shot 2019-01-18 at 15 54 35](https://user-images.githubusercontent.com/19690895/51397586-6ef2c300-1b39-11e9-9cd5-e0c02eca689a.png)

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
@helenb - can you review this one please? - https://github.com/OpenTechFund/opentech.fund/pull/941

(It requires BE work hence the mock data)

**Comment by helenb** [comment]
@chris-lawton - have reviewed so back with you.

**Comment by chris-lawton** [comment]
@gibbsmaya - screens of the hardcoded status block:

![screen shot 2019-02-01 at 10 16 16](https://user-images.githubusercontent.com/31627284/52116976-79698e00-260a-11e9-9ee9-45c58e0ae3b0.png)
![screen shot 2019-02-01 at 10 16 26](https://user-images.githubusercontent.com/31627284/52116978-79698e00-260a-11e9-866c-ef6490a2e2bb.png)

**Comment by gibbsmaya** [comment]
Nice one. Can you just confirm that the view link appears on hover for each status?

**Comment by chris-lawton** [comment]
Apologies, thought it was in the screen!

![screen shot 2019-02-01 at 10 20 47](https://user-images.githubusercontent.com/31627284/52117229-1cbaa300-260b-11e9-9708-c774ec9d6a86.png)

**Comment by gibbsmaya** [comment]
Perfect. Marking as complete and this will go into UAT with the backend ticket in the next sprint.

**Comment by todd-dembrey** [comment]
Now on test with #866

**Comment by gibbsmaya** [comment]
UAT being done in #866

**Comment by gibbsmaya** [comment]
Moving to ready for live deployment alongside #866
