### ISSUE TITLE
Submission by status detail view

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#869]
This page is a replica of the Submission by round detail view page but showing submissions in a particular status rather than a particular round.

**Acceptance criteria**

- [x] Application listing (left hand column): Contains same items as the base Submissions by Status list view queryset (submissions in the selected status) without filters applied
- [x] Application listing (left hand column): Submissions are grouped by round
- [x] Application listing (left hand column): Number of submissions in each round are presented
- [x] Application listing (left hand column): If there is an error in fetching this data, display a 'sorry' message
- [x] Application detail view (middle column): Defaults to the first submission in the submission listing on page load
- [x] Application detail view (middle column): Shows the selected submission in the submission listing thereafter
- [x] Application detail view (middle column): Shows the same information as available on the current submission detail page (except the 'edit account' link)
 - [x] Page matches design as per design notes below

Design: as per status by round page https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971428

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- ~~provided good unit test coverage (if this is non-trivial behaviour).~~
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya This is currently deploying to dev for testing.

**Comment by gibbsmaya** [comment]
Hi @todd-dembrey ,

Generally happy with this but one issue I have found is that we seem to have lost the general information about the submissions at the top of the page (name/email etc). This seems to have gone from both the submission by round and submission by status detail views. Unsure if affected by this ticket or not but needs resolving.

![screen shot 2019-02-01 at 11 13 24](https://user-images.githubusercontent.com/19690895/52119849-6bb80680-2612-11e9-9a5d-44e440d4b279.png)


Thanks,
Maya

**Comment by todd-dembrey** [comment]
Good spot, i've made a fix and pushed it to dev.

**Comment by gibbsmaya** [comment]
LGTM. Please deploy to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work is the submission by status page detail view displaying all submissions in a particular status on one page. E.g. https://test-apply.opentech.fund/apply/submissions/received/ (click the switcher in the top right to get from the list view to the detail view). This is just like the Submission by Round detail view page page you reviewed in the last sprint but the submissions are restricted by status and in the left hand column are grouped by round instead of status. 

These are the different pages available to access:

https://test-apply.opentech.fund/apply/submissions/received
https://test-apply.opentech.fund/apply/submissions/internal-review
https://test-apply.opentech.fund/apply/submissions/in-discussion
https://test-apply.opentech.fund/apply/submissions/more-information
https://test-apply.opentech.fund/apply/submissions/invited-for-proposal
https://test-apply.opentech.fund/apply/submissions/external-review
https://test-apply.opentech.fund/apply/submissions/ready-for-determination
https://test-apply.opentech.fund/apply/submissions/accepted
https://test-apply.opentech.fund/apply/submissions/dismissed

Note you will need to access these pages directly on these urls for now as there is no link to them from the site at the moment. In the next sprint we will be creating a jumping off point for these pages from the submission overview page.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Accepted criteria are visible and functional during test. The team receives five blah points!  👍

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey for deployment to live.
