### ISSUE TITLE
Submission by round detail view: Notes tab: Notes list

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#872]
**Acceptance criteria**

- [x] 'Internal' notes are displayed in listing in notes tab
- [x] Notes show author, date and full content
- [x] Notes ordered by date descending
- [x] If no notes to display, show message
- [x] If error when fetching data, show message and allow refresh
- [x] Date is output as GMT

**Design** 
Notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430
No notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971428
Error with notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971427

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by gibbsmaya** [comment]
@tm-kn  this looks good. Have not managed to test the last two AC, the GMT one I think is irrelevant since we are not showing time, do you agree? The other one is about error states which maybe you can show me on your local build (I have also asked Chris the same question so he may be able to do this)?

**Comment by todd-dembrey** [comment]
@gibbsmaya  See below for the unstyled error message
![image](https://user-images.githubusercontent.com/6338661/51977927-a722cb80-2480-11e9-8371-7e7447b5b750.png)

**Comment by tm-kn** [comment]
@gibbsmaya I do agree with your point that timezone is less important since we do not show the exact time. Regardless of that, API returns dates with timezones and front-end explicitly converts them to GMT. Probably the only way is to change timezone on your computer and see if that affects any of the dates, but that's troublesome to test.

**Comment by gibbsmaya** [comment]
Thanks @todd-dembrey and @tm-kn. Happy with your word that it is being output in GMT. Todd, this is ready for deployment to test.
