### ISSUE TITLE
Submission by round detail view: Notes tab: Notes list: front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#873]
**Acceptance criteria**

- [x] Notes tab displayed as per design
- [x] Notes listing displayed as per design
- [x] No notes displayed as per design
- [x] Error when fetching data displayed as per design

**Design** 
Notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430
No notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971428
Error with notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971427

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
@helenb @todd-dembrey can you review this please -https://github.com/OpenTechFund/opentech.fund/pull/911

**Comment by gibbsmaya** [comment]
@chris-lawton this looks good. Have not managed to test the last AC about error states which maybe you can show me on your local build?

One issue I have found is that the notes display is not currently dealing with rich text notes. See 'Maya Tom test 2' on detail view of round: https://dev-apply.opentech.fund/apply/rounds/732/.

**Comment by helenb** [comment]
@chris-lawton a couple of comments - glad that Todd has reviewed too as I don't have the full picture with the react elements.

**Comment by chris-lawton** [comment]
@gibbsmaya - happy to show you on my local build re. the error state design. 

For the rich text - i'm presuming that will be handled when we have the rich text editor in place as per https://github.com/OpenTechFund/opentech.fund/issues/875?

**Comment by chris-lawton** [comment]
passing to @todd-dembrey for review of the React bits

**Comment by gibbsmaya** [comment]
OK, happy to review on your local build in the next day or so. Will also await the rich text backend work being completed to see if it requires any further front end.

**Comment by chris-lawton** [comment]
@gibbsmaya - attached is a screen of my local build for the design of the notes when there's been an error. 

![screen shot 2019-01-30 at 09 49 23](https://user-images.githubusercontent.com/31627284/51973350-548fe200-2475-11e9-8073-53f572b4aaec.png)

**Comment by gibbsmaya** [comment]
Thanks @chris-lawton . @todd-dembrey keeping assigned to you for code review.

**Comment by gibbsmaya** [comment]
@chris-lawton just to add that now the rich text ability is in, I can see that not all rich text elements are styled. Have tried a few here https://dev-apply.opentech.fund/apply/rounds/732/# on 'Maya's test project' which you can see an example where bold italic and list are not styled.

**Comment by todd-dembrey** [comment]
@gibbsmaya It might be better to handle the styling in #876 where we know the output of the richtext editor.

**Comment by chris-lawton** [comment]
@gibbsmaya  - as per Todds comment above suggest we move the rich text styles to #876
