### ISSUE TITLE
Submission by round detail view: Notes tab: Add note (plain text)

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#874]
**Acceptance criteria**

- [x] Plain text block available to add note
- [x] Can submit note 
- [x] When note is being submitted the note remains within the editor but editing is disabled
- [x] Send button disabled while submitting
- [x] If error while note is being submitted, display message about error (e.g. "no network connection", 500: "Unable to process")
- [x] When note is submitted the note appears as normal at top of note list
- [x] Note appears on submission as internal comment
- [x] Notifications on comment sent as normal

**Design**
General: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430

**Comment by todd-dembrey** [comment]
Reviewed and back with @tm-kn for some small changes.

**Comment by todd-dembrey** [comment]
This is now on dev for review, but would probably be best reviewed alongside #876

**Comment by todd-dembrey** [comment]
#875 Is also deployed so some of the acceptance criteria here may not make sense anymore.

**Comment by tm-kn** [comment]
>  Notifications on comment sent as normal

Hi @gibbsmaya, this will not work since that relies on refreshing the page. I assume that is just the debug messages that you meant in this AC? Let me know if that's fine by you.

**Comment by gibbsmaya** [comment]
Hi @tm-kn, so the notifications don't get sent until the page is refreshed?

Have tested what I can for now. Will test other items once #849 is complete as currently activity feed is blocking the submission block (this is with Erin).

**Comment by tm-kn** [comment]
> Hi @tm-kn, so the notifications don't get sent until the page is refreshed?

The notifications should be sent in the background as far as I understand @todd-dembrey explanation. It's just the debug notification bar at the top of the page not showing until the page is refreshed.

**Comment by gibbsmaya** [comment]
Thanks for the explanation Tomasz. Happy for this to be marked as done and be deployed to test @todd-dembrey
