### ISSUE TITLE
Submission by round detail view: Notes tab: Add note (rich text)

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#875]
**Acceptance criteria**

- [x] Rich text block available to add note
- [x] Can submit note 
- [x] When note is being submitted the note remains within the editor but editing is disabled
- [x] Send button disabled while submitting
- [x] If error while note is being submitted, display message about error (e.g. "no network connection", 500: "Unable to process")
- [x] When note is submitted the note appears as normal at top of note list
- [x] Note appears on submission as internal comment
- [x] Notifications on comment sent as normal

**Design**
General: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- ~~provided good unit test coverage (if this is non-trivial behaviour).~~
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by tm-kn** [comment]
PR - #899

**Comment by todd-dembrey** [comment]
Reviewed and deployed to Dev for testing.

Outstanding issue about how we are currently miking two markdown libraries which is causing render issues. But we can test the functionality of data leaving the form.

**Comment by gibbsmaya** [comment]
Testing what I can for now. Will test other items once #849 is complete as currently activity feed is blocking the submission block (this is with Erin).

For now, Tomasz is there any way you can show me this AC is satisfied? "If error while note is being submitted, display message about error (e.g. "no network connection", 500: "Unable to process")"

Also, please can you complete the QA checklist?

**Comment by tm-kn** [comment]
![image](https://user-images.githubusercontent.com/14931760/52000911-1f57b400-24b6-11e9-8288-4374923c7421.png)

**Comment by tm-kn** [comment]
Needs to get #936 in. There were changes in other area that affected this behaviour.

**Comment by gibbsmaya** [comment]
Hi @tm-kn 

As discussed with @todd-dembrey , please apply the following changes to finalise the rich text work:

 - [ ] Don't output markdown from rich text editor (confirm renders html in communications tab on submission correctly)
 - [ ] Render comments serverside into html
 - [ ] Restrict rich text options to: bold, italic, hyperlink, UL, OL

Thanks,
Maya

**Comment by todd-dembrey** [comment]
Tidied up the options - added some flexibility with the text size (h1 and h2) and normal which wasn't in your list.

**Comment by gibbsmaya** [comment]
Happy for this to be deployed to test.
