### ISSUE TITLE
Submission by round detail view: Notes tab: Add note: front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#876]
**Acceptance criteria**

- [x] Add note block displayed as per design
- [x] Submit button displayed as per design
- [x] When note is being submitted the editor is disabled and styled to reflect this (translucent overlay?)
- [x] Send button styled as disabled while submitting
- [x] On mobile, submit comment block brings up native keyboard

**Design**
General: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Ready for review - https://github.com/OpenTechFund/opentech.fund/pull/930

@gibbsmaya - this is now on dev if you wanted to review ahead of the code review

**Comment by gibbsmaya** [comment]
Thanks @chris-lawton, have had a look and can submit notes, but the submit button is invisible at the moment. There is obviously the issue of the activity feed being there which it shouldn't be, but even behind that the buttons are not visible (though I can click where I think they should be and it submits the note!). Using https://dev-apply.opentech.fund/apply/rounds/732/# as my test.

**Comment by chris-lawton** [comment]
Have now improved the visibility of the button by using a darker border colour

**Comment by chris-lawton** [comment]
waiting for feedback on which rich text elements can be hidden before styling

**Comment by chris-lawton** [comment]
@gibbsmaya - activity feed button has now been hidden when the app is open, so should make testing a bit easier now!

**Comment by gibbsmaya** [comment]
Thanks @chris-lawton this all looks good. Have a comment on the activity feed button but will put that on #849. I am struggling to test the mobile AC at the moment as the detail view page on mobile is not loading.

**Comment by gibbsmaya** [comment]
Hi @chris-lawton this looks good and all AC are met. I have noticed two things on mobile though:

1. long names need to be truncated (same issue as we had before with email addresses showing instead of names which runs into the date)
2. I think we need something to separate the notes list and the add note area - it currently sort of merges into one.

Screenshot from mobile showing both points:
![screenshot_20190131-101102_chrome](https://user-images.githubusercontent.com/19690895/52047428-def14800-2540-11e9-8e82-ce6b8ade5799.jpg)

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

Truncated names and mobile styling for the notes panel are now on dev.

Cheers,
Chris

**Comment by gibbsmaya** [comment]
Thanks @chris-lawton . Looks good, only follow on comment is to we need the '...' when we are not truncating? Currently it is showing after every name, even if short.

Separate to this can you complete the QA criteria and then we can sign this off?

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

Names that are over 16 chars are truncated and anything below will display as normal.
Have also checked the QA.

Thanks,
Chris

**Comment by gibbsmaya** [comment]
LGTM. Passing to @todd-dembrey for deployment to test.
