### ISSUE TITLE
Submission by round detail view: Polling

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#877]
**Acceptance criteria**

- [x] Comments list updated every 30 seconds

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya  this is now testable on dev

**Comment by gibbsmaya** [comment]
Hi @todd-dembrey I have tested this by adding an internal comment on a submission and seeing it update on the detail view page. only issue is that it adds the comment at the bottom of the list instead of the top. See Project demo on https://dev-apply.opentech.fund/apply/rounds/777/ as an example.

**Comment by todd-dembrey** [comment]
@gibbsmaya I've updated this to now add the new comments to the beginning of the list

**Comment by gibbsmaya** [comment]
LGTM. Please deploy to test.

**Comment by todd-dembrey** [comment]
This is now on test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work adding in automated updated to the Submission by Round/Status Detail View pages so that if changes are made while you are viewing the page they are updated without you having to refresh the page. The best way to test this is to go to one of the Submission by Round/Status Detail View pages e.g. https://test-apply.opentech.fund/apply/rounds/732/ (remember to click on the switcher in the top right to get to the detail view page!) - keep this open and in another tab or window open the same page, on the same submission. Add a note on on of these tabs and watch it update automatically in the other version of the page. Note it polls for data every 30s so you may need to wait up to 30s to see the change. 

Please test this against the acceptance criteria noted in the initial issue description. 

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Acceptance criterion is visible and functional during test. Thanks! 💥

**Comment by gibbsmaya** [comment]
That's great, thanks @fourthletter. Assigning to @todd-dembrey for deployment to production.
