### ISSUE TITLE
API: complete required features from API spec

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#878]
Tasks

- [x] status filter on submissions list GET
- [x] active filter on submissions list GET
- [x] review summary on submission GET

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [ ] checked that this feature works on the server/s I am deploying it to.

QA:

 * [ ] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [ ] checked that the feature works on the server/s deployed to

**Comment by tm-kn** [comment]
Reviewed the pull request. I am happy for that to go onto dev.

**Comment by gibbsmaya** [comment]
@todd-dembrey this isn't one I can test, so if you can finalise the QA criteria, happy for you to move this into done.

**Comment by gibbsmaya** [comment]
@todd-dembrey this is ready to be deployed to test.
