### ISSUE TITLE
User log in

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#889]
Two users can't sign-in to view their WebApp. I sent both of them the password reset link, but want to see if there are other technical issues beyond a password reset. I could send you their names and emails directly. Thank you.

**Comment by frjo** [comment]
@fourthletter I believe we have deployed code that fixes the main issue of people not being able to use the password reset form.

All users should now be able to use the password reset form themselves (they must first have clicked the activation link to activate their accounts).

If they say they can't find it (there is a link to it on the login form) it's usually easier to do it for them, as you have done, then try to direct them.
