### ISSUE TITLE
API: Proposed messaging extensions

### ISSUE THREAD

**Issue by jheretic** [OpenTechFund/opentech.fund#905]
This outlines proposed extensions to the API specification to support additional messaging capabilities. Sorry to get this in probably too late for this sprint.
### Submissions
**GET /submissions/?<query>**
In addition to the query parameters specified previously, we also have the following parameter:
**Query:**
- `submitter=<uid>` Filters to submissions by a specific uniquely identified user. Currently this is the user email address.

### Users
**GET /user/?<query>**
Fetch matching users based on a query containing one or more possible user object fields. Current fields listed below, but could additionally include `signalnumber`.
**Query:**
- `email=<emailaddress>` Filters to a specific email address. Also doubles as user ID.
- `full_name=<string>` Filters to a user’s full name. Preferably allows for globbing.
- `is_staff=<bool>` Filters to staff or non-staff members if specified.
- `is_applicant=<bool>` Filters to applicants or non-applicants if specified.

**Return:**
- Array of matching JSON objects, containing the parameters listed above. Returns an empty array if there are no matches.

**Comment by danblah** [comment]
@Parbhat and @frjo how does look to y'all? Can we add this to your queue to implement?

**Comment by Parbhat** [comment]
@danblah @frjo looks good. Not sure but the API specification implementation work is WIP. The enhancements work can be started after the initial API is ready.

**Comment by todd-dembrey** [comment]
Yes, it'll be a small add to the work we are currently doing.

Whats missing from this is the authentication changes that @jheretic will need if he is access the API from outside a session.

**Comment by saoun** [comment]
@jheretic @frjo what is the status on this? can it be closed?
