### ISSUE TITLE
UX improvements to Rounds and IA (to finalise WS 1 work)

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#906]
Now that all sprint 1 work is in, there are a few tweaks we want to make prior to deployment to production to make the journeys more coherent and tidy up a few bits.

- [x] Remove 'Rounds' from main menu (this is currently confusing things - Submissions overview should be the central point to access all things submission, i.e. route to all rounds page is via 'All rounds and labs' block on submission overview). 
- [x] Remove ' <- Submissions' link from Submissions by Round header (the breadcrumb) - this is confusing as there are various routes into this page, not all of which come directly from Submissions.
- [x] Take away the concept of only showing 'active' rounds in the 'All Rounds and Labs' block on submission page and dashboard. Limit this to 5, with a show all link going to All Rounds page.
- [x] Position switchers on Submissions by Round page the other way round, i.e. list view on the left and detail view on the right (because the list view is the default view you land on).

**Comment by chris-lawton** [comment]
Leaving with Todd to give it a once over

**Comment by fourthletter** [comment]
All elements within this issue to capture all sprint 1 work is accurate and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Moving to @todd-dembrey for deployment to production.
