### ISSUE TITLE
Assigning a value to slack channel in a fund doesn't send notification and also stops all notifications into the primary notification channel

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#916]
See https://github.com/OpenTechFund/opentech.fund/pull/757

1. Went to https://apply.opentech.fund/admin/pages/726/edit/?next=/admin/funds/fundtype/
2. Set channel
3. Submitted test application, email sent to the applicant no notifications to primary channel or declared channel
4. Sent test comments, no notifications sent (email sent)
5. Unset value, added comment notification sent to the primary channel

Expected behavior
1. Channel set in fund/lab
2. Notifications go to the declared channel and the site-wide default notification channel

**Comment by frjo** [comment]
That the custom channel is not working is a bug. That no notification is sent to the default channel is a missed requirement.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
@danblah It works when I test it, but only after I added the WebApp app to the channel. Did you add that to the channel when you tested?

**Comment by danblah** [comment]
oh, didn't know that was a requirement... testing.

**Comment by danblah** [comment]
That did it, now working. Still need to also send notifications to the site-wide notify channel. Is there a way we can have the bot join the channel on its own or send an alert somewhere that it needs to be added?

**Comment by danblah** [comment]
Will close this one and make a ticket for the enhancements.
