### ISSUE TITLE
There is no way to view or link to reviews or determinations in the new round view for calls

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#923]
On review calls, the first thing we do is review the teams reviews and any last submission responses. Right now, we see the submission but there is no way to get to or view the reviews. Basic requirement would be to drop a link that opens a the actual submission page in a new window so we can see these reviews. Next would be some listing of the reviews and submissions in the view that open them up, even better would be some way to load those within the current view (not having to open new tabs/etc).

**Comment by frjo** [comment]
@danblah Is it this view we are talking about https://apply.opentech.fund/apply/rounds/229/ ?

The submission title is a link to the submission and command/ctrl clicking it will open it in a new tab. Easy to have it open in a new tab by default.

When one "opens up" a submission in that view to see more info the reviews are listed, we could make the reiviewwea names in to links ans also add in the determinations beside the reviews, also as links that open in new tabs.

**Comment by danblah** [comment]
We're talking about the other view, the one with the 3 vertical columns, where we can take notes during a call.

**Comment by gibbsmaya** [comment]
FYI, as a better longer term solution, the plan for the status tab on this page

![screen shot 2019-01-29 at 15 42 55](https://user-images.githubusercontent.com/19690895/51920269-fa434280-23dc-11e9-9f52-91cef1513fcd.png)

is to display status information and allow status actions to be taken. This will be a subset of this display:

![screen shot 2019-01-29 at 15 44 54](https://user-images.githubusercontent.com/19690895/51920327-19da6b00-23dd-11e9-95f1-35fda7cc8512.png)

Our current thinking is that this would show available actions to take as 'update status' and then show the screening block and the determination block.

We could then add a third tab called Reviewers which displays the same information as this block:

![screen shot 2019-01-29 at 15 44 37](https://user-images.githubusercontent.com/19690895/51920423-442c2880-23dd-11e9-803f-728fa66ae2ff.png)

which allows linking out to the actual review.

@danblah does this seem to meet the requirements you need on the review call?

**Comment by gibbsmaya** [comment]
Note, that this is planned to be tackled in the next sprint.

**Comment by frjo** [comment]
@gibbsmaya I have merged in my quick hack so OTF have something for the time being. @danblah preferred that option.

When you get to this you revert my hack and to it the proper way.
