### ISSUE TITLE
Change our site-wide font to an open source one, from Proxima Nova to similar Montserrat

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#924]
See https://we.opentech.fund/t/switch-otf-typography-to-an-open-source-one/971/2 for more info.

**Comment by elioqoshi** [comment]
Thanks for filing this here @danblah.

@anxh3l0 and me would be happy to help with this in any case.

**Comment by elioqoshi** [comment]
Also notice: Montserrat might not be ideal for big chunks of texts (Paragraphs) so it could also be considered adapting Montserrat for headings / labels and another typeface for large bodies of text. Noto Sans is the typeface which supports most languages and glyphs with great readability as well,

Happy to do more analysis on this.

**Comment by frjo** [comment]
Please test on https://test-apply.opentech.fund

I have switch to Montserrat for headings and to Noto-Sans for everything else. Nothing elsed has changed.

These font displays a bit bigger etc. so are not a direct drop in replacement. Please compare pages on test and live to see how you like it and if any other changes are needed.

**Comment by fourthletter** [comment]
The font displayed on the test page looks good. We do not need additional changes to this issue. Thanks!

**Comment by elioqoshi** [comment]
I can't see the preview as I don't have a token for that site, but I'd agree Montserrat is not great for Body text. Noto Sans is perfect as it has the highest number of glyphs and language support of all fonts families.
