### ISSUE TITLE
Dashboard: Waiting for your review block

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#937]
The block will be used on the dashboard to list submissions where the user has been assigned as reviewer. Note this already exists but tweaks should be made to meet acceptance criteria as below.

_Note: “Since you last logged in” will not be built as part of this phase of work but can be added as a github issue for future development._

**Acceptance criteria - as an OTF staff member**
- [x] Title of block is 'Waiting for your review'
- [x] Number of applications I am assigned to review displays alongside title as per design
- [x] Lists applications I am assigned to review
- [x] Applications ordered by submission date descending
- [x] Table columns should be as per All Submissions tables
- [x] Limit number of submissions to 5, if more than 5 show all link to appear (as per other summary tables) and link to all submissions page pre-filtered by reviewer
- [x] If no submissions in this list, show message as per design with link to all submissions page, no pre-filtering.
- [x] There is no checkbox column and there are no batch actions.

**Acceptance criteria - as an AC reviewer**
- [x] “Waiting for your review” will not link to the Submissions page when empty
- [x] “Waiting for your review” will only populate with submissions in the external review status and assigned to the AC reviewer

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805633

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
This is now ready for testing @gibbsmaya

**Comment by gibbsmaya** [comment]
Tested and most AC working as expected. There is some weird behaviour going on here though. If you 'become' Lindsay Beck you can see there are firstly some duplicates in the waiting for your review list on the dashboard. Also the count is incorrect if you then link to 'all submissions'
![screen shot 2019-02-07 at 17 45 31](https://user-images.githubusercontent.com/19690895/52431767-cc5aae00-2b00-11e9-82e3-4d8e450c5576.png)

**Comment by emullaney** [comment]
Hi @gibbsmaya this should be fixed as of yesterday with a fix out to `develop`.

**Comment by gibbsmaya** [comment]
Thanks @emullaney. This all looks good. There are a few things we need to define with OTF as this work has thrown up a few oddities but this is separate to the actual work on the ticket.

@todd-dembrey can you please deploy to test?


Note to discuss with OTF:

Overarching question is which states should be counted as 'waiting for your review' when technically you can review at many parts of the workflow? This is currently manifesting in the waiting for review block whereby the logic is displaying all applications in a "reviewable" state. This, when we originally launched the site, had more meaning as OTF staff could only review when in 'internal review' but now this permission has been lifted, meaning that OTF can also review at other states, including 'Advisory Council review' which is also a reviewable state. Therefore Waiting for your review block shows both applications in Internal review and AC review.

Secondly, the Show all from here takes us to a page where we are filtering by applications where I am a reviewer. This currently shows applications in all states - thereby making the list longer, and the number of applications here inconsistent with the count on the waiting for your review block on dashboard. 

Need to discuss what is useful here for OTF staff to see - both for the dashboard view and the corresponding 'show all' view coming from this. Maya to discuss with Dan/Di.

**Comment by gibbsmaya** [comment]
After discussion with OTF, agreed approach for an initial release is that both waiting for your review and the corresponding 'show all' page should show all submissions where I am assigned as reviewer, in any status other than a final determined state, i.e. all states other than accepted, dismissed, concept accepted and invite to proposal (?status=screening&status=more-information-required&status=internal-review&status=ready-for-discussion&status=ready-for-determination&status=advisory-council-review&status=ready-for-preliminary-determination&status=proposal-received&status=ready-for-final-determination&reviewers=9&query=). The waiting for review block on dashboard should show the first 5 in the list as it does now, linking to all submissions prefiltered in the same way.

**Comment by todd-dembrey** [comment]
This is now on test.

@gibbsmaya is the above captured in another issue?

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work is adding in a block to users dashboard to see submissions awaiting review from me. As discussed on the call earlier today, this agrees to the specification we agreed however we think some tweaks need to be made to this to make it more useful to you. I have outlined these changes above and will raise a separate issue for it now for @frjo to undertake.

For now, please test this against the acceptance criteria above. You should test this as both an OTF staff member and an AC staff member - you can manipulate the data on the test site in terms of assigning reviewers and completing reviews to test this. 

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Acceptance criteria are visible. Thanks!

Only one submission appears in my "waiting for your review" dashboard so I'm not able to see criteria: 1) the first five and 2) submissions in descending order.

**Comment by gibbsmaya** [comment]
@fourthletter you can add more test submissions or add yourself as review and change statuses of submission to test. Otherwise, if you are happy for this to go as is following our testing then we can push this through to be ready for deployment. Please confirm.

**Comment by fourthletter** [comment]
Acceptance criteria are visible. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter will assign to @todd-dembrey ready for deployment to live.
