### ISSUE TITLE
Dashboard: Previous reviews block

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#938]
The block will be used on the dashboard to list submissions where the user has submitted a review for.

**Acceptance criteria**
- [x] Title of block is 'Your previous reviews'
- [x] Lists applications I have submitted a review for
- [x] Applications ordered by submission date descending
- [x] Table columns should be as per All Submissions tables
- [x] Limit number of submissions to 5, if more than 5 show all link to appear (as per other summary tables) and link to all submissions page pre-filtered by reviewer
- [x] If no submissions in this list, do not show block
- [x] Filter and search available as per submissions summary block on submissions overview page
- [x] Block shows for OTF staff and AC reviewers
- [x] There are no batch actions available for this table

For OTF staff:
- [x]  When I click through "Show All" under "Previous Reviews" block, I go to submissions/all filtered by Reviewers=myself

For AC reviewer:
- [x] All submissions table is limited to only submissions I have reviewed. I cannot see any other submissions in this table regardless of the applied filters.
- [x] There is no filter for "reviewed by"
- [x] There is no filter for "reviewers"

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/335805633

**Tech notes**
new filter should be added in a similar manner to existing filters. see:
https://github.com/OpenTechFund/opentech.fund/blob/6936907b10ab3fe98fce225686c03af72036ac94/opentech/apply/funds/tables.py#L143

we can improve the add a new queryset method for reviewed by in a similar manner to `in_review_for`, found here: 
https://github.com/OpenTechFund/opentech.fund/blob/6936907b10ab3fe98fce225686c03af72036ac94/opentech/apply/funds/models/submissions.py#L83-L88

Varying the base view handled as below:
https://github.com/OpenTechFund/opentech.fund/blob/e89491bfe9fe002cc79d9a5a4a6f09031c69c3ad/opentech/apply/funds/views.py#L431-L433

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
This is now ready for testing @gibbsmaya

**Comment by gibbsmaya** [comment]
Hi @emullaney,

Thanks for this. Have tested and ticked off most acceptance criteria. A few things to resolve below:

 - [ ] Title should be "Your previous reviews"
 - [ ] When filters/search are used from the previous reviews block, the behaviour should match that of the summary tables on the Submission Overview page - taking the user to the all submission page, pre-filtered/searched.

**For AC reviewers:**
 - [ ] We should remove the statuses filter as this is irrelevant for them (anything here should only be in AC review status)

Thanks,
Maya

**Comment by emullaney** [comment]
Hi @gibbsmaya I've made changes on my pull request for these fixes and pushed them out to `develop` as well.

**Comment by gibbsmaya** [comment]
@emullaney all looks good to me. Please can you complete the dev QA checklist and if all complete then assign to @todd-dembrey for deployment to test? Thanks.

**Comment by todd-dembrey** [comment]
This is now on test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work is adding in a block to users dashboard to see previous reviews they have completed. You should test this as both an OTF staff member and an AC staff member - you can manipulate the data on the test site in terms of assigning reviewers and completing reviews to test this. 

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
@gibbsmaya could I please get the link to this bit of work? This might be an issue with my admin level, but I'm not able to view the "previous reviews block" in the dashboard screen. Thanks.

**Comment by gibbsmaya** [comment]
Hi @fourthletter 

If you have not done any previous reviews in the test system then none will display here. Easiest way to test is to add some reviews for some of the applications on the test site and then check the block appears for you appropriately. @danblah should also be able to test this as an admin by using the 'become' feature.

Let me know if you need any further assistance?

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. 50 points for Hufflepuff!

**Comment by gibbsmaya** [comment]
Assigning to @todd-dembrey for deployment to live.
