### ISSUE TITLE
Allow comments to be edited by the author and if edited, display an "edited on" date after post date.

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#945]

**Comment by fourthletter** [comment]
Similar to issue #325

**Comment by todd-dembrey** [comment]
Is this an extension of #1128 ? 

This will apply to all comments/notes in both the react app and django pages?

**Comment by frjo** [comment]
I think it would be enough to edit them in Django. It’s mainly @fourthletter that need to edit meeting notes later on. Fixing spelling, and stuff etc. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danblah** [comment]
Just correcting that this is actually more for applicants, who post comments, forget something or want to edit something, in response to determinations, and then end up posting multiple comments.

**Comment by gibbsmaya** [comment]
**Acceptance criteria**

- [ ] Private comments in django app allow editing by the author of the comment
- [ ] Reviewers and Staff comments in django app allow editing by the author of the comment
- [ ] Internal comments in django app allow editing by the author of the comment
- [ ] Public comments in django app allow editing by the author of the comment
- [ ] Edit button visible on comment (styled as per edit button on submission detail page)
- [ ] Inline editing of comment with 'submit' and 'cancel' button
- [ ] Updated comment to display on edit submission
- [ ] Last edited date to be displayed alongside post date
- [ ] Comment sort order remains as it currently is (by original post date)

**Comment by abigail-hampson** [comment]
Hello, 

This is now ready for testing against the acceptance criteria above. An example for this can be tested here -  https://test-apply.opentech.fund/apply/submissions/26/#communications

**Comment by fourthletter** [comment]
Acceptance criteria were all visible and functional. Thanks! 💥
