### ISSUE TITLE
Error when submitting test form

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#946]
See https://www.opentech.fund/about/jobs/test-form/
Tested with both logged in and unlogged in account.

Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.

More information is available with DEBUG=True.

**Comment by frjo** [comment]
This was due to Cloudflare cache everything rule.
