### ISSUE TITLE
Submission by round detail view: Notes tab

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#951]
Creating an overall ticket for UAT of the notes tab on the detail view page: the ability to add notes to submissions, view them in the notes list and ensure that notes are correctly associated with individual submissions. Note this covers work undertaken in #876, #874, #872, #873 and #875.

**Acceptance criteria - add note**
- [x] Rich text block available to add note
- [x] Can submit note 
- [x] When note is being submitted the note remains within the editor but editing is disabled
- [x] Send button disabled while submitting
- [x] If error while note is being submitted, display message about error (e.g. "no network connection", 500: "Unable to process")
- [x] When note is submitted the note appears at top of note list
- [x] Note appears on submission as internal communication
- [x] Notifications on comment sent as normal
- [x] Add note block displayed as per design
- [x] On mobile, submit comment block brings up native keyboard

**Acceptance criteria - notes list**
- [x] 'Internal' notes added on a submission from within the communication tab are displayed in listing in notes tab on the detail view page
- [x] Notes show author, date and full content
- [x] Notes ordered by date descending
- [x] If no notes to display, show message as per design
- [x] If error when fetching data, show message and allow refresh
- [x] Notes listing displayed as per design

**Design**
Notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971430
No notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971428
Error with notes: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/340971427

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah

This work is now ready for testing. This work captures all the work done on the Notes tab in the right hand column of the Submission by Round detail view page e.g. https://test-apply.opentech.fund/apply/rounds/732/. As per the issue description, this is a specific testing issue which covers five development issues that have been worked on. This functionality allows you to add notes to submissions from this screen to meet your need of adding notes in review calls. The notes are associated with individual submissions and are also displayed on them. You will note there is a status tab alongside the notes tab which which is currently empty and will be developed in the next sprint to allow you to update status from here too.

Please test this against the acceptance criteria noted in the initial issue description where you will also see a link to the design.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Acceptance criteria are visible and functional. Thanks! 💥

In regards to "Notifications on comment sent as normal": I am able to view submission of a new note in the "view message log," but a notification does not appear in the activity feed and slack. It is not critical for a notification to appear in the activity feed or slack.

**Comment by gibbsmaya** [comment]
Hi @fourthletter,

The comment should be recorded on the activity feed for the submission as an internal comment - is this not the case? Can you link to an example submission where you have added a note and this has not been added to the activity feed?

Regarding slack messages, the test site is set up to go to webapp-test channel which we assume is with the opentech slack workspace. We don't have access to this. Can you check whether the notifications have gone there?

Thanks,
Maya

**Comment by danblah** [comment]
Slack msg went out just fine for me but confirming that comments are not being recorded in the activity feed. I'd expect something similar in the activity feed as we get in slack, ie "A new internal comment has been posted on Maya's test project by Dan Blah". See https://test-apply.opentech.fund/apply/submissions/1/#communications. 

Doesn't seem comments have every been creating an entry in activity feed to date, just the communications tab.

I'm generally fine to call this accepted and create another issue for adding comments into the activity feed later as needed.

**Comment by gibbsmaya** [comment]
Hi @danblah,

Thanks for the example. Apologies, I realise my working was incorrect on the acceptance criteria as the messages don't appear on the activity feed, rather they appear on the communications tab as you say. The acceptance criteria should have read 'communications tab' rather than 'activity feed'.

Comments have always been only entered into the comms tab, whereas actions are entered into the activity feed. On the main activity feed on the submissions listing page (https://test-apply.opentech.fund/apply/submissions/) you will see there is also an 'all' tab which displays activities and comms together.

I agree if this is an issue then it should be raised as a separate issue as this is the way the system has always functioned. But for now I think that this separation makes sense.

Marking this as done to prepare for deployment to live.

Thanks,
Maya

**Comment by todd-dembrey** [comment]
closed by #995
