### ISSUE TITLE
Review updates: reviewer role and add reviewer roles

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#957]
The purpose of this is to fill the need for Reviewers fulfilling different roles within the review process within OTF. We will provide a means to “tag” reviewers with the type of review that they are required to complete. This will have no behavioural effect, you can have any number of roles and you will have access to the full range of review methods. It is up to the User to understand what the role means.

This issue is to add a new Wagtail taxonomy for reviewer role and ability to assign OTF staff to role. 

**Acceptance criteria**
- [x] 'Reviewer role' taxonomy added to Wagtail admin within the 'Apply' menu
    * Fields for Role: Name & icon  
- [x] "Add reviewer" form updated to display multiple lists for adding reviewers, one for each of the defined roles within the taxonomy.
- [x] The “Staff Reviewers” dropdown will be repeated for each Role as `“<Role> Reviewers”`
- [x] The "Reviewers" dropdown should remain unaffected (External reviewers only includes AC reviewers)
- [x] Users can only be selected for one Role. Assigning users to multiple roles will display validation error "Cannot be assigned to multiple roles"
- [x] Selection for each role should be single select rather than multiselect, i.e. you can only select one person per role
- [x] Only OTF staff can be selected for a Role.
- [x] Updates to messaging (activity feed, slack notification) to include the role of the assigned reviewer `"<Reviewer> added as <Role>"`

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/343687953

**Dev Notes**
Affected form and field:
https://github.com/OpenTechFund/opentech.fund/blob/e89491bfe9fe002cc79d9a5a4a6f09031c69c3ad/opentech/apply/funds/forms.py#L52-L57

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [ ] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [ ] checked that the feature works on the server/s deployed to

**Comment by emullaney** [comment]
@gibbsmaya this is ready for review on develop. I noticed that the images on develop are broken but I don't think that's related to this change.

**Comment by todd-dembrey** [comment]
@gibbsmaya We have not needed images on dev until this point and have not set it up.

@frjo is setting this up tomorrow morning (Tuesday 12th Feb)

**Comment by todd-dembrey** [comment]
@gibbsmaya @emullaney Images are now working

**Comment by gibbsmaya** [comment]
Hi Erin,

This mostly looks good and meets acceptance criteria. A few things I have noticed if you can take a look please:

 - [ ] Staff reviewer roles (primary and secondary) should appear above the External reviewers in the Add reviewers modal.
 - [ ] When checking if the same user has been added to both primary and secondary roles, we seem to be submitting the form, reloading the page, giving an error notification at the top of the page, and then when you re-open the 'add reviewers' modal there is a validation message of 'Users cannot be assigned to multiple roles'. Is there any way we can validate when the form tries to submit so the user gets the validation error within the modal rather than needing a page refresh and then reopening the modal?
 
Thanks,
Maya

**Comment by todd-dembrey** [comment]
@gibbsmaya this is now on dev for you to test. 
Changes are: 
* ordering of fields so that external reviewers are at the end
* Message removed
* modal will auto-open on form errors after submissint

**Comment by gibbsmaya** [comment]
Great, this looks good to me. Please deploy to test @todd-dembrey.

**Comment by todd-dembrey** [comment]
This is now on test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina 

This work is now ready for testing. This work is adding a new concept of Reviewer Role, manageable by admin, and allowing these roles to be assigned to reviewers by OTF staff. Managing the actual reviewer roles is done via the Apply menu in the Wagtail admin. This can only be done by Admin role. I have added Primary and Secondary for now as examples. You can then, as an OTF staff member, add reviewers in the normal way from a submission page but assign primary and secondary reviewers instead.

Please test this against the acceptance criteria noted in the initial issue description.

Note that the proper display of these role assignments and the follow on actions of aggreeing/disagreeing with a review is yet to come, later in this sprint, so for now you are just testing managing the review roles and assigning them to OTF staff.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by danblah** [comment]
Looks good, confirming that I can see them, they are set, and that I can set a primary/secondary for a submission, and that those submissions show up in my dashboard, regardless of primary/secondary setting.

**Comment by gibbsmaya** [comment]
Thanks @danblah . Assigning to @todd-dembrey to prepare for live.
