### ISSUE TITLE
Review updates: batch add reviewer

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#958]
This issue is to allow the new reviewer roles to be added in batch.

**Acceptance criteria**
- [x] Batch add reviewer action updated to display multiple lists for adding reviewers, one for each of the defined roles (as per individual actions).
- [x] Batch reviewer activity text changed to be `"<reviewer> assigned as <role>"`  per role.
   * Slack
   * Activity feed

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/343687953

**QA criteria**
Dev:

- [ ] checked feature meets acceptance criteria/conforms exactly to the specification.
- [ ] provided good unit test coverage (if this is non-trivial behaviour).
- [ ] checked all tests for the project pass with this feature enabled.
- [ ] checked code conforms to the project coding standards.
- [ ] had code reviewed by another developer and resolved any issues raised.
- [ ] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [ ] checked that this feature works on the server/s I am deploying it to.

QA:

 * [ ] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [ ] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
This is now deploying to dev

**Comment by gibbsmaya** [comment]
Happy for this to be deployed to test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

I am adding in the testing notes here. @todd-dembrey is yet to deploy this to live, but as soon as he does (very soon!) he will update this to confirm. For when he does - here are the testing notes:

This work is now ready for testing. This work is amending the batch review functionality for you to be able to batch add reviewers of specific roles.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by todd-dembrey** [comment]
This is now on test

**Comment by fourthletter** [comment]
@todd-dembrey I'm getting an internal server error when I attempt to add reviewers as a batch action. I am getting the same error message when I attempt to add a reviewer to a single submission.

**Comment by todd-dembrey** [comment]
I'm really sorry. I thought this was deployed but it wasn't. Deploying it now.!

**Comment by todd-dembrey** [comment]
@fourthletter This has now deployed and i have tested it on the site! Sorry about that.

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thanks! 🎅

**Comment by gibbsmaya** [comment]
Ready for deployment to live
