### ISSUE TITLE
Review updates: display assigned review role

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#959]
This issue covers the output of the new reviewer roles in the various places the reviewer roles are currently output.

**Acceptance criteria**
- [x] Review Block in right hand column of submission detail page (e.g. https://dev-apply.opentech.fund/apply/submissions/15/) updated to show the type of review assigned reviewers are expected to undertake (outputting icon depending on assigned role e.g. primary or secondary reviewers)
- [x] Any existing assigned reviewers are unaffected and will remain displayed in the review block.
- [x] Listing tables for 'Waiting for my review' on dashboard will include an extra column for my assigned Role (for OTF staff only)

Design: https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/343688448 (we are only looking here at the addition of the icon - the rest of the design will be dealt with in a subsequent issue)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by emullaney** [comment]
@todd-dembrey - this is ready for [review](https://github.com/OpenTechFund/opentech.fund/pull/1014)

**Comment by emullaney** [comment]
FYI @gibbsmaya this is still waiting for further code review after I made changes per the first review, but it has been merged into develop for testing.

**Comment by gibbsmaya** [comment]
Have testing this and a few notes below @emullaney:

A date is appearing the the reviewer block underneath each reviewer's name - can this be removed please?

I am nervous that the existing reviewers (without role) are not displaying any more. I don't have a specific example of this for sure but I find it unlikely that all submissions currently on dev do not have any reviewers pre-assigned, without a role, who have not completed a review. Can you look into this please to confirm?

Can the new 'Assigned role' column in the waiting for your review table display before comments please? i.e. after Reviews.

**Comment by todd-dembrey** [comment]
@gibbsmaya The date was added by fredrik in #926 at the request of OTF in #922. We should probably not just remove it - though it will impact on the reviewer consensus work coming up.

Perhaps discuss with @tmsndrs on Monday?

**Comment by emullaney** [comment]
Hi @gibbsmaya I made some more edits per Todd's review and pushed back up to develop just now. 

How would you like me to test that reviewers are still showing up that were there before? There is a migration that should have moved any existing reviewers into the new set up, without roles by default.

**Comment by emullaney** [comment]
@gibbsmaya 
One more thing to note is that the reviewer roles now show up as icons in the Waiting for your review block on the dashboard.

**Comment by gibbsmaya** [comment]
Can the new 'Assigned role' column in the waiting for your review table display before comments please? i.e. after Reviews.

Review block now does seem to be displaying old reviewers...strange. Although the score is appearing after every review, and there is also a message of "No assignees or reviews yet" appearing when there are review. See https://dev-apply.opentech.fund/apply/submissions/11/ as an example.

**Comment by emullaney** [comment]
@gibbsmaya I've made a change per your feedback on slack and here. New changes:
1. The traffic light only appears above all the staff reviews section (the top part of the reviews, above the horizontal rule that shows up when there are external reviewers in that stage). The traffic light is calculated based on staff reviews only, not external reviews. If no staff reviews have been made, no traffic light is displayed.
2. The messages still show up depending on no reviews in the following ways:
- If no staff reviews have been made display "No reviews yet" above the horizontal rule line.
- If no exernal reviewers have been assigned and we are in external review stage, display "No assignees or reviews yet" below the horizontal rule line

These changes have also been made to the pull request and pushed into develop. 

cc @todd-dembrey

**Comment by todd-dembrey** [comment]
@emullaney I've made two tweaks to the code. One to address Maya's comment about the position of the role icon and the other to tweak the logic of how the review block displays. Happy with this now.

**Comment by todd-dembrey** [comment]
@gibbsmaya with you for review.

**Comment by todd-dembrey** [comment]
@emullaney I merged the branch as i'm happy with the code. if there are any changes coming out of Maya's review we'll open a new branch.

**Comment by gibbsmaya** [comment]
LGTM. Small styling tweak to not show the line underneath the reviewers if there are no AC reviewers (e.g. https://dev-apply.opentech.fund/apply/submissions/5/), but I will get @chris-lawton to sort this on the FE ticket. Assigning to @todd-dembrey for deployment to test.

**Comment by gibbsmaya** [comment]
Apologies, but reopening this as I have found an issue. Waiting for my review block does not show submissions where users is assigned as secondary reviewer.

To test, see Libby Liu's account where she is assigned as secondary reviewer for https://dev-apply.opentech.fund/apply/submissions/17/ but this is not displaying here.

**Comment by gibbsmaya** [comment]
I've worked out why this is - its to do with the logic we apply to which submissions show in the waiting for your review block. This should be resolved by #1009. Putting back into Done.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work follows on from #957, displaying assigned reviewer roles. The best way to test this will be to assign some reviewer roles to some submissions, including yourself, and then check this is displaying as expected on the submission page itself as well as the waiting for my review block on your dashboard, as per acceptance criteria.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
The last criterion doesn't reflect reviewer assignments. Example: I've assigned Di as the second reviewer, but this assignment was not reflected my waiting for review block.

![image](https://user-images.githubusercontent.com/20019656/53527352-bb281000-3ab4-11e9-92e8-ff3b72b1e89e.png)

**Comment by gibbsmaya** [comment]
Hi @fourthletter 

Do you mean that the actual submission does not show in your 'waiting for your review' block? I have just looked at this on the test site and can see that 'Maya Tom Test' is not displaying (which I think is the submission you are referring to above). This is because it is not in status 'internal review' as explained in #937. You can see the role displaying correctly however for the submission 'Testing' which should be on your dashboard in the 'waiting for review' block. Can you confirm this is working as expected?

Thanks,
Maya

**Comment by fourthletter** [comment]
The only submission I am able to view in my dashboard is (image below): https://test-apply.opentech.fund/apply/submissions/11/

Di is a primary or secondary reviewer for submissions below:
https://test-apply.opentech.fund/apply/submissions/15/
https://test-apply.opentech.fund/apply/submissions/16/
https://test-apply.opentech.fund/apply/submissions/17/
https://test-apply.opentech.fund/apply/submissions/5/

![image](https://user-images.githubusercontent.com/20019656/53601953-5daac680-3b7b-11e9-9beb-defc3390da9b.png)

**Comment by fourthletter** [comment]
I accept all the above acceptance criteria. I no longer want to delay the deployment of this feature. Thank you.

**Comment by gibbsmaya** [comment]
Hi @fourthletter I will push this through. Just as a quick note (not blocking this) - the reason those submissions are not displaying in that table is because the table is currently only displaying submissions in status 'internal review'. All of those submissions are in a different state at the moment. This is the issue we covered in our call last week and is being resolved (the logic is being updated) as part of #1009.
