### ISSUE TITLE
Review updates: reviewer consensus: model and interface for agree/disagree

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#960]
Reviewers will be able to indicate if they agree or disagree with another reviewer’s review. Reviewers will be able to indicate their opinion from two buttons within the Review Detail view. 

**Acceptance criteria**
- [x] Two new buttons on review detail page (e.g. https://dev-apply.opentech.fund/apply/submissions/11/reviews/4/), one for agree one for disagree. These should be placed at the bottom of the page underneath the review.
- [x] Functionality limited to OTF staff only and OTF staff reviews only
- [x] You cannot agree/disagree with your own review
- [x] A notification will be created stating `<user> <agrees|disagrees> with <reviewers> review of <submission>`
  * Activity
  * Slack
- [x] Agreeing or disagreeing will have no effect on scores
- [x] Once you have expressed an opinion:  Review Detail view disables the button of the opinion you have selected. Clicking the other button will record your new opinion and send out the relevant notifications.

Design: buttons to follow existing button design patterns 

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by emullaney** [comment]
Hi @gibbsmaya this has been deployed to the dev server. I have to make a change per a review from Todd, but it is probably worth testing now anyway.

**Comment by gibbsmaya** [comment]
All acceptance criteria look good to me when testing. However when testing by following full workflow of primary and secondary reviews - have found one issues which may or may not be related to this work:

Became Libby Liu, added a normal review (she is the primary reviewer), saved as draft. Review now displays in review block as if it is a completed review:
![screen shot 2019-02-20 at 10 03 50](https://user-images.githubusercontent.com/19690895/53083455-df08b600-34f6-11e9-87de-d460d5589df1.png)
Checked this in my own user account and clicked on the review and got a 500 error (presumably because I am not meant to see this draft, which is correct)
https://dev-apply.opentech.fund/apply/submissions/18/reviews/14/. This is maybe one for @todd-dembrey to check?

**Comment by todd-dembrey** [comment]
@gibbsmaya that is an existing issue.

e75ba4a fixes it.

**Comment by todd-dembrey** [comment]
@gibbsmaya Correction. There are two issues there. 

f23777d fixes the issue with drafts appearing in the list.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work is the new ability to agree or disagree with an existing review (which we have named reviewer consensus). This functionality is intended for secondary reviews, however it is not restricted only to users of this role. The best way to test this is to add some agreements/disagreements to reviews and ensure this I working as per the acceptance criteria above. Please note that the display for the agreement/disagreement is covered in #962, and that there is also a separate issue for the behaviour when disagreeing which has some additional steps (covered in #961) so this can be tested alongside those issues.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. Thanks! 💥

**Comment by gibbsmaya** [comment]
Great, thanks @fourthletter. Moving to @todd-dembrey ready for deployment to live.
