### ISSUE TITLE
Review updates: reviewer consensus: disagree behaviour

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#961]
This issue covers the behaviour that should happen when someone disagrees with a review.

**Acceptance criteria**
 - [x] On clicking the Disagree button your opinion will be recorded and you will be redirected to complete a new review (the normal add review form e.g. https://dev-apply.opentech.fund/apply/submissions/1/review/)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by emullaney** [comment]
@todd-dembrey, this is ready for review https://github.com/OpenTechFund/opentech.fund/pull/1045

**Comment by gibbsmaya** [comment]
Something in the latest deployment has removed the functionality of the opposite opinion button being disabled once an opinion has been made. E.g. if you agree with a review then the agree button is then disabled and you can only disagree with that review.

I am also getting a 500 error when disagreeing with a review. Using https://dev-apply.opentech.fund/apply/submissions/5/reviews/10/.

**Comment by todd-dembrey** [comment]
Fixed the issue with the 500 - back to you

**Comment by gibbsmaya** [comment]
LGTM. @todd-dembrey leaving with you for failing test. Happy fr this to be deployed to staging after that.

**Comment by gibbsmaya** [comment]
Test fixed

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work follows on from #960, with some additional behaviour when you disagree with a review.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
Acceptance criteria was functional during test. Thanks!

**Comment by gibbsmaya** [comment]
Great, thanks @fourthletter. Moving to @todd-dembrey ready for deployment to live.
