### ISSUE TITLE
Review updates: reviewer consensus: display

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#962]
This issue covers the display of agreeing/disagreeing with a review.

**Acceptance criteria**
 - [x] Review block on submission detail page: agreement/disagreement shown as 'Agree' or 'Disagree' associated with the parent review (as per screenshot in design section below). 
- [x] Expanded submission on Submissions listing: agreement/disagreement shown in Review outcomes section as 'Agree' or 'Disagree' associated with the parent review. (Image shows location only, no need to match design)
![image](https://user-images.githubusercontent.com/6338661/52418115-47ae6680-2ae5-11e9-8e2c-68dd9d0d7a3b.png)
- [x] Review detail view (e.g. https://dev-apply.opentech.fund/apply/submissions/11/reviews/4/): will show agreement/disagreement from anyone who has agreed or disagreed with the review. A list of:  `<user> <role icon> <agree|disagree>s` will appear in the header to the right of the title.
- [x] View all reviews view (e.g. https://dev-apply.opentech.fund/apply/submissions/6/reviews/) will show agreement/disagreement from anyone who has agreed or disagreed with the review. This will be an extra row above the score with a list as per Review Detail page.

Design:
![image](https://user-images.githubusercontent.com/6338661/52417713-65c79700-2ae4-11e9-808c-7041001d77ed.png)

**Dev Notes**
Table for reviews is constructed here:
https://github.com/OpenTechFund/opentech.fund/blob/7b49da51dcc08407abf3d9a9a94b29fadb849a2b/opentech/apply/review/views.py#L136

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@gibbsmaya We have varied the acceptance criteria here. Your opinion will remain visible regardless of having submitting a review.

This simplifies the logic and is a less surprising behaviour.

**Comment by gibbsmaya** [comment]
AC updated. Thanks.

**Comment by emullaney** [comment]
I've made changes per Todd's review and merged this into develop. It is ready for testing, @gibbsmaya .

**Comment by gibbsmaya** [comment]
This looks good to me. @todd-dembrey does this need a final review or can we mark this as ready for staging?

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work follows on from #960, displaying the agreement/disagreement on reviews. The acceptance criteria describes each of the places this is displayed. This can be tested alongside #960, ensuring that every time you make an agreement/disagreement, it is displayed as expected. Please note that the front end display for this (the styling) is covered in #979 which can also be tested alongside this.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thanks! 💥

**Comment by gibbsmaya** [comment]
Great, thanks @fourthletter. Moving to @todd-dembrey ready for deployment to live.
