### ISSUE TITLE
Is there support in wagtail for multi-level/hierarchical categories?

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#969]
Screening terms and apply categories need this, as well as coming features for additional labels for submission data.

**Comment by Parbhat** [comment]
@danblah Are you pointing to categories present at URL `/admin/categories/category/`? And the requirement is to have categories structured like Pages. Seems like will require a custom implementation.

**Comment by frjo** [comment]
Have you worked with https://github.com/django-treebeard/django-treebeard ? Looks promising.

**Comment by Parbhat** [comment]
Wagtail [uses](https://github.com/wagtail/wagtail/blob/stable/2.2.x/setup.py#L27) `django-treebeard` internally for page tree.

**Comment by frjo** [comment]
@Parbhat Thanks for the tips that is already used by wagtail, found it in `pip list`.

OTF want the new Screening statuses vocabulary to be hierarchical  as well as a yet to be added "Meta" vocabulary. These will be used to tag submissions to help with internal workflow and analytics.

- Animal
    - Dog
    - Cat
    - Rabbit
- Plant
    - Tree
    - Flower

If they tag something with "Rabbit" they want to find it with the tag "Animal as well as "Rabbit".

The Screening statuses vocabulary are created as a standard model and set on submission as a ForeignKey.

https://github.com/OpenTechFund/opentech.fund/blob/7b49da51dcc08407abf3d9a9a94b29fadb849a2b/opentech/apply/funds/models/screening.py#L1-L11

https://github.com/OpenTechFund/opentech.fund/blob/7b49da51dcc08407abf3d9a9a94b29fadb849a2b/opentech/apply/funds/models/submissions.py#L313-L319
