### ISSUE TITLE
Create a new hierarchal "Meta" category for submissions

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#971]
These are terms/labels/categories that are not self-selected by the applicants, but by the OTF team.

**Comment by danblah** [comment]
Setting these labels does not change the edit date or recently edited by labels in the application.

**Comment by frjo** [comment]
Will be using https://github.com/django-treebeard/django-treebeard

**Comment by frjo** [comment]
Place it next to the "Screening Status" category in the Wagtail admin. The "Screening Status" will also later on be converted in to a hierarchal category in the same way as "Meta".

Staff will apply these meta terms to applications and on the other end api requests should be able to select submissions based on the meta tags.

If one pick a meta term that is a parent to other terms all submission belong to the parent and the children should be selected.

**Comment by Parbhat** [comment]
PR #1057
