### ISSUE TITLE
Create a  interface on submission page that allows a team member to see and set meta categories

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#972]
Ideally, w/o leaving or having to reload the page. Labels set on 1st-stage applications should carry over to associates 2nd-state applications.

**Comment by frjo** [comment]
I suggest reusing the way staff today set lead and reviewers etc on submissions.

**Comment by danblah** [comment]
Ability to also flag some categories to only be manipulated by admins/specific roles. others can be defined and edited by staff. Also making sure the archive function carries over here, rather than delete.

**Comment by frjo** [comment]
This is ready for testing on test. Staff can set meta categories and in a block in the sidebar view the ones that have been set.

I have created some terms to test with at https://test-apply.opentech.fund/admin/categories/metacategory/ but please edit to make it more realistic.

**Comment by danblah** [comment]
On the admin side...
* The Root root is super confusing. The root is Meta Categories. Doubly confusing that there is a "+Add Child Category" button that creates things under Root. 
* Can we rename Root?
* Can we create other Roots? 
* I don't want users to have the ability to select terms (ie Animals) that have child terms, ie cat. Is it possible to automatically disallow selection of top-level terms when child terms exist?
* The more I think about it, the more I believe here will never be a need to select a top-level term or a top-level term w/o child-terms
* Got a 500 error when I tried to update/save "Cat" and "Cars". Same with "Cat" and "Unicorn". Same with "Unicorn". Assuming no saving allowed bug :-/

Sooo...

Meta Categories
Cars (not selectable)
- Saab
-- Saab 9-3
-- etc
- Volvo
-- Volvo XC60
-- etc..
Animals
- Cat
-- Bengal
-- etc...
- Unicorn
-- Archaic
-- Alicorn
-- etc...

Hopefully its easy in the data structure to also make a query to see how many submissions have Animals or Unicorn or narrowly Alicorn etc.

On the submission interface (where specific category terms are selected), we need something more clear and efficient. Where it now says "Meta Categories:" and then one drop down, can we have drop downs for each top-level? So there'd be a drop down for Cars, for Animals, etc.

Super excited about this!

**Comment by frjo** [comment]
The "Root" comes from the django-treebeard package and we will not rebuild that. It can, and must, be only one root. My suggestion is just to ignore it. On the front end we do not show it.

**Comment by frjo** [comment]
* I believe we can hide the checkbox for all parent terms.
* I can add and edit terms with out issue or errors. Temporary issue for you?

**Comment by Parbhat** [comment]
Wagtail also uses `django-treebeard` internally for its Page structure. Root at the top is the first root node. Wagtail first root is also there but not usually interacted by admin use. In below screenshot, notice Root at top. The first root node has to be created only once and all main categories can be under it. So, we can name it anything like Meta Categories not required to name as Root. The examples can be

`Meta categories (or Root)> Web development > Python` 
`Meta categories > Web development > CSS` 
`Meta categories > Web development > Javascript`

The first Root (can be named Root/Meta categories) is there for the Tree structure and not usually used by the admin user.

<img width="1280" alt="Screen Shot 2019-05-31 at 11 25 40 AM" src="https://user-images.githubusercontent.com/4817493/58684872-650a8780-8397-11e9-8129-fc7e55970b3d.png">

**Comment by danblah** [comment]
status check here?

**Comment by Parbhat** [comment]
https://github.com/OpenTechFund/opentech.fund/pull/1230#issuecomment-503088385

**Comment by frjo** [comment]
You can now only select leaf terms (terms with no children).

**Comment by danblah** [comment]
Ok, this is a bit easier. Added categories [here](https://test-apply.opentech.fund/apply/submissions/40/) and it didn't crash, w00t! Also, we need an activity entry for this event.

Backing up a bit, I still don't like this interface. It may be the most efficient but I don't find it intuitive. I'd rather see something like the reviewers (which as two boxes for primary and secondary), where there is a box for each branch term with a multiple select for each leaf. Is there any reason why we can't do this? If we choose what we have now and make a UI change later, does that matter to the data?

**Comment by danblah** [comment]
See #1284

**Comment by Parbhat** [comment]
Agree, the interface to select meta categories is not good.

>For example, Animal (a top-level branch with leaves) is the title of a box with a bunch of terms selectable. There is a box for cars, for demographics, etc (any top-level branch). Top-levels will always have leaves (and branches themselves).

Will need to check if this is possible but not seems trivial from an implementation perspective.

**Comment by Parbhat** [comment]
New interface https://github.com/OpenTechFund/opentech.fund/pull/1230#issuecomment-511451273

**Comment by frjo** [comment]
The new interface is now on test for OTF to test.

**Comment by fourthletter** [comment]
[] The search function worked well during test, it was easy to find specific root and child meta categories.
[] The "add meta category" button worked during test, no error messages.
[] The function for creating new root and child meta categories was intuitive and was functional during test.

@danblah let us know what you think. Thanks!

**Comment by danblah** [comment]
We're definitely improved @Parbhat and @frjo. The submission interface is way better. I think we can deploy to live with what we have but the following would be nice for first go:

* Rename Meta Categories to Meta Terms
* Within the submission page's Meta Categories block, Show the top-level categories that the selected ones are within (where the top-level Car is bolded as a header for Saab, Demographics for Gender/Young, etc). If this can be done before going to live quickly, lets do that and deploy to live.

Those items in with the label tags (https://github.com/OpenTechFund/opentech.fund/issues?q=is%3Aopen+is%3Aissue+meta+label%3Atags)

**Comment by Parbhat** [comment]
@danblah @frjo Moved above meta categories required changes to issue #1284.
