### ISSUE TITLE
Implement access to the API via a token, create a new role that have permission to manage tokens

### ISSUE THREAD

**Issue by danblah** [OpenTechFund/opentech.fund#974]
Initially limited to read-only and the meta endpoint. Prefer to have it on a separate domain, api.opentech.fund.

**Comment by Parbhat** [comment]
@danblah How the token will be used? A few more details about the usage will help to decide the package

- Token expire time requirements.
- Can a user generates a Token by making a request or we need Token authentication for internal usage so only admin can create? Which client (Mobile app or) will make the request?

We have three options for a token authentication here

1. DRF inbuilt [token authentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)
2. [django-rest-knox](https://github.com/James1345/django-rest-knox)
3. JSON Web Token using [django-rest-framework-simplejwt](https://github.com/davesque/django-rest-framework-simplejwt)

**Comment by frjo** [comment]
@danblah @Parbhat As I understand it the tokens should be permanent. But I think most services call this a API KEY.

Right now you can only access the API if you are logged in and have the right permissions.

I believe OTF want authorised users to be able to create a API KEY (token) that can be used to access the API until they are revoked.

**Comment by Parbhat** [comment]
@frjo Thanks for the information. Then we will need a different strategy. The above packages are meant to authenticate users with a token. An alternative to current session based authentication so clients like Mobile apps, desktop apps can use the API.

Our use case seems like allowing server-side clients to use our API. These clients (machines) do not have an account on our site but still need to interact with our API. For this requirement [djangorestframework-api-key](https://github.com/florimondmanca/djangorestframework-api-key) will be a good option.

**Comment by frjo** [comment]
@Parbhat let her what @danblah says first. It might be that the keys/tokens should belong to an account. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danblah** [comment]
From a users perspective:
1. User is added to role API Access (or whatever)
2. User has new tab or some interface within https://apply.opentech.fund/account/ named "Access Keys/Tokens" or whatever. Ideally, this tab is only accessible if the user is from an approved domain (opentech.fund) with an active OAuth token, and/or has MFA enabled, and is in this role.
3. User has option to generate new Access Keys, view previously generated keys, and revoke previously generated keys.
4. User generates an Access Key (Access Key ID and Secret Access Key) can give it an expiration date, and provide a short description for its use
5. User can then then submit a json PUSH/GET/PUT request that includes the access key id and secret access key to send/retrieve as needed as they could from the web interface.
6. All requests are logged as from the user as they would be from the web interface but with an additional indication that it was authenticated with an Access Key via the api interface.

That help?

**Comment by Parbhat** [comment]
Sounds good. So, the access token/key is linked to a user account which gives them access to the API. Only users in a group say API access can authenticate themselves using a token along with current session authentication.

**Comment by Parbhat** [comment]
@danblah @frjo The workflow mentioned [here](https://github.com/OpenTechFund/opentech.fund/issues/974#issuecomment-503602234) is not generally used by web apps. The commonly used method is to first get a token using email/username and password by making an API request. The user receives a token and it is sent in Authorization header for subsequent API requests. And token is a single value and not a combination of Access Key ID and Secret Access Key. Mentioning the generally used method before implementing the custom solution. DRF [TokenAuthentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) and [django-rest-knox](https://github.com/James1345/django-rest-knox) both are based on general workflow.

**Comment by frjo** [comment]
@Parbhat  No need for Access Key ID and Secret Access Key as far as I can see,  just one access key/token will do. I believe @danblah just copied how it works on Amazon AWS, overkill for us.

The rest framework gives an example using an auth token with curl:

    curl -X GET http://127.0.0.1:8000/api/example/ -H 'Authorization: Token 9944b09199c62bcf9418ad846dd0e4bbdfc6ee4b'

Looks exactly like what we want. That token the users should be able to retrieve from it's user account on the OTF WebApp. Create and delete as @danblah wrote above.

The django-rest-knox seems to have a better implementation so I would use that.

**Comment by Parbhat** [comment]
Thanks, [django-rest-knox](https://github.com/James1345/django-rest-knox) looks better than DRF token authentication. Is making the first API request using token a requirement? Can not a user just obtain the token first using email and password using Login API? And then create subsequent requests using the attained token. We can create an interface on the web app to generate and manage tokens. But from a security view, tokens should have a short expiry time. Allowing users to manage tokens is not seen commonly.

**Comment by frjo** [comment]
@Parbhat My impression is that requests mainly will come from other webb applications, e.g. something like https://dataviz.opentech.fund/.

@danblah Is that correct or do we have other use cases?

Having them add e-mail and password to the app configuration to be able to get api tokens from OTF Web App is not optimal I think.

**Comment by Parbhat** [comment]
> @Parbhat My impression is that requests mainly will come from other webb applications, e.g. something like https://dataviz.opentech.fund/.

Do not know much about the DataViz platform. From the current look, looks like there are no user accounts. If the requirement is just to access data from OTF via API then [djangorestframework-api-key](https://github.com/florimondmanca/djangorestframework-api-key) is a good choice.

>djangorestframework-api-key allows server-side clients to safely use your API.

>Server-side clients are third-party backends and services (i.e. machines) which do not have a user account but still need to interact with your API in a secure way.

**Comment by frjo** [comment]
@Parbhat The DataViz is an example of an app that would use the API to pull data.

The developer of that site would get an account on the OTF Web App with permissions to generate API tokens. Take that token and add it to the DataViz system so it can pull data from the OTF Web App.

Talked with OTF about this and they would really like to have this API access via token on a separate domain, api.opentech.fund.

**Comment by Parbhat** [comment]
This sounds like an ideal case for [djangorestframework-api-key](https://github.com/florimondmanca/djangorestframework-api-key). Here we want another service like DataViz to access our API. Other options like Django inbuilt token authentication are meant for giving users an option other than session authentication.

The workflow will be:
1. Admin user/a user in a certain group can create, view and revoke API keys (token) via the admin site.
2. API calls can be made using this API key from DataViz platform to access OTF API endpoints. We can only allow access to certain endpoints only using an API key.

@danblah Feedback?

**Comment by frjo** [comment]
Sounds right to me.

**Comment by danblah** [comment]
And me.
