### ISSUE TITLE
Actions: front end tweaks

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#978]
Front end tasks relating to actions to be undertaken in sprint 4.

 - [x] All action modals styled as per batch action modal
 - [x] Disabled batch action buttons styled as per design including on hover explanatory text (appears when a batch action is not able to be performed on the currently selected submissions)
 - [x] Batch determination form (addition of show/hide number of submissions selected) styled as per design
 - [x] Batch determination confirmation modal styled as per design

Design (modal styling): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781107
Design (disabled batch action): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781110
Design (add determination form): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781109
Design (confirmation modal): https://projects.invisionapp.com/share/KZPIO1NENQJ#/screens/342781108

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [ ] tested this feature as an end user.
- [ ] checked that the feature works on the server/s I am deploying it to.

QA:

 * [ ] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [ ] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
FE work is here - https://github.com/OpenTechFund/opentech.fund/pull/1023

Now requires work from BE to hook up, specifically: 

* Hook up disabled batch actions button
* Populate list reveal block on determination form
* Populate modal on determination form
* Hook up modal to submit determination form

**Comment by chris-lawton** [comment]
Blocked until BE work is complete and can be put on dev to test

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

The first two AC are now on dev. 

Thanks,
Chris

**Comment by gibbsmaya** [comment]
Reviewers action modal not yet updated - is this being done as part of #979? Rest of actions look good.

Disabled action looks good. @todd-dembrey can you confirm help text now that you have changed the logic slightly?

**Comment by chris-lawton** [comment]
@gibbsmaya  - Looks like a class got lost somewhere but reviewers action modal now has the updated styling on dev.

**Comment by gibbsmaya** [comment]
Great, can confirm that is now as expected. 

@todd-dembrey re Q above re help text, should we just go with "Status changes can't be applied to submissions with this combination of statuses"?

**Comment by gibbsmaya** [comment]
@chris-lawton confirmed with Todd re the above help text. Please can you update?

**Comment by chris-lawton** [comment]
now updated on dev

**Comment by gibbsmaya** [comment]
LGTM. Assigning back to you for final two AC.

**Comment by todd-dembrey** [comment]
This is included in #1067 as part of the work on #859

**Comment by gibbsmaya** [comment]
Happy with this work. Ready for deployment to test.
