### ISSUE TITLE
Review updates: front end

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#979]
**Acceptance criteria**

- [x] Review block on submission detail page styled as per design:
  - [x] if reviewer assigned but no reviews or agreement/disagreement yet, display as per design (include icon) but greyed out as per current styles 
![image](https://user-images.githubusercontent.com/6338661/52417859-b212d700-2ae4-11e9-94c7-88f4952000a1.png)
  - [x] agreement/disagreement shown as 'Agree' or 'Disagree' associated with the parent review (coloured in green for agree, red for disagree)
  - [x] Traffic light to remain as per current design.
- [x] Expanded submission on Submissions listing: agreement/disagreement shown in Review outcomes section as 'Agree' or 'Disagree' associated with the parent review. Styles based on review block on submission detail page
- [x] Review detail view (e.g. https://dev-apply.opentech.fund/apply/submissions/11/reviews/4/): will show agreement/disagreement from anyone who has agreed or disagreed with the review in the header
- [x] View all reviews view (e.g. https://dev-apply.opentech.fund/apply/submissions/6/reviews/) will show agreement/disagreement from anyone who has agreed or disagreed with the review in a new row above score in the table
- [x] Error notifications styled as per standard notification styles. Try adding the same person as a primary and secondary review and see error notification that appears.

Design: 
![image](https://user-images.githubusercontent.com/6338661/52417713-65c79700-2ae4-11e9-808c-7041001d77ed.png)

**QA criteria**
Dev:

- [x] checked that this feature works across all agreed supported browsers and devices.
- [x] checked that this code meets the agreed accessibility level.
- [x] checked that this code meets the agreed browser performance levels.
- [x] checked that this code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user.
- [x] checked that the feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by chris-lawton** [comment]
Blocked until BE work is complete and can be put on dev to test

**Comment by gibbsmaya** [comment]
One FE tweak required which I noticed as I tested #959:

Reviewer block on submission page: don't show the line underneath the reviewers if there are no AC reviewers (e.g. https://dev-apply.opentech.fund/apply/submissions/5/)

**Comment by gibbsmaya** [comment]
Hi @chris-lawton,

As I have been tested review stuff, I have noticed a small styling tweak required. On review pages, e.g. https://dev-apply.opentech.fund/apply/submissions/5/reviews/10/, when you use the agree button, the agree button should then be disabled when you return to it. And vice versa. This was in place, however something recently seems to have knocked this out. Can you please take a look?

Thanks,
Maya

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,
This and the disabled button styles are now on dev.
Thanks,
Chris

**Comment by gibbsmaya** [comment]
Hi @chris-lawton 

All looks good - just one tweak: need some further styling on the expanded view of a submission in the submissions list - should be based on styles from review block on submission page so we can show relationship between reviews and agree/disagree.

Thanks.

**Comment by chris-lawton** [comment]
Hi @gibbsmaya ,

The following are now on dev:
- dropdown agree/disagree styles (https://dev-apply.opentech.fund/apply/submissions/)
- reviewer icon if they've agreed (https://dev-apply.opentech.fund/apply/submissions/5/)
- disabled batch action tooltips (https://dev-apply.opentech.fund/apply/submissions/all/)
- blue bar on active submission listing should now be visible

Thanks,
Chris

**Comment by gibbsmaya** [comment]
All LGTM.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work is the styling work for the new review consensus workflow, covering styling tweaks for functionality built in #962.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria visible and functional. Thanks!

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Handing over to @todd-dembrey ready for deployment to live.
