### ISSUE TITLE
Submission by round/status detail views: Status tab

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#980]
**Acceptance criteria**

- [x] Status tab in right hand column of detail view page contains "update status" action under an 'Actions to take' label . This should be output as per block in right hand column of submission detail page (e.g. https://dev-apply.opentech.fund/apply/submissions/6/)
- [x] Using update status actions provide same modal and workflow as per actions on individual submission page e.g. attempting to determine a submission will redirect you to the determination page.
- [x] If i update the status of a submission I see a notification confirming the success of the action. "You have successfully updated the status of the submission."  There is a button "OK" which dismisses this notification.

**Design** 
Using existing output as per right hand column of submission detail page (e.g. https://dev-apply.opentech.fund/apply/submissions/6/)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- ~~provided good unit test coverage (if this is non-trivial behaviour).~~
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@tm-kn Approved - can you get it deployed and over to maya for testing please.

**Comment by gibbsmaya** [comment]
Hi @tm-kn 

This looks good. Only issue I noticed is when I tested updating the status from 'ready for discussion' to 'AC review'. Updated correctly but the submission shows in both statuses in the list in left hand column. See screenshot.
![screen shot 2019-02-20 at 10 36 48](https://user-images.githubusercontent.com/19690895/53085791-8e478c00-34fb-11e9-92f3-1c3e63c06dd6.png)
Will this be resolved by #983 or should this be resolved here? After page refresh it displays as expected.

Thanks.

**Comment by tm-kn** [comment]
@gibbsmaya I'll resolve it here. Thanks!

**Comment by tm-kn** [comment]
@gibbsmaya It seems that there's an animation added (for dev - `TransitionGroup`) in the listing and it seems to mess up with re-rendering data. Not sure if it may be worth disabling it and implementing it again later.

**Comment by tm-kn** [comment]
@gibbsmaya I've disabled the animation now. Can you please re-test?

**Comment by gibbsmaya** [comment]
Hi @tm-kn 

It seems to not be functioning when you move to an application further down the list, but does not highlight any applications you select which are above your current position on the list. Any ideas?!

Thanks
Maya

**Comment by tm-kn** [comment]
Merged.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work is adding a content into the Status tab of the Submission by Round/Status views e.g. https://test-apply.opentech.fund/apply/rounds/732/?submission=3 to allow status updates to be made to submissions from this screen. 

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by todd-dembrey** [comment]
To note: the styling is missing on the button in the status bar. We'll fix this in #1016 

![image](https://user-images.githubusercontent.com/6338661/53261464-05337f00-36cc-11e9-9115-88460c7eaac2.png)

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. Thanks! 💥

I do NOT want to hold up this issue, but I do not see the 'Actions to take' label
![image](https://user-images.githubusercontent.com/20019656/53394013-334fe200-399e-11e9-8eed-9fdc2f51d0cf.png)

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey ready for deployment to live.
