### ISSUE TITLE
Submission by round/status detail views: Review information

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#981]
**Acceptance criteria**

- [x] Status tab in right hand column of Submission by round detail view page contains same information as review block in right hand column of submission detail page (e.g. https://dev-apply.opentech.fund/apply/submissions/6/)
- [x] Does not contain "View all" button
- [x] API updated to include list of reviewers. Current API result unchanged. add the following new information:
  * Name
  * URL of review (e.g. https://dev-apply.opentech.fund/apply/submissions/11/reviews/4/)
  * Score
  * Recommendation

Note that the following two will be added to the API in #1016.
  * Role Icon URL
  * List of Agreers & disagreers (Name, icon URL, and opinion only)

**Design** 
Using existing output as per right hand column of submission detail page:
![image](https://user-images.githubusercontent.com/6338661/52417713-65c79700-2ae4-11e9-808c-7041001d77ed.png)

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [ ] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by todd-dembrey** [comment]
@tm-kn Approved, please deploy and assign to maya for testing.

**Comment by gibbsmaya** [comment]
@tm-kn this looks good.

@todd-dembrey a question for you before I ask @tm-kn to make any changes. We are currently only pulling in reviewers who have completed reviews, not the list of all assigned reviewers. With the changes we are making with the reviewer roles, is it worth waiting until that is in so that we only pull in the new assigned review roles, rather than needing to deal with the old style staff reviews?

**Comment by todd-dembrey** [comment]
a) Yes lets handle unassigned reviewers on the roles ticket
b) I guess its more important to see assigned ac reviewers. Do you agree? (in which case we should handle all assigned reviewers regardless of review state)

**Comment by gibbsmaya** [comment]
Yes, I think we need both OTF assigned reviewers, which going forward will be with via the review roles. And we should also pull in assigned AC reviewers. I will put this onto the roles ticket.

@tm-kn can you confirm if any tests needed in the QA checklist and mark as appropriate? Then happy for this to be assigned to Todd and moved into 'Done'.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work is adding review information into the Status tab of the Submission by Round/Status views e.g. https://test-apply.opentech.fund/apply/rounds/732/?submission=3. Note this issue only covers pulling in and display of completed reviews. Review assignments are part of issue #1016.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. Thanks! 💥

I do NOT want to hold up deployment of this issue, but the primary and secondary number does not appear next to reviewer's name:
![image](https://user-images.githubusercontent.com/20019656/53395455-2fbe5a00-39a2-11e9-9088-c8bb178f2ea7.png)

**Comment by gibbsmaya** [comment]
Hi @fourthletter. Thanks for this. Can you confirm which submission you were looking at in this example? Are Tom and Di set as the primary and secondary reviewers? Only if they are assigned the role will the numbers appear.

**Comment by fourthletter** [comment]
@gibbsmaya I made an error, the primary and secondary numbers are visible. It's because "Di" and "Tom" were assigned as reviewers multiple times: https://test-apply.opentech.fund/apply/submissions/6/

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Will pass this to @todd-dembrey ready for live deployment.
