### ISSUE TITLE
Submission by round/status detail view: Status tab: Front end review

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#982]
Front end tidy up of status tabs on detail view (right hand column). Should use existing output as per right hand column of submission detail page (e.g. https://dev-apply.opentech.fund/apply/submissions/6/) but may want to remove the boxes around the different blocks

**Comment by chris-lawton** [comment]
MR for the status modal - https://github.com/OpenTechFund/opentech.fund/pull/1028

**Comment by chris-lawton** [comment]
MR for the reviewers block - https://github.com/OpenTechFund/opentech.fund/pull/1033

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,
The modal styles and reviewer block styles are now on dev.
Thanks,
Chris

**Comment by gibbsmaya** [comment]
Hi @chris-lawton 

A few points below:

 - [ ] Reviewer block has a typo - Assigness instead of Assignees
 - [ ] Header row on the reviewer table should contain traffic light, not yes/no/maybe as per reviewer block on submission detail page
- [ ] When no actions available for updating status, this is currently written in the button - can this be removed with simply the button being disabled? See project DEF https://dev-apply.opentech.fund/apply/rounds/777/
- [ ] While on the status tab, if you switch between submissions int he left hand column, the content changes appropriately but the highlighted submission in the listing does not update

**Comment by gibbsmaya** [comment]
Note there may be further tweaks to do here once #1016 is done.

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

The first three are now on dev. 
The last point i'm unsure on - i don't think any work in this ticket introduced it but am aware of a wider problem with the transition group causing issues with the listings - https://github.com/OpenTechFund/opentech.fund/issues/980#issuecomment-465521554
Worth testing on dev now that Tomasz has disabled the animations - I can't replicate now fwiw.

Thanks,
Chris

**Comment by gibbsmaya** [comment]
Hi @chris-lawton 

First three look good to me. Regarding last comment, have retested and It seems to not be functioning when you move to an application further down the list, but does not highlight any applications you select which are above your current position on the list. Any ideas?! Can screenshare and show you if you can't replicate.

Thanks,
Maya

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

The work done in #991 looks to have fixed this now, which is on dev.

Thanks,
Chris

**Comment by gibbsmaya** [comment]
This is now working well. Over to @todd-dembrey for deployment to test.
