### ISSUE TITLE
Submission by round/status detail views: Status changes by others and messages

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#983]
Messages to be displayed to user on submission by round or submission by status detail views if changes are made to an application whilst they are viewing the application in question.

**Acceptance Criteria**
* Both Detail Views
  - [x] When the submission content of the active submission (questions and meta questions) is updated by someone while i am viewing it I see a notification informing me the content has updated. "The contents of this application have been changed by someone else. "
  - [x] The notification includes a button saying "Show Updated" which when clicked updates the application with the latest changes and removes the notification
  - [x] If i navigate away from a submission I have previously dismissed a notification, next time i view the application i see the latest content.

* Round Detail View
  - [x] When the status of an application i am viewing is changed by someone else i see the notification: "The status of this application has changed by another user."
  - [x] The notification includes the button "OK" which dismisses the notification

* Status Detail View
  - [x] When a submission I am viewing is moved to a different status by someone else I receive a notification informing me of this. "The status of this application has been changed."
  - [x] The notification includes a button "OK" which when clicked hides the notification.
  - [x] When a submission I am viewing is moved to a different status the submission is removed from the sidebar immediately but the content in the middle column remains visible until user clicks on another submission.
  - [x] When I update the status of a submission I see a notification confirming the action "You have successfully updated the status of the submission. Once you navigate away from this submission you will no longer be able to access it from this page.". Behaviour is then the same as for the other person case.

**Design**
Notification to match standard notification design 
<img width="757" alt="screen shot 2019-02-01 at 12 40 49" src="https://user-images.githubusercontent.com/31627284/52123950-952b5f00-261f-11e9-87b9-21191b448ce2.png">

**Comment by tm-kn** [comment]
@todd-dembrey I am unable to test the status detail view because it's not working, but hopefully it should work.

**Comment by todd-dembrey** [comment]
@gibbsmaya I've deployed this to dev. 

It might be worth going through this together as we've subtly changed some of the requirements.

**Comment by gibbsmaya** [comment]
Hi @todd-dembrey 

All acceptance criteria are met for this one but noticed a few odd things while testing that need to be resolved before this can be deemed complete.

 - [ ] There are 2 dismissed states on https://dev-apply.opentech.fund/apply/rounds/732/?submission=11. Why is this?
 - [ ] Notification is acting strangely if you navigate to another submission without updating: the content gets updated but the notification remains and is persistent across multiple submissions.
 - [ ] The order of rounds in the grouped listing is changing as you navigate between submissions.
 - [ ] Styling of notification

Thanks,
Maya

**Comment by todd-dembrey** [comment]
@gibbsmaya I have just deployed changes that should address the above points

- Duplicate dismissed status was due to not keying on the display value and instead using the underlying database value - fixed
- Resetting the selected submission was a bit flaky. I have simplified the code and this is now fixed.
- Ordering was non determinate, I have updated the ordering to be consistent between re-renders
- Notification is now styled in line with other messages.

**Comment by gibbsmaya** [comment]
This all looks good except Dismissed should be at the bottom of the grouped status list - these statuses are ordered by the workflow, so all determined states should be at the bottom.

**Comment by todd-dembrey** [comment]
As discussed we do not have a simple way of identifying this within the listing. This will have to be a future piece of work.

**Comment by gibbsmaya** [comment]
OK thanks @todd-dembrey. Please deploy to test.

**Comment by todd-dembrey** [comment]
This is now on test.

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

I am adding in the testing notes here. @todd-dembrey is yet to deploy this to live, but as soon as he does (very soon!) he will update this to confirm. For when he does - here are the testing notes:

This work is now ready for testing. This work is adding notifications to the detail view pages to update the user if a submission is updated while they are viewing it. It refers to both the submission by round page e.g. https://test-apply.opentech.fund/apply/rounds/732/?submission=11 and the submission by status page e.g. https://test-apply.opentech.fund/apply/submissions/internal-review/?submission=10

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by todd-dembrey** [comment]
This is now on test.

**Comment by fourthletter** [comment]
All acceptance criteria are visible and functional. Thanks!

**Comment by gibbsmaya** [comment]
Ready for live deployment
