### ISSUE TITLE
Repurpose Internal Comments as Notes

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#984]
Internal comments are comments only available to OTF staff. They fulfill the same purpose as Notes do, we will repurpose them to reflect this.

**Acceptance Criteria**
- [ ] There is a tab on the submission detail page with the title "Notes"
- [ ] The "Notes" tab includes an editor with no privacy options
- [ ] The "Notes" tab editor only creates comments of privacy "internal"
- [ ] The "Notes" tab only includes comments of privacy "internal"
- [ ] All "internal" comments are displayed as type "Note"
- [ ] The Activity Feed includes an extra tab of "Notes" which includes only "Notes" as per the "Notes" tab
- [ ] Notes appear on the "All" tab with the label "Note"
- [ ] Listing of "Notes" is grouped by date on both Activity feed Notes tab and "Notes" tab on submission page.
- [ ] "Internal" comments no longer appear in the communications tab
- [ ] "Internal" privacy option no longer appears below the editor for the communications tab

**Dev Notes**
Relevant Comment form areas.
https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/activity/models.py
https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/activity/views.py#L52
https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/apply/activity/forms.py#L10

**Comment by danblah** [comment]
I'm actually keen on there being a "Notes" feature but something that is only for the user.
