### ISSUE TITLE
Review updates: reviewer consensus: updates to table display

### ISSUE THREAD

**Issue by todd-dembrey** [OpenTechFund/opentech.fund#985]
For review summary indicator (traffic lights) wherever they appear: Agreeing with the review will be considered as having left a review of the same outcome. Disagreeing with a review will be considered as having left a review of the opposite outcome, always resulting in an Amber circle

**Acceptance criteria**
- [x] Agreements are reflected in the count of completed reviews in the review column of submission tables
- [x] Disagreements are not reflected in the count of completed reviews in the review column of submission tables
- [x] Disagreements will change a red or green traffic light to amber.

**Dev Note**
Both Disagreement and Agreement will be saved - `for_table` queryset method updated so that `review_submitted_count` includes agreements, and does not include disagreement.
https://github.com/OpenTechFund/opentech.fund/blob/7b49da51dcc08407abf3d9a9a94b29fadb849a2b/opentech/apply/funds/models/submissions.py#L122

`review_recommendation` impacts the traffic light. 
https://github.com/OpenTechFund/opentech.fund/blob/7b49da51dcc08407abf3d9a9a94b29fadb849a2b/opentech/apply/funds/models/submissions.py#L126

**QA criteria**
Dev:

- [x] checked feature meets acceptance criteria/conforms exactly to the specification.
- [x] provided good unit test coverage (if this is non-trivial behaviour).
- [x] checked all tests for the project pass with this feature enabled.
- [x] checked code conforms to the project coding standards.
- [x] had code reviewed by another developer and resolved any issues raised.
- [x] tested this feature as an end user of the website/app (Can I get to it? Is it useable? Can I break it? Does it work in an end-to-end context?)
- [x] checked that this feature works on the server/s I am deploying it to.

QA:

 * [x] tested this feature as a front end user and it meets the acceptance criteria/conforms to the specification and design.
 * [x] checked that the feature works on the server/s deployed to

**Comment by frjo** [comment]
@todd-dembrey Could making sure the list of reviewers being sorted in the same manner in all places be part of this as well?

**Comment by todd-dembrey** [comment]
I've done the bulk of the work fro this ticket and will pick up on it again next friday. 

The only blocking issue is de-duplicating the authors from opinion and reviews (in progress in latest commit)

**Comment by todd-dembrey** [comment]
@frjo I've created a new issue for your comment about the ordering of the reviewers.

**Comment by todd-dembrey** [comment]
@fourthletter @danblah This is deployed to the test instance for review.

**Comment by fourthletter** [comment]
@todd-dembrey Please deploy this feature. Thank you!

**Comment by todd-dembrey** [comment]
Duplicated in #1129. Moving into mini sprint for final implimenation

**Comment by abigail-hampson** [comment]
This is now with Dan for internal review

**Comment by todd-dembrey** [comment]
@abigail-hampson This is now deploying on dev for you to test.

**Comment by abigail-hampson** [comment]
This is now ready for you to test, an example of where this can be tested is here - https://test-apply.opentech.fund/apply/submissions/all/

**Comment by fourthletter** [comment]
Acceptance criteria are visible and functional during test. Thanks!

**Comment by gibbsmaya** [comment]
@frjo this is ready to be deployed to live. Can you include in your next deployment please?
