### ISSUE TITLE
Audit loading and error state display

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#990]
**Acceptance criteria**
- [x] Consistent loading styles on detail view pages:
  - [x] On page load, submission doesn't flash up in middle column before the data loads
  - [x] On page load, when grouped by listing is still loading, other columns should show only one loading panel as opposed to one in each column.
 - [x] Ensure message displayed on detail view page if no submission in round

**Comment by chris-lawton** [comment]
Ready for review

**Comment by chris-lawton** [comment]
Actioned CR feedback so ready for re-review

**Comment by todd-dembrey** [comment]
Re-reviewed maybe one small change as a result? Back to you Chris.

**Comment by chris-lawton** [comment]
Thanks Todd. Have made the error states consistent now, can you take over my last commit? https://github.com/OpenTechFund/opentech.fund/pull/1012/commits/0a8912ec552711dc0a9ab852fb7d8f92419d29f2

**Comment by gibbsmaya** [comment]
Looks good to me @chris-lawton.

Only thing I noticed is that I am getting the following state intermittently for this round: https://dev-apply.opentech.fund/apply/rounds/732/
![screen shot 2019-02-20 at 11 03 24](https://user-images.githubusercontent.com/19690895/53087595-6fe38f80-34ff-11e9-9625-0fa5b1fc34e3.png)

It seem to be struggling to load the applications, if I refresh again it does, but not sure whats going on here and the error state does not look right - the whole page should just be loading, right?

**Comment by chris-lawton** [comment]
Yeah, i noticed this to and it's something that Tomasz has picked up on in the channel. Unsure if it's related to the work done here or another ticket. Best to keep this open and i'll check with Todd to see what's happened.

**Comment by chris-lawton** [comment]
Hi @gibbsmaya,

The work in #991 should fix this which is now on dev.

Thanks,
Chris

**Comment by chris-lawton** [comment]
I stand corrected, can still replicate this on dev.

**Comment by chris-lawton** [comment]
Now fixed on dev

**Comment by gibbsmaya** [comment]
Looks good to me. Over to @todd-dembrey for deployment to test.
