### ISSUE TITLE
Direct links to detail view pages

### ISSUE THREAD

**Issue by gibbsmaya** [OpenTechFund/opentech.fund#991]
**Acceptance criteria**
- [x] Can link to a detail view page with a specific application selected
- [x] When I am on a submission i have a URL `?submission=<id>`
- [x] When i change submissions the URL changes. 
- [x] If i paste a link to a submission the detail view opens on the selected submission
- [x] If i have an invalid link (submission id not in round/status) I see a message telling me this and I default to the first submission.
- [x] If I switch back to the detail view page the URL removes the `?submission=<id>` from the url

**Comment by chris-lawton** [comment]
WIP PR: https://github.com/OpenTechFund/opentech.fund/pull/1022

Needs logic to handle trying to directly access a submission that isn't in the current round.

**Comment by todd-dembrey** [comment]
@chris-lawton I've updated #1022 to better handle submissions that are not in the current set of active submissions.

**Comment by todd-dembrey** [comment]
@gibbsmaya This is now on Dev.

- [ ] When I am on a submission i have a URL `?sumission=<id>`
- [ ] When i change submissions the URL changes. 
- [ ] If i paste a link to a submission the detail view opens on the selected submission
- [ ] If i have an invalid link (submission id not in round/status) I see a message telling me this and I default to the first submission.

**Comment by gibbsmaya** [comment]
@todd-dembrey this looks good and works as you specify. Only thing that I have noticed is that if you then use the switcher to go back to the list view, the url remaining with the `* ?submission=<id>` appended, meaning you then can't link to the list view page.

**Comment by todd-dembrey** [comment]
@gibbsmaya updated to handle back/forward

**Comment by gibbsmaya** [comment]
LGTM

**Comment by gibbsmaya** [comment]
Hi @fourthletter, @danblah, @arduina, 

This work is now ready for testing. This work is adding a unique URL to submission by status/round detail views so you can link to these pages directly. Example page is https://test-apply.opentech.fund/apply/rounds/732/?submission=3.

Please test this against the acceptance criteria noted in the initial issue description.

Please let us know if anything is unclear or if you have any questions. Otherwise please provide feedback of any issues you find or if everything is working as expected, please confirm and we can get this work deployed to the live site and issue closed off.

Thanks,
Maya

**Comment by fourthletter** [comment]
All acceptance criteria were visible and functional during test. Thanks! 💥

**Comment by gibbsmaya** [comment]
Thanks @fourthletter. Assigning to @todd-dembrey ready for deployment to live.
