### ISSUE TITLE
Add name to "Leads" filter

### ISSUE THREAD

**Issue by fourthletter** [OpenTechFund/opentech.fund#999]
Please add my name to the "Leads" filter in webapp. Thank you.

**Comment by danblah** [comment]
@frjo and @todd-dembrey, looks like that list is from
``lead = Select2ModelMultipleChoiceFilter(queryset=get_round_leads, label='Leads')

Where it should be pulling from all users in the role team, which would include submissions that @fourthletter has been assigned as lead, even though they're not assigned as the lead for any rounds.

Submissions are for a number or reasons re-assigned leads that are different than the lead they were initially assigned by the round settings. The reasons could be pushing it to another round lead after one round has concluded (what we have to do cause we can't change a submissions round), the submission was approved and we assign the lead to the person who will oversee the effort, etc.

**Comment by frjo** [comment]
Only leads that are added to at least on round show up in the filter.

Should change this to any staff that is set as lead, or just list all staff accounts.
